### ISSUE TITLE
maven-publish

### ISSUE THREAD

**Issue by tempvchitti** [allegro/axion-release-plugin#102]
Hi
I am using maven-publish to push the release version to release nexus repository. I am using below
script to do 

publishing {
	    publications {
	        mavenJava(MavenPublication) {
	            from components.java
	            
	            artifact sourcesJar {
	                classifier "sources"
	            }
	        }
	    }
	}
	publishing {
		repositories {
			maven {
		          credentials {
		            username nexusUsername
		            password nexusPassword
		          }
		          
		            if(project.version.endsWith('-SNAPSHOT')) {
		            url nexusSnapshotRepoURL
		          } else {
		            url nexusReleaseRepoURL
		          }
		          
			 }
	    }
	}

But , when I run task 'release publish', the version is pushed to snapshot but not to release nexus repository.

Am I doing any mistake.

**Comment by vbuell** [comment]
You cannot release and publish at once. http://axion-release-plugin.readthedocs.org/en/latest/configuration/publishing.html

**Comment by tempvchitti** [comment]
Does that mean I have to create two jenkin jobs for each one, is there any way to combine into one.

**Comment by tempvchitti** [comment]
When I run release and publish separately, it works as expected i.e creates a new version in release nexus repository.

So, when I check the current version it is the release version I see, and I did a checkout from that release I was expecting the current version will show me a snapshot version but not.

Only, if i commit something then it shows snapshot version. If multiple developers checkout the release version , how does the snapshot will work?

**Comment by adamdubiel** [comment]
The algorithm is simple: are you on tag (release)? You get "full" version. If not, it's a snapshot. I don't see a problem with multiple devs checkouting the release version. Maybe [this](http://axion-release-plugin.readthedocs.org/en/latest/configuration/version.html#reading) will help?

**Comment by adamdubiel** [comment]
I will close this issue, let me know if you still have any problems.
