### ISSUE TITLE
Custom or no version incrementer

### ISSUE THREAD

**Issue by petarov** [allegro/axion-release-plugin#112]
Hi,

This is probably a noob question. I'd like to disable the version incrementer and as far as I understand (not really a groovy developer), my only option is to specify a custom incrementer. I do this by specifying:

```groovy
scmVersion {
    versionCreator 'default'
    versionIncrementer { context, config ->  return context.currentVersion.getNormalVersion() }
}
```

However, I keep getting the following Gradle error:

    A problem occurred evaluating script.
    > No signature of method: my_project_98xokvbnnu5zglzjorgfjz1b2$_run_closure1$_closure10.doCall() is applicable for argument types: (pl.allegro.tech.build.axion.release.domain.VersionIncrementerContext) values: [pl.allegro.tech.build.axion.release.domain.VersionIncrementerContext(1.0.0, ScmPosition[branch = develop, latestTag = 1.0.0, onTag = false])]
      Possible solutions: doCall(java.lang.Object, java.lang.Object), findAll(), findAll(), isCase(java.lang.Object), isCase(java.lang.Object)

Am I messing up the parameters or something?

**Comment by adamdubiel** [comment]
Looks like its an actual bug in function invocation. Pass single-argument closure instead:

```
versionIncrementer { context ->  return context.currentVersion.getNormalVersion() }
```

and it will work :)

**Comment by petarov** [comment]
Hey, thanks! It worked, although I had to modify it a little bit:

```groovy
versionIncrementer { context ->  return context.currentVersion }
```

`currentVersion` seems to be a String.

    * What went wrong:
    A problem occurred evaluating script.
    > Cannot cast object '1.0.0' with class 'java.lang.String' to class 'com.github.zafarkhaja.semver.Version'

A fix would be nice. My build definitely won't mind :)

**Comment by vbuell** [comment]
Actually, it's a bug in documentation. Not in the code.

Specifying a _config_ object makes sense for predefined rules only. In other words, you would want to parameterize a predefined rule with this config map (just because it's precontructed), but in case if you use a closure you just don't need that configuration object.

The documentation should state that:

```
    versionIncrementer {context -> ...}
```

**Comment by adamdubiel** [comment]
Oh, you are right, i didn't check the predefined incrementer factory, which actually changes 2 arg closure into 1-arg. Thanks for pointing it out, documentation fix is way easier :)

**Comment by adamdubiel** [comment]
I fixed the docs, they are rebuilding at the moment :)

**Comment by petarov** [comment]
Looks great :+1:
