### ISSUE TITLE
Different versioning schemes in maintenance branches

### ISSUE THREAD

**Issue by szpak** [allegro/axion-release-plugin#114]
I have a library which has maintenance/legacy branch for critical bugfixes for our key users and the master branch with current development. With branch specific `versionIncrementer` I can bump only a patch number, but it would be useful - as a complement to version increments and decorators - to have also a branch specific tag prefix (to not interfere between 2.x in master and 1.3.x in legacy). 

There is quite simple, yet not very elegant, workaround. In the legacy branch tag.prefix could be set to another value (e.g. legacy/) with current legacy version tag manually created (legacy/1.2.2). Therefore if you think it would complicate Axion configuration overly it is possible to live without it :).

**Comment by adamdubiel** [comment]
Okay, i will take a look at this, though should not be very hard.

**Comment by adamdubiel** [comment]
Well, its harder than expected, but i'm halfway done :) Though a lots of places have been touched and lots of tests to fix. On the plus side, no API changes except for adding new config option:

```
scmVersion {
    tag {
        prefix = release

        branchPrefix = [
            "^legacy/.*" : "legacy" // if none matched, prefix is taken, so only put the legacy pattern here
        ]
    }
}
```

**Comment by szpak** [comment]
API looks good to me. It looks consistent with `branchVersionCreators`, so should be easy to memorize.

**Comment by adamdubiel** [comment]
1.3.4 has been released :) It took me a while because i decided to do a major refactor along with this issue: revolutionary spirit. Should have released version with this feature before the refactor though.

**Comment by szpak** [comment]
I've seen that you did some New Year cleanups in code. We will see how good regressions tests really are ;).

Btw, it would be probably good to also have (one day) some [nebula-test](https://github.com/nebula-plugins/nebula-test/)/TestKit acceptance tests for the main paths.

**Comment by adamdubiel** [comment]
Yes, thats on my todo list as a next step (see description in cleanup PR) :) After cleaning up it all should be much easier to do.
