### ISSUE TITLE
Incorrect currentVersion

### ISSUE THREAD

**Issue by chbatey** [allegro/axion-release-plugin#115]
Great work, really like the plugin.

One of my projects appears to be picking up the wrong currentVersion:

```
git tag                                                                   (master) 
k8plugin-0.6.2
k8plugin-0.6.3
k8plugin-0.6.4
k8plugin-0.6.5
k8plugin-1.0.0
k8plugin-1.1.0
k8plugin-1.1.1
k8plugin-1.1.2
k8plugin-1.1.3
k8plugin-1.1.4
k8plugin-2.0.0

```

Current version:

```
./gradlew clean :k8-plugin:currentVersion                                            (master) 
:hystrix-dashboard:clean UP-TO-DATE
:jenkins-jobs:clean UP-TO-DATE
:k8-plugin:clean UP-TO-DATE
:pipeline-plugin:clean UP-TO-DATE
:verification-app:clean UP-TO-DATE
:k8-plugin:currentVersion

Project version: 1.1.5-SNAPSHOT

BUILD SUCCESSFUL

Total time: 0.68 secs
```

Config:

```
scmVersion {
    tag {
        prefix = 'k8plugin'
    }
}
```

I am expecting it to be 2.0.1-SNAPSHOT but getting the  1.1.5-SNAPSHOT

**Comment by szpak** [comment]
Are you on the master's HEAD (in other words is it possible that your commit is not in the time line when the tag for 2.0.0 was created)?

It can be related to recently spotted in my project with CD https://github.com/allegro/axion-release-plugin/issues/116.

**Comment by adamdubiel** [comment]
Do you still have this problem? Reopen the issue if you do :)
