### ISSUE TITLE
Axion ignores tags not available in the current commit time line

### ISSUE THREAD

**Issue by szpak** [allegro/axion-release-plugin#116]
To calculate current version Axion takes only tags which are known in the current commit time line. Therefore `currentVersion` from a branch can report lower current version than from master. It seems to be inconsistent as in case of release the creation of that tag would fail (it already exists - created from master (or some other, more current branch)).

**Comment by adamdubiel** [comment]
axion-release relies on current commit tree and it is supposed to be this way. In the case that you described it might be inconsistent (tags are global, but paths to tags are local), but keeping close to Git means:

* easy implementation
* no need to worry about corner cases
* easy creation of bugfix/hotfix versions (switch over to tag, commit, release)

I don't want to trade this for custom-made logic.

**Comment by szpak** [comment]
Sounds reasonable.
