### ISSUE TITLE
Question: any objection to add an "incrementMajor" option?

### ISSUE THREAD

**Issue by martinda** [allegro/axion-release-plugin#117]
I am tempted to write a pull-request to add incrementMajor, would you have any objection? I have a Jenkins release job that offers the choice to increment the patch or the minor version number, and I would like to give the ability, in the Jenkins job, to increment the Major number as well.

**Comment by adamdubiel** [comment]
Hm, we have those predefined version incrementers that can be used per branch. Maybe, if you want to use them per build, add some `release.verisonIncrementer` command line option that would override `versionIncrementer` setting?

**Comment by martinda** [comment]
This was easier than I thought, so moving the discussion to PR #118.

**Comment by adamdubiel** [comment]
1.3.4 has been released :)
