### ISSUE TITLE
Push says it succeeds but no tag is created

### ISSUE THREAD

**Issue by sephlietz** [allegro/axion-release-plugin#120]
22:49:00.867 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :release
    22:49:00.867 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':release'
    22:49:00.867 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':release' is up-to-date
    22:49:00.868 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':release' (up-to-date check took 0.0 secs) due to:
      Task has not declared any outputs.
    22:49:00.868 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':release'.
    22:49:03.092 [QUIET] [org.gradle.api.Project] Creating tag: release-0.1.1
    22:49:03.232 [QUIET] [org.gradle.api.Project] Pushing all to remote: origin
    22:49:05.375 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':release'
    22:49:05.375 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :release (Thread[main,5,main]) completed. Took 4.508 secs.

So that looks good. But there is no tag after all this is done.

This is a Jenkins build, with " -Prelease.disableChecks -Prelease.pushTagsOnly".

**Comment by adamdubiel** [comment]
This is actually an annoying *feature* of JGit i guess - under specific circumstances no exception is raised even if auth fails. What kind of auth do you use? Are you sure the keys or passwords are okay? Could you also double-check *origin* remote url?

**Comment by sephlietz** [comment]
Thank you. That JGit "feature" was helpful to know. Essentially, I was experiencing a permission error (pushing to Gerrit).

Digging through JGit and then reproducing the push command they use was helpful, as was running createRelease then inspecting the tag.

    # JGit-equivalent push tags command
    git push origin refs/tags/*:refs/tags/*
    
    # Inspect a tag created by the createRelease task
    git show --tags
