### ISSUE TITLE
Release issue on CI environment

### ISSUE THREAD

**Issue by bogdangherca** [allegro/axion-release-plugin#126]
Hi,

I'm trying to do a release with axion-release 1.3.4 on a ci environment using teamcity and I'm getting a GroovyCastException. So, my ci job does this:

- gradlew currentVersion - just to check and see the current version

```
Output:
Failed top open repository, trying to work without it org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/teamcity/TeamCity/buildAgent/work/f70b48429d9242bf
[:currentVersion] 
[14:50:23][:currentVersion] Project version: 0.1.0-SNAPSHOT
```
- gradlew release -Prelease.disableChecks -Prelease.pushTagsOnly -Prelease.customUsername=USER Prelease.customPassword=PASS

```
Output:
[:verifyRelease] Failed top open repository, trying to work without it org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/teamcity/TeamCity/buildAgent/work/f70b48429d9242bf
##teamcity[buildProblem identity='1932123928' description='Execution failed for task |':verifyRelease|'. org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object |'pl.allegro.tech.build.axion.release.infrastructure.DummyRepository@3f87780b|' with class |'pl.allegro.tech.build.axion.release.infrastructure.DummyRepository|' to class |'pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository|'' type='gradleBuildProblem']
```

I'm also concerned about the 'org.eclipse.jgit.errors.RepositoryNotFoundException'. I've also attached the stacktrace. Do you have any ideas/suggestion for what might be causing this?

[cast_exception_stacktrace.txt](https://github.com/allegro/axion-release-plugin/files/99165/cast_exception_stacktrace.txt)

Thanks,
Bogdan.

**Comment by adamdubiel** [comment]
So, i have no experience with Teamcity, but isn't it related to how Teamcity handles git repositories? Quick google revealedd [this stackoverflow question](http://stackoverflow.com/questions/17555931/how-do-i-get-teamcity-to-create-the-git-directory-when-cloning-a-repo-for-build).

**Comment by bogdangherca** [comment]
Indeed, doing a 'ls -lha' on the teamcity agent revealed the fact that the .git dir wasn't pulled from the repo. That was it, I can now do my releases. Thanks for the quick help!
