### ISSUE TITLE
howto: cope with old tag format vX.Y and vX.Y.Z

### ISSUE THREAD

**Issue by gschueler** [allegro/axion-release-plugin#128]
This is not an issue, just how I worked around a problem with existing tags in some repos.  Some were of the form `vX.Y` while others were `vX.Y.Z`.  e.g. `v1.0` and later `v1.0.1`.  I know "1.0" is not actually semver compatible, but it's what was used.

Here is my `scm` clause:

~~~{.groovy}

scmVersion {
    tag {
        prefix = 'v'
        versionSeparator = ''
        def origDeserialize=deserialize
        //apend .0 to satisfy semver if the tag version is only X.Y
        deserialize = { config, position, tagName ->
            def orig = origDeserialize(config, position, tagName)
            if (orig.split('\\.').length < 3) {
                orig += ".0"
            }
            orig
        }
    }
}
~~~

this uses a `v` prefix with no separator.  It then patches the deserialize closure and appends ".0" if the version only has two components.

HTH someone!

**Comment by adamdubiel** [comment]
Thanks! :)
