### ISSUE TITLE
No support for Java 6

### ISSUE THREAD

**Issue by benfortuna** [allegro/axion-release-plugin#130]
I noticed this is compiled with Java 7, and as such won't run with a Java 6 VM. Is it possible to use compiler flags to support Java 6, or is there a reason this won't work with less than Java 7?

Many thanks.

**Comment by benfortuna** [comment]
#131

**Comment by benfortuna** [comment]
Unfortunately the latest JGit has a min Java 7, dependency since 4.0. Even downgrading to 3.7, there is still a Java 7 requirement by GrGit. Unfortunately this isn't really going to be possible without GrGit providing a Java 6-compatible version.

**Comment by adamdubiel** [comment]
That's what i been afraid - Java 7 added some pretty useful APIs and it might not be possible to run it on earlier versions.
