### ISSUE TITLE
verifyRelease leads to ClassCastException on MultiProject

### ISSUE THREAD

**Issue by krasv** [allegro/axion-release-plugin#133]
I'm trying to setup the release plugin for a larger project (~80 modules). cV and nextRelease works fine, if I'm ignoring the org.eclipse.jgit.errors.RepositoryNotFoundException.

The project is structured as:

```
project
  .git/
  product
       build.product
       modules/
           module1/
               submodule1/
              ....
           module2/
            ...
  tools/
  etc/
  ...
```

The source to build are located within "product".
So I set the 

```
scmVersion {
    repository {
        type = 'git'
        directory = project.rootProject.file('..') // repository location
       }
}
```

running gradle within project/product.

Thats issue 1) Whats wrong?

Next point: running gradle verifyRelease breaks with

```
:verifyRelease
Looking for uncommitted changes.. 
Checking if branch is ahead of remote.. 
:modules:verifyRelease
Failed top open repository, trying to work without it org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: ~project/product
:modules:verifyRelease FAILED

* What went wrong:
Execution failed for task ':modules:verifyRelease'.
> Cannot cast object 'pl.allegro.tech.build.axion.release.infrastructure.DummyRepository@1632465d' with class 'pl.allegro.tech.build.axion.release.infrastructure.DummyRepository' to class 'pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository'
```

Note that the folder "modules" does not contain reals source, just a folder for the sub modules...

Thanks for any hint in advance.

**Comment by adamdubiel** [comment]
Hi, i will take a closer look at it in few hours, just wanted to give you  ACK :)

**Comment by adamdubiel** [comment]
Looks like the whole problem is in invalid Git root - the `cV` is working fine on `DummyRepository`, which his loaded when no Git can be found, but it does nothing actually, won't read tags etc etc. Thus don't ignore the `RepositoryNotFound` exception :)

I would start with printing the results of `project.rootProject.file("..")` to stdout sowmewhere in Gradle to see it it points to the right place.

**Comment by mlimat** [comment]
Having a similar issue.

My structure is:
```
main-project
|_ .git
|_ module1
|_ module2
|_ sub-project
|   |_ build.gradle
|_ build.gradle
```

Where `sub-project` is detached from `main-project`'s gradle, but lives in the same repository, i.e. `main-project/.git`

So, in `sub-project/build.gradle` I have:
```
scmVersion {
    repository {
        directory = project.rootDir.parentFile
    }
}
```

However, when I do:
```
$ cd sub-project
$ gradle task
```
I get
```
Failed to open repository, trying to work without it org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /path/to/main-project/sub-project
Could not resolve current position on uninitialized repository, returning default
Couldn't perform check uncommitted changes command on uninitialized repository
```

Note, when I `print(project.rootDir.parentFile)`, I get the correct path: `/path/to/main-project`
