### ISSUE TITLE
Expose base version as well as -SNAPSHOT & -rc

### ISSUE THREAD

**Issue by himslm01** [allegro/axion-release-plugin#136]
`scmVersion.version` gives the version including -SNAPSHOT or including -rc1 (etc).

Presumably you've parsed the tags and know the base SemVer triple of major.minor.patch ?
Could you exposing that in the API?

**Comment by adamdubiel** [comment]
Sorry, this issue somehow slipped. I do have the "raw" version, but it can't be reached easily through the API. This would be kind of "raw" version though, without any decorators/incrementers.

**Comment by himslm01** [comment]
I'm looking for exactly the same version number as `scmVersion.version` but without the -SNAPSHOT or the -rc\d+. I'm trying to save myself from needing to parse `scmVersion.version` and remove those extra parts.
Actually, to be completely honest, three values would be useful:

- `scmVersion.version` as it is
- the major.minor.patch from `scmVersion.version` - I make versioned packages and need the semver triple
- the release type - `SNAPSHOT` or `rc\d+` or null if it's a production release

Yes, I'm just being lazy, not wanting to parse `scmVersion.version`. But, as I say, if you have the values and you concatenate them to make `scmVersion.version` then it would be nice if you could expose the separate parts too ;-)

**Comment by adamdubiel** [comment]
Looks like this issue can be closed as of `1.6.0`. You can access "raw" version via `versionConfig.undecoratedVersion`.
