### ISSUE TITLE
Get previous version

### ISSUE THREAD

**Issue by dafelipe130** [allegro/axion-release-plugin#138]
I've been trawling through the documentation for this but I can't seem to find something about it. Is it possible in the current iteration of the plugin preferably a task on its own?

**Comment by adamdubiel** [comment]
No, currently it is not possible. Do you need just the previous version, or in general list of all versions?

**Comment by dafelipe130** [comment]
Just need the previous version. Just like when you get the incremented version when you call currentVersion with the effective incrementers applied, I'd like to get the previous version counterpart again with the effective incrementers applied.

E.g. 
#gradlew cV
1.11.0-SNAPSHOT

#gradlew pV
1.10.0

**Comment by gschueler** [comment]
I was able to get the previous version with this:

~~~{.groovy}

def getAxionVersion() {
    def ctx = pl.allegro.tech.build.axion.release.infrastructure.di.GradleAwareContext.create(project)
    def rules = ctx.rules
    scmVersion.versionService.currentVersion(
            rules.version,
            rules.tag,
            rules.nextVersion
    )
}

task previousVersion << {
    println "Previous version: ${axionVersion.previousVersion}"
}
~~~

**Comment by mockitoguy** [comment]
+1 to this use case. Previous version is very useful for automatically building the release notes.

This ticket has been filed 5 years ago. Is there a public API currently to expose the previous version?

**Comment by bgalek** [comment]
@mockitoguy seems useful, do you want to implement this? :)
