### ISSUE TITLE
Intermingling different prefix names leads to confusing error

### ISSUE THREAD

**Issue by danhallin** [allegro/axion-release-plugin#140]
I had a project where two different builds used similar version prefixes:
prefix1=PRODUCT
prefix2=PRODUCT_Subproduct

When prefix2 is the last one in commit history, then currentVersion for PRODUCT will pick up the tag for PRODUCT_Subproduct as its tag and somehow fail silently and lead to this rather obtuse error on the line where you do scmVersion.version:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/...../build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':myproject'.
> com.github.zafarkhaja.semver.UnexpectedCharacterException (no error message)

```

I can work around it of course, but the obtuse error made it take a long time to figure out what was going on.

**Comment by adamdubiel** [comment]
I added a way better exception message in #190 :)
