### ISSUE TITLE
gradle cV -q should only return the version string

### ISSUE THREAD

**Issue by levsa** [allegro/axion-release-plugin#143]
It would be convenient if "gradle cV -q" only returned the version string, without extra string or newlines, so that it can be used from scripts etc to get the version:

```
$ echo `./gradlew cV -q`
1.0.0-SNAPSHOT
$
```

**Comment by adamdubiel** [comment]
+1 on this, i don't know if its easy to achieve though. I think we could modify the output of `cV` in general, but i'm a bit afraid it might make existing scripts fail.

**Comment by levsa** [comment]
No problem. I found a better solution, something like :

task printVersion << { logger.quiet version }

**Comment by asarkar** [comment]
@adamdubiel Please see [166](https://github.com/allegro/axion-release-plugin/issues/166) for a use case that we've. Any existing code that parses the string is forced to do so because of the unnecessary prefix. I don't think anyone will be unhappy if they don't have to maintain code they don't need.
Progress is not possible without change. There'd be no butterfly if it stayed in the cocoon.

**Comment by asarkar** [comment]
@levsa Every project that uses Axiom plugin has to declare a new task. I don't understand how's it a  better solution.

**Comment by adamdubiel** [comment]
Maybe it is time to do something about it in 1.5 - at least in `cV -q`. Let me think about it.

@szpak what is your take on this? i know you use Axion a lot, do you have any parsers? I know we do not have them anymore in my company.

**Comment by szpak** [comment]
I've seen those parsers in the similar use cases like asarkar's. Parsing can fail, but the worse would be to parse it incorrectly and start for instance releasing artifacts with bogus version (with some fancy parsers :) ). I you liked to follow SemVer strictly 2.0.0 would be needed. Alternatively an additional task (`currentVersionShort`? `currentVersionOnly`?) could be added to just display the version.

I may exaggerate a little bit as probably for most of the cases the change would make builds fail and parsers would have to be fixed (or there could be an extra flag to keep old behavior - to make migration to 1.5 easier).

**Comment by asarkar** [comment]
Do we've an agreement on this one?

**Comment by adamdubiel** [comment]
I will add `-Prelease.quiet` modifier to suppress `Project version:`. In 2.0.0 this will be the default behaviour.

**Comment by asarkar** [comment]
@adamdubiel Just to be clear, in order to get only the version, I've to run the following command then?
$ `./gradlew cV -q -Prelease.quiet`

**Comment by adamdubiel** [comment]
Yes, exactly.

**Comment by adamdubiel** [comment]
Released in 1.5.0.
