### ISSUE TITLE
Errors when attempting to send a release to github from Jenkins on CentOS

### ISSUE THREAD

**Issue by jtbigwoo** [allegro/axion-release-plugin#145]
We're seeing errors when we attempt to use axion to push a release tag to github.

We're using Axion 1.3.5, Gradle 2.7, CentOS 7.2 and Ncat Version 6.40

Jenkins is running this command:
/var/lib/jenkins/workspace/test_release_job/gradlew --debug --stacktrace release -Prelease.disableChecks -Prelease.pushTagsOnly

Here's the initial error we get when we run our build:
13:07:26.891 [INFO] [org.ajoberstar.grgit.auth.JschAgentProxySessionFactory] NetCat USocketFactory could not be configured: netcat does not support -U option.
13:07:26.892 [DEBUG] [org.ajoberstar.grgit.auth.JschAgentProxySessionFactory] NetCat USocketFactory failure details
com.jcraft.jsch.agentproxy.AgentProxyException: netcat does not support -U option.
	at com.jcraft.jsch.agentproxy.usocket.NCUSocketFactory.<init>(NCUSocketFactory.java:70)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)

After a bit of investigating, I found that I could change /usr/bin/nc to redirect stdout to stderr to get around this error like this:
#!/bin/bash
[[ $1 == -h ]] && ncat $@ 1>&2 || ncat $@

Then I get the following error:
<<Jenkins errors removed here>>
13:14:17.167 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.ArrayIndexOutOfBoundsException: 1024
13:14:17.167 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.jcraft.jsch.agentproxy.Buffer.getByte(Buffer.java:142)
13:14:17.167 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.jcraft.jsch.agentproxy.Buffer.getShort(Buffer.java:138)
13:14:17.167 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.jcraft.jsch.agentproxy.Buffer.getInt(Buffer.java:123)
13:14:17.167 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.jcraft.jsch.agentproxy.Buffer.getString(Buffer.java:181)
13:14:17.167 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.jcraft.jsch.agentproxy.AgentProxy.getIdentities(AgentProxy.java:112)
13:14:17.168 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.jcraft.jsch.agentproxy.RemoteIdentityRepository.getIdentities(RemoteIdentityRepository.java:47)
13:14:17.168 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.auth.JschAgentProxySessionFactory.getJSch(JschAgentProxySessionFactory.groovy:78)
13:14:17.168 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:219)
13:14:17.168 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:175)
13:14:17.168 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:109)
13:14:17.168 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
13:14:17.168 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.TransportGitSsh$SshPushConnection.<init>(TransportGitSsh.java:320)
13:14:17.168 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.TransportGitSsh.openPush(TransportGitSsh.java:166)
13:14:17.168 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:154)
13:14:17.168 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.Transport.push(Transport.java:1200)
13:14:17.169 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:157)
13:14:17.169 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:80)
13:14:17.169 [ERROR] [org.gradle.BuildExceptionReporter] 	at java_util_concurrent_Callable$call$0.call(Unknown Source)
13:14:17.184 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy:114)
13:14:17.185 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy)
13:14:17.185 [ERROR] [org.gradle.BuildExceptionReporter] 	at java_util_concurrent_Callable$call.call(Unknown Source)
13:14:17.185 [ERROR] [org.gradle.BuildExceptionReporter] 	at java_util_concurrent_Callable$call.call(Unknown Source)
13:14:17.185 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
13:14:17.185 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.Grgit.methodMissing(Grgit.groovy:188)
13:14:17.185 [ERROR] [org.gradle.BuildExceptionReporter] 	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.callPush(GitRepository.groovy:103)
13:14:17.185 [ERROR] [org.gradle.BuildExceptionReporter] 	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.push(GitRepository.groovy:96)
13:14:17.185 [ERROR] [org.gradle.BuildExceptionReporter] 	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.push(GitRepository.groovy:92)
13:14:17.185 [ERROR] [org.gradle.BuildExceptionReporter] 	at pl.allegro.tech.build.axion.release.domain.scm.ScmRepository$push$3.call(Unknown Source)
13:14:17.185 [ERROR] [org.gradle.BuildExceptionReporter] 	at pl.allegro.tech.build.axion.release.domain.scm.ScmService.push(ScmService.groovy:29)
13:14:17.186 [ERROR] [org.gradle.BuildExceptionReporter] 	at pl.allegro.tech.build.axion.release.domain.scm.ScmService$push.call(Unknown Source)
13:14:17.186 [ERROR] [org.gradle.BuildExceptionReporter] 	at pl.allegro.tech.build.axion.release.domain.Releaser.pushRelease(Releaser.groovy:44)
13:14:17.186 [ERROR] [org.gradle.BuildExceptionReporter] 	at pl.allegro.tech.build.axion.release.domain.Releaser$pushRelease$0.call(Unknown Source)
13:14:17.186 [ERROR] [org.gradle.BuildExceptionReporter] 	at pl.allegro.tech.build.axion.release.ReleaseTask.release(ReleaseTask.groovy:17)
13:14:17.186 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
13:14:17.194 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
13:14:17.194 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
13:14:17.194 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
13:14:17.194 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
13:14:17.195 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
13:14:17.195 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
13:14:17.195 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
13:14:17.212 [ERROR] [org.gradle.BuildExceptionReporter] 	... 60 more

I've attached the test project I used to generate this error.
[temp-build.zip](https://github.com/allegro/axion-release-plugin/files/402633/temp-build.zip)

**Comment by adamdubiel** [comment]
I'm not an expert here myself, but could you try disabling agent options?

```
./gradlew release ... -Dorg.ajoberstar.grgit.auth.sshagent.allow=false -Dorg.ajoberstar.grgit.auth.pageant.allow=false
```

I don't know if you used `ssh-agent` to authenticate here, but we can see if it makes it goes away.

**Comment by jtbigwoo** [comment]
It made that particular problem go away and with a little research I was able to get the rest of the way.

So without the ssh-agent, I had to add the private key via the following option: -Dorg.ajoberstar.grgit.auth.ssh.private=<path to key>

Then I had to work around the following exception that it seems like others have seen before: 
com.jcraft.jsch.JSchException: UnknownHostKey: github.oursite.com. 
RSA key fingerprint is 22:fb:ee:fe:18:cd:aa:9a:9c:78:89:9f:b4:78:75:b4

It turns out that my known_hosts file had a ECDSA key for the remote server instead of a RSA key.  So I had to do the following (steps stolen partially from these answers on stackoverflow: http://stackoverflow.com/a/15314924 http://stackoverflow.com/a/34478483)

1. Log in as the jenkins user
`sudo su jenkins -s /bin/bash`
2. Delete the line from ~/.ssh/known_hosts for github.oursite.com
3. Load the RSA key for github.oursite.com by attempting to ssh there
`ssh -o HostKeyAlgorithms=ssh-rsa jtbigwoo@github.oursite.com`

Then it worked!  Thanks so much for your suggestion.

**Comment by adamdubiel** [comment]
So what you can actually do is to use [SSH authorization](http://axion-release-plugin.readthedocs.io/en/latest/configuration/authorization.html#ssh-key-password) from axion-release. It also disables those `ssh-agent` options and it gives you a nice way to pass all ssh stuff. Let me know if it worked for you :) Closing the issue.

**Comment by kknd22** [comment]
we encounter this issue in jenkins using this plugin. Finally we figure out that this is space in the jenkins job name. After removing the space, the issue got resovled.
