### ISSUE TITLE
Tag selector picks rc over release version

### ISSUE THREAD

**Issue by asarkar** [allegro/axion-release-plugin#146]
In [ScmRepository.groovy](https://github.com/allegro/axion-release-plugin/blob/1de6a06b4c1ff88291e039223820cc5a7c80b096/src/main/groovy/pl/allegro/tech/build/axion/release/domain/scm/ScmRepository.groovy)

```
public static final Closure<String> LAST_TAG_SELECTOR = { List<String> tags ->
    tags && tags.size() > 0 ? tags[-1] : null
}
```

The tag selector picks the last one in the list but the order of tags seems to be undeterministic. This causes `2.1.0-rc1` to be picked over `2.0.0` from a list `[2.0.0, 2.1.0-rc1]`.
Why not do this `tags.split { ~/.*-rc\d+$/ }.find().max()`?

**Comment by adamdubiel** [comment]
Go ahead :) In my opinion having multiple tags on a single commit is kind of a corner case. However if you wanted to change the default behaviour, then i'm afraid this regexp won't suffice - am i right it would not work for `[2.0.0, 2.1.0]`? Ideally it would just pick the highest version, but to do that it needs to be parsed.

If you have time to create this kind of pull request it would be a welcome addition to axion-release :)

**Comment by abhijitsarkar** [comment]
@adamdubiel 
> it would not work for [2.0.0, 2.1.0]

Why not?

```
def tags = ['2.0.0', '2.1.0']
tags.split { ~/.*-rc\d+$/ }.find().max()
Result: 2.1.0
```

**Comment by adamdubiel** [comment]
Hm, you are right - it works nicely. Okay, great - how about a PR with this small change? :)

**Comment by abhijitsarkar** [comment]
A quick PR attempt failed 18 tests. That's more than I can handle right now. Perhaps another day.
