### ISSUE TITLE
How to validate Git tags

### ISSUE THREAD

**Issue by asarkar** [allegro/axion-release-plugin#159]
If I wanted to impose a tag naming convention, or in other words, disallow some tags, how could I do that? I need a hook that gets called no matter the task.

**Comment by adamdubiel** [comment]
What do you mean by "disallow some tags"? You configure the tag prefix in `build.gradle` and only this prefix is used. Can you give an example of expected behaviour?

**Comment by abhijitsarkar** [comment]
What I meant is to fail the build if the Git repo has tags we don't wanna see. Like a tag ending in SNAPSHOT.
I'm asking what'd be a good place to check the Git tags and fail the build if necessary.
