### ISSUE TITLE
Next version after 2.1.0-beta is 2.1.1

### ISSUE THREAD

**Issue by szpak** [allegro/axion-release-plugin#162]
Having the latest tag `2.1.0-beta` the next version resolved by Axion when a default incrementer is used is `2.1.1`. I would expect `2.1.0` which is resolved when `2.1.0-alpha` is found.

Steps to reproduce (tested with Axion 1.2.3 and 1.4.1):

```
git tag release/2.1.0-beta HEAD~
gw cV
```

Possibly to be fixed by the way of #157.

**Comment by adamdubiel** [comment]
I think it might be solved by #156 actually :)

**Comment by szpak** [comment]
It was looking promising as I had duplicated tags at first, but after putting a tag on a separate commit the version is still resolved incorrectly. I even build a version from that PR (rebased with master) and the problem persists :(.

**Comment by adamdubiel** [comment]
I think this was recently fixed in #266 - there were a bunch of bugs with version resolution on `HEAD`.
