### ISSUE TITLE
gradle release currentVersion returns SNAPSHOT version

### ISSUE THREAD

**Issue by janbols** [allegro/axion-release-plugin#164]
When I do `gradle release currentVersion`, it creates a new release f.e. `1.15.7`, but returns `1.15.7-SNAPSHOT` as the current version:

```
gradlew release currentVersion
:verifyRelease
Looking for uncommitted changes..
Checking if branch is ahead of remote..
Checking for snapshot versions..
:release
Creating tag: release-1.15.7
Pushing all to remote: origin
:currentVersion

Project version: 1.15.7-SNAPSHOT

BUILD SUCCESSFUL

Total time: 1 mins 9.741 secs
```

I think I understand why that is: my project version is set like the following: `project.version = project.scmVersion.version`. Both `project.version` and `project.scmVersion.version` are set at config time and when the release task finishes, they're not supposed to change.

Is there any way to overcome this or is this just the way things are. You're not supposed to call another task that depends on the new version after releasing. If so, it might be useful to include that in the wiki.

Thanks
Jan

**Comment by adamdubiel** [comment]
This is how things are, there are ways to force rereading of the version, but it won't change the fact that `project.version` once set will not change.  You are right about putting this in docs.

**Comment by adamdubiel** [comment]
However if you want to do some simple actions you can use pre and post release hooks which always access the new version.

**Comment by janbols** [comment]
Yes, right. Thanks
