### ISSUE TITLE
currentVersion adds unnecessary prefix "Project version: "

### ISSUE THREAD

**Issue by asarkar** [allegro/axion-release-plugin#166]
A sample `./gradlew -q cV` output is `Project version: 2.3.0-SNAPSHOT`. The "Project version: " part is completely unnecessary and requires more effort on the user to actually get the version. In our project, we use the version to figure out what Maven and Docker repo to publish to, and the unnecessary verbosity forces us to parse the string.
It is beyond obvious that the output of a command `currentVersion` is the project version. There's no need for any window dressing. Just printing the version string is good enough.

**Comment by szpak** [comment]
See #143 why it's not so easy to preceded and a workaround.

**Comment by asarkar** [comment]
Duplicate to 143.

**Comment by adamdubiel** [comment]
Released in 1.5.0.
