### ISSUE TITLE
Publish task does not exist

### ISSUE THREAD

**Issue by ProTrent** [allegro/axion-release-plugin#167]
gradle publish

Task 'publish' not found in root project...

**Comment by szpak** [comment]
And... ?

Where have you found that Axion provides the `publish` task? It's not mentioned in [the documentation](https://axion-release-plugin.readthedocs.io/en/latest/configuration/tasks.html).

**Comment by ProTrent** [comment]
http://axion-release-plugin.readthedocs.io/en/latest/configuration/publishing.html mentions
`./gradlew release
./gradlew publish`

AND

http://axion-release-plugin.readthedocs.io/en/latest/ mentions `./gradlew publish`

I'm not sure what it's supposed to do, but they don't work.

**Comment by adamdubiel** [comment]
While `axion-release` does not define `publish` task, i mentioned it because it is a well-known task for publishing artifacts that comes from Gradle builtin [maven-publish](https://docs.gradle.org/current/userguide/publishing_maven.html) plugin.

**Comment by ProTrent** [comment]
Ah, cool. Well, you might want to make that clearer. I was trying to test out this plugin and thought it was broken.

**Comment by adamdubiel** [comment]
yes, you are right, i created PR for this: https://github.com/allegro/axion-release-plugin/pull/168
