### ISSUE TITLE
Expose scmVersion as part of the project output

### ISSUE THREAD

**Issue by ProTrent** [allegro/axion-release-plugin#169]
Expose the SCM (git) build hash tag as part of the output to allow for something akin to:

Optionally expose an 'undecorated' version or an option to not decorate.

scmVersion: {
    version: 1.0.0-SNAPSHOT,
    scmVersion.tag: b818b16
    undecoratedVersion: 1.0.0
}

**Comment by adamdubiel** [comment]
I need some additional clarification about the `undecoratedVersion` field.

*decorated* in axion-release domain means version with some additional information like branch name, which is only used in `scmVersion.version`, but never in tag names. For example:

```
$ git branch
my-branch

$ ./gradlew cV
0.1.0-my-branch-SNAPSHOT
# ^ this is decorated version

$ git checkout master
$ ./gradlew cV
0.1.0-SNAPSHOT
# ^ decoration changes with e.g. branch name, depending on decorator used
```

So if i only stripped `-SNAPSHOT` from version, you would still get something like `0.1.0-my-branch` and not `0.1.0`. Is this what you mean by `undecoratedVersion`?

**Comment by adamdubiel** [comment]
@ProTrent any thoughts? I'm having some time to develop this small stuff, so could just finish this up. I would lean towards `undecoratedVersion` being `0.1.0`.

**Comment by ProTrent** [comment]
Yeah, undecoratedVersion would be the version without the 'decoration' step appended to it, so '0.1.0' would be perfect.
