### ISSUE TITLE
Are there any Maven analogues to this plugin?

### ISSUE THREAD

**Issue by dafelipe130** [allegro/axion-release-plugin#173]
Not really an issue towards this plugin but a cry for help.

I work with both Maven and Gradle projects but initially Maven. When we started using Gradle, we had already had it in mind to use this plugin given how we are so on board with the thinking behind it and how it's easy to customize to our process.

Now, we're humming along quite nicely with our Gradle projects via this plugin. Not so much in Maven as I always find myself trying to replicate the behavior of this plugin in our Maven projects with a series of inline scripts in our CI server which I feel is very ugly.

Going back to the subject, are there any Maven plugins out there that operate exactly like what this plugin does or at least close enough?

**Comment by adamdubiel** [comment]
I'm not familiar with any direct replacement, but i also haven't been using Maven for a long long time. I know [maven-git-commit-id-plugin](https://github.com/ktoso/maven-git-commit-id-plugin) which exposes a lot of Git info as build variables, you can probably achieve similar effects with some configuration.

**Comment by dafelipe130** [comment]
Thanks for the quick response!

Yeah, I've already looked into that plugin and it really wouldn't put a dent on my homebrew stuff compared to lets say a Maven version of Axion with version creation and releasing all baked in into one plugin.

If I may, I'd like to keep this issue open and hopefully get some sort of traction concerning this request.

**Comment by bgalek** [comment]
@dafelipe130 I think after few years without traction there won't be any ;) cheers!
