### ISSUE TITLE
SNAPSHOT vs release 

### ISSUE THREAD

**Issue by KhagayN** [allegro/axion-release-plugin#199]
Hello,

Thank you for creating this. 

I am trying to release an artifact using the plugin but, every time I do a gradle cV, I get SNAPSHOT appended to it. I did a git pull of the repo I am using and without committing anything else, I did a gradle cV -Prelease.releaseVersion=1.34.0. I get back an artifact 1.34.0-SNAPSHOT but, I would like it without the SNAPSHOT suffix b/c I want to release and upload a non-snapshot. Any recommended course of action?

I see on the Read The Docs page that a "SNAPSHOT" is appended when not on a tag. I then ventured to create a tag via git tag -a 1.34.0. That however still does not remove the "SNAPSHOT" suffix.

Thanks

**Comment by adamdubiel** [comment]
This is because you use annotated tags (`-a`). Please create normal, lightweight tag (`git tag <tag name>`) and it should work just fine.

**Comment by KhagayN** [comment]
I deleted all tags and created a lightweight tag. Then, I ran gradle cV -Prelease.forceVersion=1.34.0 but, it still creates an artifact with "-SNAPSHOT" appended.

**Comment by agusmba** [comment]
Do you have any uncommitted/modified/untracked files? Depending on your configuration for dirty repos it could be a cause...
Try `git status` to check

**Comment by KhagayN** [comment]
There are no uncommitted/modified/untracked files.

**Comment by adamdubiel** [comment]
Can you paste your axion configuration? (`scmVersion` section)

**Comment by KhagayN** [comment]
```
scmVersion {
    versionIncrementer 'incrementMinor'

}

```

**Comment by adamdubiel** [comment]
The default configuration sets `release-` as tag prefix. Only tags with this prefix are used to determine version. Since you create `1.3.4`-like tags, you need additional config:

```
scmVersion {
    versionIncrementer 'incrementMinor'
    prefix = ''
    versionSeparator = ''
}
```

You can see it all in [docs](http://axion-release-plugin.readthedocs.io/en/latest/configuration/overview.html).

**Comment by KhagayN** [comment]
Thank you for the help. Would it be possible to add that configuration to a pre-release hook? 

The reason I ask is because when I create a commit after a release, the SNAPSHOT keyword is appended to the name of the artifact. I would like to remove that SNAPSHOT keyword and just have the tag number b/c I use it to reference a dependency with the same tag number. Would it be possible to remove that keyword from scmVersion.version in a pre-release hook?

**Comment by adamdubiel** [comment]
Ah, i mistyped, sorry for this, they should be indeed in `tag` section:

```
scmVersion {
    versionIncrementer 'incrementMinor'
    tag {
        prefix = ''
        versionSeparator = ''
    }
}
```

So the error you are getting is pretty verbose :) If you set tag prefix to `<empty>` every single tag in your repository will match it. This means that you should basically have only version tags in your repo. This is why the default prefix is `release-`. However you wanted to keep tags in `1.2.3` not `release-1.2.3`, so i showed you the config.

You can list all tags with `git tag` and see if there are some unwanted ones. I guess you have `release-0.1.1` tag as a side effect of testing the plugin. If that is the case, you should be able to safely remove it.

Before you start adding pre/post hooks, please make sure the config is sane and suits your needs. Adding a commit adds -SNAPSHOT and this is the core idea behind this plugin. Every unreleased (untagged) piece of code is a SNAPSHOT, only tags guarantee that the code will not change. You can either make commits before release (which would make sense if this is a change that should be shipped with this release), or switch to tag in git and push the artifact from tag (without the commit you made after the release).

**Comment by adamdubiel** [comment]
Let me know if this fixed your problem, until then i will close the issue (feel free to reopen it).

**Comment by SchwiftyRick** [comment]
Hi Adam,
what if it is necessary to use annotated tags? Is there some workaround? 
Thanks and KR
Martin
