### ISSUE TITLE
Can not release? Looking for uncommitted changes.. FAILED

### ISSUE THREAD

**Issue by conanchen** [allegro/axion-release-plugin#202]
Hi, 

Please refer to my build.gradle : https://github.com/conanchen/hiask-api-sexyimage/blob/master/build.gradle

Why the release step always look into the no used files e.g. taskHistory.bin? 

sc:hiask-api-sexyimage admin$ ./gradlew release -Prelease.pushTagsOnly

> Task :verifyRelease
Looking for uncommitted changes.. FAILED

Staged changes:

Unstaged changes:
    modified: .gradle/4.1/fileHashes/fileHashes.lock
    modified: .gradle/4.1/taskHistory/taskHistory.lock
    added: .gradle/4.1/taskHistory/taskHistory.bin
    added: .gradle/4.1/taskHistory/fileSnapshots.bin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':verifyRelease'.
> There are uncommitted files in your repository - can't release. See above for list of all changes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by adamdubiel** [comment]
axion-release implements couple of pre-release checks. They try to verify if you have uncommitted changes or if your changes are ahead of remote origin, which usually is unwanted situation. All checks are described in [docs](http://axion-release-plugin.readthedocs.io/en/latest/configuration/checks.html#uncommited-changes-check).

You can disable them either in configuration or using command line flags, refer to docs for details.

**Comment by bigwaff** [comment]
Typically, `.gradle` directory is listed in the `.gitignore` file and axion-release will ignore. It appears that @conanchen 's `.gradle` directory is not. It's probably safe to close this issue.
