### ISSUE TITLE
Push task silently ignores rejection from remote server

### ISSUE THREAD

**Issue by adamdubiel** [allegro/axion-release-plugin#203]
If there is any kind of remote-side validation of pushes and it fails `axion-release` silently ignores errors and prints success, instead of failing the build.

#### Steps to reproduce

Create new repo:

```
mkdir restricted-remote-repo
git init
touch some_file
git add -A
git commit -m "Initial commit"
```

Add pre-receive hook which always fails with error message:

```
echo "echo 'This push will fail!'; exit 1" >  .git/hooks/pre-receive
chmod +x  .git/hooks/pre-receive
```

Clone newly created repo into new dir:

```
git clone /home/..../restricted-remote-repo axion-release-repo
```

Add build gradle with axion-release and run release command:

```
gradle release -Prelease.disableChecks
```

This should end with success, while under the hood everything failed and no commits have been pushed to remote. However tag has already been created, so we end up with bad state.

#### Expected behaviour

Release task should fail, printing message from remote. If task failed, created tag should be removed (tag and push should be in a sort of "transaction").

#### Implementation notes

* most of changes can be done in `GitRepository` class
* `GrGit#push` does not even return error status (nor throws exceptions), so raw `JGit` has to be used
* for testing: when used with local repo, `JGit` will not run `pre-receive` hooks (no support for it), so some other fail has to be simulated for testing purposes (maybe ahead of remote?)

**Comment by mareckmareck** [comment]
I will check this out and attempt to come up with something
