### ISSUE TITLE
Multiple axion calls

### ISSUE THREAD

**Issue by KhagayN** [allegro/axion-release-plugin#205]
I would like to run the release and upload gradle tasks but I pass parameters to gradle release: -Prelease.disableChecks.

If I want to run both of these tasks with the parameters should I do 

gradle release tasks -Prelease.disableChecks

or 
gradle release -Prelease.disableChecks tasks

Thanks.

**Comment by adamdubiel** [comment]
`-P...` parameters are Gradle build parameters, they are available for all tasks. So it doesn't matter how you specify them, axion-release will pick them up.

**Comment by KhagayN** [comment]
I see. The reason I can is because I ran the former and creates the tag but, doesn't run the upload. I solved this problem by first running the release task and then the upload task.

**Comment by adamdubiel** [comment]
I don't think there is any explicit ordering when it comes to tasks. If you want to enforce order, you need to do so in `build.gradle` with `dependsOn` method (see Gradle docs for details).

**Comment by KhagayN** [comment]
I understand. thank you for the help and the tool!
