### ISSUE TITLE
Snapshot version dependency version check limitations

### ISSUE THREAD

**Issue by jghandour** [allegro/axion-release-plugin#206]
The SnapshotDependenciesChecker does not work in some circumstances. 

1. It does not detect a snapshot buildscript in the 'buildscript' section.
`
buildscript {
dependencies {
        classpath 'pl.allegro.tech.build:axion-release-plugin:1.9.0-SNAPSHOT'
    }
}
`

2. It does not work when you are using the spring dependency management plugin to resolve the versions (https://github.com/spring-gradle-plugins/dependency-management-plugin).

I'm not sure on the proper solution, but it seems using  'it.buildscript.configurations'  and 'resolvedConfiguration' will give you the required information.

A colleague has a potential fix for the second issue in this branch:
https://github.com/hexsel/axion-release-plugin/commit/1bb508cd1b1cb2748c8785c94c53df613c030b07

**Comment by adamdubiel** [comment]
I can merge the potential fix, as long as you can test it with your corner-cases :) Sorry for ignoring this issue for so long, i just noticed that it is still open.

**Comment by nerderma** [comment]
I'm trying to figure out some of the inconsistencies with the SnapshotDependenciesChecker. Some of mine will be verified, but it seems like anything defined as constraints at the top level are verified either, similar to the dependency-management-plugin mentioned above I believe.

**Comment by nerderma** [comment]
@adamdubiel Tagging you just to call this out again. I know this thread is old, but felt it contained useful background over creating a new issue.

**Comment by ghilainm** [comment]
I would also add that it does not work with Gradle rich versions like latest.release and latest.integration. The plugin (could) automatically lock the versions in such case. That would enforce fixed versions on release.
