### ISSUE TITLE
readVersion on HookContext casts DecoratedVersion to String

### ISSUE THREAD

**Issue by brunorene** [allegro/axion-release-plugin#207]
the readVersion() method on HookContext returns a regular toString() output instead of the decorated version

change from 

`String version = versionService.currentDecoratedVersion(rules.version, rules.tag, rules.nextVersion)`

to 

`String version = versionService.currentDecoratedVersion(rules.version, rules.tag, rules.nextVersion).decoratedVersion`

**Comment by adamdubiel** [comment]
Why would you like to change this behaviour? I did it to minimise the amount of public API. If i expose `DecoratedVersion` object i can no longer change it without potentially breaking things. If i know exactly what you need, i might be able to solve our problem in some other way :)

**Comment by adamdubiel** [comment]
Did you found a way to achieve what you wanted? Please reopen if not :)
