### ISSUE TITLE
Having used "markNextVersion" in past, can't seem to get the tool to create the "right" versioning

### ISSUE THREAD

**Issue by kmandeville** [allegro/axion-release-plugin#218]
This is probably not an "issue" with the plugin but with the way we've used it, but I could still use some assistance. We've run into occasional issues with the plugin not correctly incrementing the version number after doing a "release" build in a CI build (so the release number keeps getting incremented when builds run on our release branch and tags are created, but the "currentVersion" was not getting set to the next patch version up plus "-SNAPSHOT". It would get stuck it seemed. So we had used the "markNextVersion" to try to force it to set the "right" version. Now those tags exist (-alpha) and our "currentVersion" is stuck in the past as the documentation states. So we have the following tags: 

release-1.0.1
release-1.0.10
release-1.0.11
release-1.0.2
release-1.0.3
release-1.0.4
release-1.0.5
release-1.0.6
release-1.0.6-alpha
release-1.0.7
release-1.0.8
release-1.0.9
...
When a release build is run, the release number is incremented, but the "currentVersion" is now stuck at 1.0.6-SNAPSHOT because of the -alpha tag I assume?. I tried deleting the -alpha tag but when I do, the "currentVersion" returns 1.0.5-SNAPSHOT instead of 1.0.12-SNAPSHOT like I would expect. 

What am I doing wrong here?

**Comment by adamdubiel** [comment]
I guess you figured it out? :)

**Comment by kmandeville** [comment]
Yup :)

Related question though? 

So I pushed to release branch, ran the build and got the right next release version I expected of 1.0.12. I merged back from release branch to master and in master branch I'm getting "currentVersion" of 1.0.12 instead of 1.0.12-SNAPSHOT that I expected. How does it know to put -SNAPSHOT or not? 

Sorry for my ignorance on the subject. New to release management side of things

**Comment by adamdubiel** [comment]
From the readme :)

```
If current commit is tagged commit, project has a release version. If there were any commits after last tag, project is in SNAPSHOT version.
```

What we often do is add `versionCreator` like:

```
scmVersion {
    versionCreator 'versionWithBranch'
}
```

Which appends branch name to version if you are not currently on master branch:

```
$ git branch
some-branch
$ ./gradlew cV
0.1.0-some-branch-SNAPSHOT
```

If master is not your main branch, you can create your own simple branch creator as described in [docs](http://axion-release-plugin.readthedocs.io/en/latest/configuration/version.html#decorating).
