### ISSUE TITLE
master and release branches

### ISSUE THREAD

**Issue by kmandeville** [allegro/axion-release-plugin#219]
I haven't found anything that could help point us in the right direction to use the Axion plugin with the way we're working, which doesn't seem like it's far off from how many companies work. 

We work in the master branch. At regular intervals, we merge what's in master to a release branch. We then run a "release" build. The Axion plugin is able to properly set the release build versions using tags. But it seems that because the release branch commits are the one's being tagged, the build on the master branch does NOT see the commits tagged on the release branch. So our release branch tags are up around 1.0.11, but the "currentVersion" on the master branch is a lot lower and out of sync.

Could you help point me in the right direction for how we should be using this in this two branch process?

**Comment by adamdubiel** [comment]
Hi! What i think most of people in this situation do is merge tags back from release to master branch. Axion analyses only current branch, it has no idea about the existence of other branches and tags on it.

**Comment by kmandeville** [comment]
I've realized after i wrote this that we should be doing that but i still
wanted to confirm that is the expected process.

Thank you

**Comment by adamdubiel** [comment]
Great :) Closing this one then.

**Comment by bthom1** [comment]
Just trying to wrap my around this plugin so I can make use of it.  We too work on master and release branches. After reading the docs I have the following questions on this topic...

If you merge tags back from release to master branch then how is parallel work/release tags for both hotfix and next major version work?  For example, if we have released 2.0.0 on the release-2.0.0 branch with a tag, and now we are currently using master for 2.1.0 work, and today we create release tag 1.0.1 on the hotfix/1.0.1 branch. If we merge the the v1.0.1 tag back to master work, what will currentVersion on master be? 

Rather than merging tags back to master, should we be using the configuration options and/or MarkNextVersion method? i.e.
useHighestVersion = true
or the MarkNextVersion method "Create next-version marker tag, that affects current version resolution. Tag is pushed to remote. See Next version markers for details"

**Comment by kmandeville** [comment]
FYI, we ultimately switched to a more explicit approach with another plugin where we set the version of the branch in a file in that branch. Causes some problems occasionally when merging since you don't want to merge that file but at least it's more explicit what the version is. I still really wanted to figure out how to use this plugin with our process, but I just couldn't get it consistently enough.

**Comment by bthom1** [comment]
reading the current docs, I think the way to handle this is use the markNextVersion method in the plugin on your master branch.  By default that adds a tag in the master branch set to your next version with a default suffix of "-alpha" which is treated differently than regular version tags, and the suffix is configurable. 
See: (https://axion-release-plugin.readthedocs.io/en/latest/configuration/next_version/#next-version-markers)
Also I think you would have to have the tag strategy set to the default "First tag encountered" (useHighestVersion = false) 
See [tagging](https://axion-release-plugin.readthedocs.io/en/latest/configuration/version/#reading)

**Comment by adamdubiel** [comment]
@bthom1 in your scenario the mix of what you described (next versions + use highest) will work the best probably. I imagine the following situation after merging all the branches you described:

````
A -- release-2.0.0 -- B -- release-2.1.0-alpha -- C -- release-1.0.1 -- D
````

The following version will be shown when using `./gradlew cV`:

* `1.0.1` iff `useHighestVersion == false`
* `2.1.0-SNAPSHOT` iff `useHighestVersion == true`

Mind, that `useHighestVersion` is not on by default, as it forces full scan of Git tags, which might take some time for huge repos.

**Comment by agusmba** [comment]
If you don't want to use `useHighestVersion` you could simply tag again your release branch after merging the production hotfix:

    A -- release-2.0.0 -- B -- release-2.1.0-alpha -- C -- release-1.0.1 -- D -- release-2.1.0.alpha.2

**Comment by bthom1** [comment]
@adamdubiel thanks for the clarification. One other question, a bit off topic, what is the best way to set things up so that my release branches start incrementing with rc.1 (e.g. rc.1, rc.2 etc)? I want the 'rc' and # separated by a dot to make it easier for any external tools that need to parse the version.

**Comment by bthom1** [comment]
@adamdubiel Thanks, I will try incrementMinorIfNotOnRelease and branchVersionIncrementer incrementPrerelease for release.*.

My understanding (perhaps I'm misunderstanding) of the semver spec is that '-rc.1' is a valid prerelease value, and will allow for numeric comparison of a dot separated field in the prelease version as opposed to lexical comparison which results in 'rc2' > rc12.

Here is the text from semver that led me to want to use a '-rc.#' scheme for the numerical comparison....

"9. A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version"

11. ...
"Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0."

So I assume this means '1.0.0-rc.2' is less than '1.0.0-rc.12', and with no dot separator '1.0.0-rc2' is greater than '1.0.0-rc12'. Notice they have an example of a dot separated numerical filed in the prerelease verion in the last sentence "1.0.0-rc.1".  Please let me know if I'm misunderstanding?  I'm trying to make use of the plugin for our 1st release branch next week :-)

**Comment by adamdubiel** [comment]
Oh, great :) My mistake, it is semver compliant, somehow i thought there must be no dots in prerelease.

However I don't know if current implementation of `incrementPrerelease` will work with dot notation, so you should probably give it a try or read the tests/source code. Anyway i think it should work :)
