### ISSUE TITLE
Determine next version based on predefined version incrementer

### ISSUE THREAD

**Issue by asarkar** [allegro/axion-release-plugin#220]
I'm looking to know the next version without actually making any changes to the repo, sort of like the `currentVersion`. I'd like to set up versioning rules in the build file and then ask the question "what is the next version?". Is this possible?

**Comment by adamdubiel** [comment]
It is not possible currently, you would have to create `nextVersion` task in axion plugin.

**Comment by asarkar** [comment]
Seems to me a useful task to have. I think release does some of it, but not quite. If implemented, release could use it as well.

Would you consider this as a feature request?

**Comment by adamdubiel** [comment]
Yes, although i have a very limited time for development.
