### ISSUE TITLE
Only push the new release tag instead of all tags

### ISSUE THREAD

**Issue by cliffred** [allegro/axion-release-plugin#224]
Currently, the axion-release-plugin pushes all tags when creating a release, and will therefore potentially also push tags that were unintended. Wouldn't it be cleaner if only the newly created release tag is pushed, or is this a conscious decision?

I've implemented this in a branch https://github.com/cliffred/axion-release-plugin/tree/push-release-tag-only and it seems to work, but I have not tested it thoroughly. I justed wanted to know if you like the idea.

**Comment by adamdubiel** [comment]
This is a great suggestion! I will take a look at the code.

**Comment by cliffred** [comment]
I'll try to create a test and look at your comment some time this week.

**Comment by cliffred** [comment]
I've added a test,
see https://github.com/cliffred/axion-release-plugin/commit/f7c6b4c28f4ddc8f2949984242c032b7043eee84

But I'm not sure how to handle the PushReleaseTask and HookContext as they also do pushing, and at that time you don't know the release tag.

**Comment by bgalek** [comment]
@cliffred how do You feel about creating PR to the main repo?:)

**Comment by cliffred** [comment]
@bgalek Last time I stumbled upon the problem of handling pushing in PushReleaseTask and HookContext. I can't remember the exact details, but I will look at again this weekend.
