### ISSUE TITLE
Could not resolve current position on uninitialized repository

### ISSUE THREAD

**Issue by amimas** [allegro/axion-release-plugin#225]
Hello,

I've been reading the guides/docs for this plugin for awhile now and finally decided to try it out. I'm applied the plugin in one of my project. When I run `sh gradlew currentVersion`, I get the following response:

```
> Configure project : 
Failed to open repository, trying to work without it org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /Users/amimas/projects/hello-world/master
Could not resolve current position on uninitialized repository, returning default
Couldn't perform check uncommitted changes command on uninitialized repository

> Task :currentVersion 

Project version: 0.1.0-SNAPSHOT

BUILD SUCCESSFUL in 0s
```

I'm not sure if this is because of my project's layout or if I mis-configured something. My project layout is like this:

```
+ hello-world <git-repo>
   + subproject1
   + subproject2
   + master
       + gradle/wrapper
       - build.gradle
       - settings.gradle
       - gradlew
       - gradlew.bat
```
As you can see, my root project is in the `master` directory. Inside the `master\build.gradle`, I added the plugin and only applied very basic configuration, which look like this:

```gradle
plugins {
	id 'pl.allegro.tech.build.axion-release' version '1.9.0'
}

scmVersion {
	tag { prefix = 'v-' }
}

project.version = scmVersion.version

allprojects {
	project.version = scmVersion.version
}
```

**Comment by adamdubiel** [comment]
The thing is that `axion-release` expects Git repository root to be at project root by default.

However you can change this, as described in [Repository section docs](http://axion-release-plugin.readthedocs.io/en/latest/configuration/repository.html):

```
scmVersion {
    repository {
        directory = project.rootProject.file('../')
    }
}
```

In general a good place to start when looking if something can or can't be done in axion-release is to look at [configuration overview](http://axion-release-plugin.readthedocs.io/en/latest/configuration/overview.html) :)

**Comment by amimas** [comment]
Thanks a lot for the hint. That worked out fine.
