### ISSUE TITLE
Release jgit error Transport Exception..  USERAUTH fail

### ISSUE THREAD

**Issue by philbeiler** [allegro/axion-release-plugin#23]
So I have my project cloned using ssh://git@host:xxxx/blah/blah.git I can perform all get actions without being prompted for a password or authentication.

When I do the gradle release -  it does all of the work

Creating tag: release 1.0.0
Pushing all to remote: origin
:release FAILED

TransportException: ssh://git@xxx/blah/blah.get USERAUTH fail

caused by PushCommand.java 160
caused by JschConfigSessionFactory.getSession 142
caused by jsch.JSchException : USERAUTH fail
UserAuthPublicKey.start(UserAuthPublicKey.java: 120)

I did a git push --tags and they all when to the server without issue...

**Comment by philbeiler** [comment]
Question...  Why does this not work?  I created a depends on task to provide  your customKeyFile and customKeyPassword properties before the release plugin executes?

task releasePreparation << {
   release.ext.customKeyFile = "......"
   release.ext.cutomKeyPassword = credentials.ssh
}
release.dependsOn releasePreparation

If I specify the -P options -- the plugin works perfectly.. However when I use my method above - it fails.  I can do a release.hasProperty("....") for both values and they are there...

Are they getting resolved when plugin loads, which is too early?  Verses when it executes?

What am I trying to accomplish?
 -- I don't want my password in the command history of the shell for one. - don't want to hard code these things or ask users to plug them in
-- We are using a password encryption plugin to grab passwords during execution.  - no clear text
-- I was able to make customKeyFile a standard  for us -- $HOME/.ssh/id_rsa

My strategy seems sounds -- it just does not work!!!  Thanks for any guidance.

**Comment by adamdubiel** [comment]
Strategy is flawless :) I guess it's becasue i read -P options on plugin apply (to initialize git repo), not task run. So any change in -P after plugin has been applied is not visible to axion-release. I need to see if i can move this to tasks body. Opening #37 for this.
