### ISSUE TITLE
ScmPosition.branch is set to commit hash istead of HEAD since version 1.9.0

### ISSUE THREAD

**Issue by cliffred** [allegro/axion-release-plugin#230]
Since version 1.9.0, probably since commit 5a6d2d6, the value of ScmPosition.branch changed from HEAD to the commit hash if the repo is in a detached head state (checkout of a specific commit).

Example:
```groovy
versionCreator = { version, position ->
    return "${version}-${position.branch}"
 }
```
```> git checkout 56e5e1113ab55e567d9e918860fa001eecc903cb```
**In 1.8.3:**
```
> gradle currentVersion
Project version: 1.0.1-HEAD-SNAPSHOT
```
**In 1.9.0:**
```
> gradle currentVersion
Project version: 1.0.1-56e5e1113ab55e567d9e918860fa001eecc903cb-SNAPSHOT
```

**Comment by adamdubiel** [comment]
Thanks for pointing this out, i will take care of it.

**Comment by adamdubiel** [comment]
GrGit used different method to get branch name. I used default JGit methods, which in detached state returned commit id. I changed the code to mimic what GrGit did.
