### ISSUE TITLE
Two tags on the same commit behavior clarification

### ISSUE THREAD

**Issue by lwasylkowski** [allegro/axion-release-plugin#236]
When we have one commit with two tags -- say `1.0.0` and `1.1.0-alpha`, the computed version is always the 1.1.0-SNAPSHOT one. We were thinking of having a flow where we release a version, and immediately mark the new one for development. This doesn't seem possible with current behavior, since after marking new release we're not able to infer current stable release.

Our reasoning is that stable version should have higher priority here, since there are no commits made for the next version yet. However I've seen some issues that already requested some specific behavior in this case, so I'd like a clarification on what's the suggested approach and whether there's some option that we can use to achieve what we want.

I'm willing to submit a pull request if it makes sense and isn't a ground-breaking change.

**Comment by adamdubiel** [comment]
Stable version should always have higher priority. This is also enforced by test in project itself. This was a bug in the first place and it was fixed in 1.7.2. Which version are you using?

**Comment by lwasylkowski** [comment]
I'm using `pl.allegro.tech.build:axion-release-plugin:1.9.0` from gradle plugin portal (although imported in a custom plugin, not via `plugins{}` block, but I think that doesn't matter.

This is my functional test:

```
println(runTasks("cV", "-Prelease.quiet", "-q").output)
println("-----")
println(runTasks("release", "-Prelease.version=1.0.0", "-q").output)
println("-----")
println(runTasks("markNextVersion", "-Prelease.version=1.2.0", "-q").output)
println("-----")
println("-----")
println(runTasks("cV", "-Prelease.quiet", "-q").output)
println("-----")
println(git.tagList().call().joinToString { it.name })
```

This is the output:

```
0.1.0-SNAPSHOT

-----
Looking for uncommitted changes.. 
Skipping ahead of remote check
Checking for snapshot versions.. 
Creating tag: release/1.0.0
Changes made to local repository only

-----
Creating next version marker tag: release/1.2.0-alpha
Changes made to local repository only

-----
-----
1.2.0-SNAPSHOT

-----
refs/tags/release/1.0.0, refs/tags/release/1.2.0-alpha
```

I don't think we change anything significant in the configuration:

```
repository.pushTagsOnly = true
ignoreUncommittedChanges = false
localOnly = true // Never push to the remote repository
tag.prefix = "release"
tag.versionSeparator = "/"
```

**Comment by lwasylkowski** [comment]
I think the test you're thinking about verifies two tags specifying the same version (`should prefer normal version to nextVersion when both on same commit`), only one is next version marker, the other is stable. Our case would be described by this scenario: 

```groovy
def "should prefer normal version to newer nextVersion when both on same commit"() {
    given:
    repository.tag('release-1.1.0-alpha')
    repository.tag('release-1.0.0')

    when:
    VersionContext version = resolver.resolveVersion(defaultVersionRules, tagRules, nextVersionRules)

    then:
    version.previousVersion.toString() == '0.1.0'
    version.version.toString() == '1.0.0'
    !version.snapshot
}
```

**Comment by adamdubiel** [comment]
You are right, i missed this detail. PR would be great if you have time and means for it :)

**Comment by lwasylkowski** [comment]
Fixed by https://github.com/allegro/axion-release-plugin/pull/237. I see there are other PRs waiting for the review, and I know you're busy -- do you have any plans for some next release, or maybe snapshots are published automatically?

**Comment by adamdubiel** [comment]
I didn't have time to take a look at the other one yet. I will publish this one asap, as there is one more bugfix waiting for a release.
