### ISSUE TITLE
Android Flavor Support?

### ISSUE THREAD

**Issue by kkovach** [allegro/axion-release-plugin#241]
I have an Android library that has 2 flavors and I'm having a hard time figuring out if I can get this plugin to work with them. Specifically, I'd like to tag and release each of the flavors separately if possible. The problem I'm running into is that the prefix is different for each of the flavors. I believe this is the case. Or, at least how I was imagining it and trying to get it working.

Has anyone done this? I can provide more details about what I have and what I'd like to do if necessary. Thanks.

**Comment by adamdubiel** [comment]
I'm closing this issue, but if you still have this problem (or found the solution you would like to share - don't hesitate to reopen).

**Comment by kkovach** [comment]
Well, it appears that I must have moved on and forgotten about this question/issue but am now interested again. I'm wondering if maybe someone else has become interested in it since then? I love this release plug-in but am wondering again if we can get it to work with the Android Gradle Plug-in (AGP) and it's build variants? https://developer.android.com/studio/build/build-variants

To answer your question from 2 years ago. I have a single project, but with the AGP the source can be split into different directories under the project for differences in source, with the majority being the same and shared. If that makes sense.

I've attached a example gradle build file. Thanks!

[axion-release-flavor-example.txt](https://github.com/allegro/axion-release-plugin/files/4880262/axion-release-flavor-example.txt)

**Comment by kkovach** [comment]
@adamdubiel  Is there anything else I can help provide on this? I know it's been a long time, and I would like to reopen this issue, but I don't know that there's an actual way to reopen issues in Github? Thanks!
