### ISSUE TITLE
Wrong version name

### ISSUE THREAD

**Issue by YevhenDuma** [allegro/axion-release-plugin#243]
Hi,

I've created few releases in master branch using axion-release plugin, and everything looks good.
I've got tags:
release-1.1.0
release-1.1.1
release-1.1.2
release-1.1.3

But when I run on develop branch, I am getting next:
./gradlew cV -Prelease.useHighestVersion -Prelease.forceSnapshot

> Task :currentVersion 

Project version: 1.1.1-SNAPSHOT

but as I understand it should be 1.1.4-SNAPSHOT, right?

Thanks!

**Comment by adamdubiel** [comment]
Yes, but `axion-release` traverses commits only in current branch. So if you created tags in other branches and never merged them, you won't see those tags i commit tree, thus you won't see the newest version. You can read more [in docs](http://axion-release-plugin.readthedocs.io/en/latest/configuration/version.html#first-tag-encountered).

**Comment by YevhenDuma** [comment]
So the solution is to merge from master to develop in my case, right?

Even if I am fetching all tags? 
Even with -Prelease.useHighestVersion ?

**Comment by adamdubiel** [comment]
Yes :) Fetching all the tags does not make them visible when traversing commit tree in current branch.

**Comment by YevhenDuma** [comment]
thanks a lot @adamdubiel for your answers.

Will you consider to add some flag to check all tags, not only in current branch? :)

**Comment by adamdubiel** [comment]
Frankly: i would review & merge PR, but probably will have no time to code it :)

**Comment by adamdubiel** [comment]
Just create a PR if/when you have time, i will close this issue.

**Comment by YevhenDuma** [comment]
Thanks a lot!
