### ISSUE TITLE
Commit is pushed without branch

### ISSUE THREAD

**Issue by Fodoj** [allegro/axion-release-plugin#244]
Tagging as it is works fine for me, but when I add simple hook to change the gradle.properties file and they perform release, commit is pushed without any branch attached to it, so it's just a tag and commit on it and that's it.

Not sure how to debug it even :-)

Ah, and this happens in TeamCity only, locally it works fine. I can confirm that in TeamCity repo is _not_ in detached state though.

**Comment by adamdubiel** [comment]
Hm, when debugging this kind of issues on bamboo i just added stuff like `git remote show origin` just to see the real state of repository. I don't know how to help you in any other way, i never encountered this issue :)

**Comment by adamdubiel** [comment]
Did you manage to find the solution?
