### ISSUE TITLE
Managing version numbers on merging

### ISSUE THREAD

**Issue by pslootweg** [allegro/axion-release-plugin#248]
We have our 'release' code on the 'master' branch, and then develop on ```'bugfix/.*', 'hotfix/.*', 'feature/.*' or 'release/.*'``` branches.
For each of these I would like to use the patch/patch/minor/major version incrementors - which seems to work, but...

When we merge back to master, the version number there does not reflect the branch that was merged - it just increments the patch number.

I know of the existence of ```markNextVersion```, but that requires manual intervention. I want the 'master' branch version to depend on the branch that is merged.

Can this be done?

**Comment by adamdubiel** [comment]
If i understand correctly, you could achieve it by creating release on one of those branches and then merging to master. This would create tagged commit with expected version. However i know that his approach might not be "clean" (releasing from sth else than master). Currently `axion-release` knows nothing about branches that were merged. You can take a look at discussion in #52 , maybe it will help somehow?

**Comment by adamdubiel** [comment]
I'm closing this one - in case you need more help or want to discuss it more - just reopen :)
