### ISSUE TITLE
Multi-module with multiple version

### ISSUE THREAD

**Issue by farrukhnajmi** [allegro/axion-release-plugin#251]
The https://github.com/allegro/axion-release-plugin/blob/master/docs/configuration/basic_usage.rst page says:

> Multi-module with multiple versions
> Sometimes it might be desirable to release each module (or just some modules) of multi-module project separately. If so, please make sure that:
> 
> - tag prefixes for each module do not overlap, i.e. !tagA.startsWith(tagB) for each permutation of all tag prefixes
> - keep in mind, that scmVersion must be initialized before scmVersion.version is accessed
> - apply plugin on each module that should be released on it's own

I have a multimodule project with following module structure:

- my-services
  - a
    - a-client (client API for a-service )
    - a-service (a-service impl)
  - b
    - b-client (client API for b-service )
    - b-service (b-service impl)

I would like to increment version of a-client and a-service together, and increment version of b-client and b-service together. The end result I want is that after createRelease:
- there is a single tag created for: a, a-client and a-service
- there is a single tag created for: b, b-client and b-service

I would like to accomplish this with the least change to my project structure and naming as possible.

Currently on first createRelease I get tags:

- my-services-0.1.0
- a-0.1.0
- a-client-0.1.0
- a-service-0.1.0
- b-0.1.0
- b-client-0.1.0
- b-service-0.1.0

On second createRelease I get error:

```
Execution failed for task ':bid:createRelease'.
> Failed to parse version: a-client-0.1.0 that matched configured prefix: a. There can be no tags that match the prefix but contain non-SemVer string after the prefix. Detailed message: Unexpected character 'LETTER(c)' at position '0', expecting '[DIGIT]'
```

Can you please suggest what I need to do.

Thanks for a great plugin!

**Comment by farrukhnajmi** [comment]
It appears that the plugin works as expected if I do createRelease task on just the client and service modules:

gradle a:a-client:createRelease a:s-service:createRelease 

This seems like an adequate solution to me. Please let me know if there are gotchas I should be aware of with this model.

**Comment by adamdubiel** [comment]
I think this should be okay, since as far as i understand `a` is not really a module. I think what you could do is ignore `a` and `b` when applying plugins, sth like:

```
configure(subprojects - project(':a') - project(':b')) {
   apply plugin: `axion-release`
}
```
