### ISSUE TITLE
version starts from scratch after deleting working directory

### ISSUE THREAD

**Issue by YevhenDuma** [allegro/axion-release-plugin#252]
Hi,

I have gradle+Jenkins+axion-release-plugin for automated versionning.

After I've deleted Jenkins working directory, gradlew cV started to show version 0.1.1. 
Git tag shows that I have tags release-1.1.20 for example, so I am expecting to have version 1.1.21.

Regards

**Comment by YevhenDuma** [comment]
`.\gradlew release -Prelease.forceVersion=1.1.19

> Task :verifyRelease FAILED
Looking for uncommitted changes..


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':verifyRelease'.
> Cannot get property 'aheadCount' on null object`

**Comment by adamdubiel** [comment]
Hi,

What do you mean by "deleted Jenkins working directory"? How does your flow look like? Does everything work on localhost?

Also for this `FAILED` job, can you run it with `-s` and post stacktrace?

**Comment by YevhenDuma** [comment]
Hi Adam,

I guess I found issue: for some reason there was tag adde - release-0.1.0.
So it took last tag (sorted by time I guess) and increased.

I guess I won't be able to find why that tag was added, so you can close this issue.

Thanks. alot!

**Comment by YevhenDuma** [comment]
I have Jenkinsfile which has next functions:

`def doCheckout() {
    if (!isUnix()) {
        echo "Adding support for longpaths."
        bat 'git config --global core.longpaths true'
    }
    checkout scm
    if (env.BRANCH_NAME == 'develop') {
        echo "Merging from master to develop..."
        if (isUnix()) {
            sh 'git pull origin master'
            sh 'git fetch --all'
        } else {
            bat 'git pull origin master'
            bat 'git fetch --all'
        }
        echo "Done"
    }
    if (env.BRANCH_NAME == 'master') {
        echo "Fetching all tags..."
        if (isUnix()) {
            sh 'git fetch --all'
        } else {
            bat 'git fetch --all'
        }
        echo "Done"
    }
}`

`def publishReleaseToNexus() {
    stage('Nexus Release Publish') {
        if (isUnix()) {
            sh './gradlew clean -Prelease.disableChecks -Prelease.pushTagsOnly release  --stacktrace --console=plain'
            sh './gradlew publish generateDeploymentConfig --stacktrace --console=plain'
            stash includes: 'ansible/**/*', name: 'ansible'

        } else {
            bat 'gradlew.bat clean -Prelease.disableChecks -Prelease.pushTagsOnly release --stacktrace --daemon --console=plain'
            bat 'gradlew.bat publish generateDeploymentConfig --stacktrace --daemon --console=plain'
            stash includes: 'ansible/**/*', name: 'ansible'
        }
    }
}`
and:

`general.doCheckout()
nexus.publishReleaseToNexus()`

**Comment by adamdubiel** [comment]
It is not sorted by time :) `axion-release` traverses the commit tree until it finds first tag with matching prefix. You can change this behavior by switching to [useHighestVersion](http://axion-release-plugin.readthedocs.io/en/latest/configuration/version.html#tag-with-highest-version). This however forces `axion-release` to lookup all commits in current tree.

**Comment by YevhenDuma** [comment]
Another case

git tag
release-1.1.19
release-1.1.2
release-1.1.20
release-1.1.3
release-1.1.4
release-1.1.5
release-1.1.6
release-1.1.7
release-1.1.8
release-1.1.9
v0.1.0
v0.1.1
v0.2.0

.\gradlew cV

 Task :currentVersion

Project version: 1.1.20

But expected was 1.1.21-SNAPSHOT

**Comment by adamdubiel** [comment]
You got full version, so were there any commits after `release-1.1.20` tag? Looks like you are currently on this tag.

**Comment by YevhenDuma** [comment]
You are right! thanks a lot.
