### ISSUE TITLE
Changelog needs updating

### ISSUE THREAD

**Issue by punit-shah** [allegro/axion-release-plugin#255]
The most recent version documented in the changelog (http://axion-release-plugin.readthedocs.io/en/latest/changelog.html) is 1.8.0, even though the latest version of the plugin is now 1.9.2.

It would be nice to see what has changed between versions.

**Comment by punit-shah** [comment]
Found https://github.com/allegro/axion-release-plugin/blob/master/docs/changelog.rst after creating this issue, sorry!

Still, is there a reason the linked docs site doesn't have this?

**Comment by adamdubiel** [comment]
Hi, no, there is no reason for it to stay this way. Probably sth broke in docs build, i will take a closer look at it.

**Comment by adamdubiel** [comment]
I changed format of docs to mkdcos (i been meaning to do this for a while now) and docs build just fine. However i just noticed that custom mkdocs themes are no longer supported.. I will need to put some more work into this.
