### ISSUE TITLE
initialVersion setup issue

### ISSUE THREAD

**Issue by KishorGaneshrao** [allegro/axion-release-plugin#259]
Hi,

I'm trying to use initialVersion setup, but even after release it seems like i'm still stuck with snapshot version.

What am I missing here please:

- set up initial verison in build file
```
	scmVersion {
		tag {
			initialVersion = { c, p -> '1.0.0' }
		}
	}
```	

- check currentVersion, which correctly returns - 
```
        gradle cV
	Project version: 1.0.0-SNAPSHOT
```

- run release task:
```
        Creating tag: release-1.0.0
        Pushing all to remote: origin
```
	
- Now when I check currentVersion again, I still get snapshot:
```
        gradle cV
	Project version: 1.0.0-SNAPSHOT
```
- whereas the latest commit is now tagged with release-1.0.0
```
        git tag
        release-1.0.0
```

**Comment by KishorGaneshrao** [comment]
- And further to that, the very first attempt of running release actually throws exception as tag exists:
```
* What went wrong:
Execution failed for task ':release'.
> org.eclipse.jgit.api.errors.RefAlreadyExistsException: tag 'Tag={
object cef53f98bb3b1651678e8cab7126b5967b5995d9
type commit
tag release-1.0.0
tagger PersonIdent[Jenkins_user, host, timestamp]
}' already exists
```

**Comment by KishorGaneshrao** [comment]
I believe my problem was:
```
    // customizable suffix for Next version marker
    nextVersion {
        suffix = ''
        separator = '-'
    }
```

here is the full scmVersion config I have:
```
scmVersion {
    // Pre-release checks disabled
    checks {
        snapshotDependencies = false
        aheadOfRemote = false
    }

    // Sets initial version:
    tag {
        initialVersion = {config, position -> '1.0.0'}
    }

    // Updates readme.md with current version
    hooks {
        pre 'fileUpdate', [file: 'README.md', pattern: {v, c -> /version: $v/}, replacement: {v, c -> "version: $v"}]
        pre 'commit'
    }

    // customizable suffix for Next version marker
//    nextVersion {
//        suffix = ''
//        separator = '-'
//    }
}
```

**Comment by adamdubiel** [comment]
Yes, your versions were not matched, because version tags were mistaken for nextVersion tags. You can read more about next version in the [docs](https://axion-release-plugin.readthedocs.io/en/latest/configuration/next_version/). It has to have some distinctive suffix, `''` is not a best one :)
