### ISSUE TITLE
CurrentVersion issue: nextVersionTag and forceSnapshot yield nextVersionTag+1

### ISSUE THREAD

**Issue by trohr** [allegro/axion-release-plugin#263]
### Issue
When `-Prelease.forceSnapshot` is specified and last tag is `nextVersionTag`, than `currentVersion` is incorrect -> the version is incremented once more.

Given:
 tag 'release-1.2.0-alpha'
 -Prelease.forceSnapshot

When:
 gradle currentVersion
 
Then:
 BUG: currentVersion == '1.2.1-SNAPSHOT'
 IMHO SHOULD be: currentVersion == '1.2.0-SNAPSHOT'

### Current status of the issue
I have reproduced this issue in your tests (`VersionResolverTest.groovy`) and I will now make commit to my forked version of the axion-release-plugin.

I will you let you know when I find some solution.

Please let me know whether this is really a BUG and whether you see any possible things with the code I should be aware of.

**Comment by trohr** [comment]
Hi,

I have been able to fix the problem I have encountered, but I found another issue with the `forceSnapshot` option.

What I have fixed was simple enough, but making the second failing test work would IMHO entail making some design decision in the code of `VersionResolver.resolveVersion`, `VersionResolver.readVersions` and `VersionResolver.readVersionsByHighestVersion`. I am not comfortable to make these decisions for myself.

Please review the test cases and let me know your thoughts. (Also -- will you be able to fix the second test case?)

Thank you,
Tomas Rohrbacher



### Fixed
Problem when -Prelease.forceSnapshot is specified and last tag is nextVersionTag.

    def "should return previous version from last release tag and current from next version when on next version tag (and force snapshot)"() {
        given:
        repository.tag('release-1.1.0')
        repository.commit(['*'], 'some commit')
        repository.tag('release-2.0.0-alpha')
        def versionRulesForceSnapshot = versionProperties().forceSnapshot().build()

        when:
        VersionContext version = resolver.resolveVersion(versionRulesForceSnapshot, tagRules, nextVersionRules)

        then:
        version.previousVersion.toString() == '1.1.0'

        // The following assertion failed -- if forceSnapshots was specified, than 'nextReleaseVersion'
        // was incremented once again yielding the 2.0.1-SNAPSHOT version, which is NOT CORRECT.
        version.version.toString() == '2.0.0'
        version.snapshot
    }


### Has Error
    def "should prefer snapshot of nextVersion when both on current commit and forceSnapshot is enabled"() {
        given:
        repository.tag('release-1.0.0')
        repository.tag('release-1.1.0-alpha')
        VersionProperties versionRules = versionProperties().forceSnapshot().build()
        
        when:
        VersionContext version = resolver.resolveVersion(versionRules, tagRules, nextVersionRules)
        
        then:
        version.previousVersion.toString() == '1.0.0'
        // #263: also the nextVersion should be taken account when forceSnapshot is specified
        version.version.toString() == '1.1.0'
        version.snapshot
    }

**Comment by trohr** [comment]
Please excuse the amount of commits to be shown here. I have been cleaning up the commits and rewriting history in my branch.

**Comment by adamdubiel** [comment]
Thanks for putting the effort to fix this issue :) I don't mint the commits. I will take a look at it on Monday.

**Comment by adamdubiel** [comment]
The original issue is without a doubt a legitimate one. Version should not be incremented twice. Second issue you found.. I'm in two minds. See my comment in #264 and let us discuss it there.
