### ISSUE TITLE
CurrentVersion issue: nextVersionTag on same commit as release version and forceSnapshot yield release version

### ISSUE THREAD

**Issue by trohr** [allegro/axion-release-plugin#264]
### Issue
When `-Prelease.forceSnapshot` is specified and last tag is `nextVersionTag` on same commit as a release tag, than `currentVersion` is the already released version.

### Test Case
    def "should prefer snapshot of nextVersion when both on current commit and forceSnapshot is enabled"() {
        given:
        repository.tag('release-1.0.0')
        repository.tag('release-1.1.0-alpha')
        VersionProperties versionRules = versionProperties().forceSnapshot().build()
        
        when:
        VersionContext version = resolver.resolveVersion(versionRules, tagRules, nextVersionRules)
        
        then:
        version.previousVersion.toString() == '1.0.0'
        //  also the nextVersion should be taken account when forceSnapshot is specified
        //  BUT IS NOT -- IS 1.0.0-SNAPSHOT !!!
        version.version.toString() == '1.1.0'
        version.snapshot
    }

**Comment by adamdubiel** [comment]
This issue exists because of the logic described in `VersionSorter`:

```
// next version should be igored when tag is on head
// and there are other, normal tags on it
// because when on single commit on head - normal ones have precedence
```

And also specified in `VersionSorterTest`:

```
def "should prefer normal version to alpha version when on head and versions on single commit"() {
        when:
        def versionData = sorter.pickTaggedCommit(
            [new TagsOnCommit('a', ['release-1.0.0', 'release-2.0.0-alpha'], true)],
            false,
            ~/.*-alpha$/,
            factory
        )

        then:
        versionData.version.toString() == '1.0.0'
    }
```

This is because `VersionSorter` has no information about `forceSnapshot` flag. When there is no snapshot, implemented behavior is preferable, because release always should take precedence.

But with `forceSnapshot`.. well, this is not so easy. `forceSnapshot` was designed to take the output of `currentVersion` and make a snapshot out of it. And it does so. The output of `cV` is `1.0.0`, not `2.0.0-SNAPSHOT`.

Now if we were to change this behavior, it would feel a bit inconsistent to me. I get `1.0.0` from `cV`, but when i add `forceSnaphsot` everything changes.

On the other hand it feels like we should use next version there, because this is an expected behavior. If there existed another commit after tagged one (not on head), it would work the way you want.

Can you maybe specify usage scenario for this issue?

**Comment by trohr** [comment]
After looking at it for an hour, I realized that _I made an error_ and mislead you in this case because I wrote that the 'released' version is taken into account and made into SNAPSHOT. This is not true.

Currently, evaluation of:
- tag `release-1.0.0`
- `./gradlew cV -Prelease.forceSnapshot`
yields `1.0.1-SNAPSHOT`, where incrementing is done by the configured incrementer for given branch.

This is OK.


This issue however should be about the fact, that the `nextVersionTag` (`alpha`) version is not taken into account when making snapshot on the same commit that has both the `nextVersionTag` as well as the `release` tag.

Example of ignored nextReleaseTag:
- tag `release-1.0.0`
- tag `release-1.5.0-alpha`
- `./gradlew cV -Prelease.forceSnapshot`
yields `1.0.1-SNAPSHOT`. This just means that `nextVersionTag` is not taken into account in this case.


### Situation
Imagine CI server with two pipelines:
- one makes only release builds (either reads existing tagged commits or performs the release using the axion-release-plugin)
- the other one makes only shapshot builds (triggered either manually, polled using cron expression or triggered via git hook)

Example commands:
- RELEASE_JOB: `./gradlew clean createRelease build pushRelease publish`
- SNAPSHOT_JOB: `./gradlew clean build publish`

#### Scenario A
incrementer = `incrementPatch`
1. RELEASE build -> tag version `1.0.0`
2. tag next version `1.5.0-alpha`
3. SNAPSHOT build -> currently not 1.5.0-SNAPSHOT, but 1.0.1-SNAPSHOT

This means that some `unplanned` lower version is going to be built and published to company repository.

#### Scenario B
incrementer = `incrementMinor`
1. RELEASE build -> tag version `1.0.0`
2. tag next version `1.0.1-alpha` // there was discovered a problem in 1.0.0 and we need it to be addressed
3. SNAPSHOT build -> currently result will not be `1.0.1-SNAPSHOT`, but `1.1.0-SNAPSHOT`

This means that a much higher than expected version will be built and published into a snapshot repo.

### Notes
All and all, I don't think this is a big issue, but I think it shows inconsistency in implementation of the next release marker.
As I look at it, the `alpha` version logic would best be treated as some forced `incrementer` strategy.
I would like at least to create pull request with tests that document current behaviour, but unfortunately I don't have time for it now.

**Comment by Theer108** [comment]
I'll look into it

**Comment by adamdubiel** [comment]
@trohr looks like @Theer108 fixed this issue :) Can you build and try out snapshot version from master?

**Comment by trohr** [comment]
> @trohr looks like @Theer108 fixed this issue :) Can you build and try out snapshot version from master?

I will look into it probably sometimes during next week.

Also I would like to add that you are awesome!
