### ISSUE TITLE
How to add branch suffix for snapshots only

### ISSUE THREAD

**Issue by mpapirkovskyy** [allegro/axion-release-plugin#269]
I really like behavior of `versionCreator 'versionWithBranch'`, except one thing.
I want it to work for snapshots only.
E.g. on branch `hotfix` I want `currentVersion` return:
- `1.0.1` when on release tag, current behavior is `1.0.1-hotfix`
- `1.0.2-hotfix-SNAPSHOT` otherwise

Tags are unique in git anyway, so why not.
Any advise?

**Comment by adamdubiel** [comment]
There is no way to achieve this currently. In `BranchCreator` you have access to `ScmPosition` object, but it does not contain information if you are on tag, so you could modify created version based on being on release.

**Comment by cliffred** [comment]
We have the exact same need. Would it be possible to overload the versionCreator closure so it can also take just the versionContext? VersionContext contains all the information you need to achieve this. You would only need to pass the right parameters based on the number of parameters of the versionCreator closure here:

https://github.com/allegro/axion-release-plugin/blob/03f951c313325fb5a93d0e4e809b6803710c8a42/src/main/java/pl/allegro/tech/build/axion/release/domain/VersionService.java#L24-L26
