### ISSUE TITLE
Replacement for ScmPosition.onTag?

### ISSUE THREAD

**Issue by jawitthuhn** [allegro/axion-release-plugin#272]
We're running an older version (1.4.1) and are looking at how we might upgrade to the latest. One issue that we are running into is that 1.4.1 contained a field in the ScmPosition class called "onTag", and that field appears to have disappeared.

We are using configuration like this:
```
scmVersion {
  // version incrementing -- default to minor, and increment patch on release branches
  versionIncrementer 'incrementMinor'
  branchVersionIncrementer = [
    'release/.*' : 'incrementPatch'
  ]

  // version decoration to add -RELEASE to release artifacts
  versionCreator { version, position -> position.onTag ? "${version}-RELEASE" : version }
}

project.version = scmVersion.version
```

However, starting with 1.5.0, the "onTag" boolean field no longer exists as part of ScmPosition. Is there another way that we could achieve this same effect, adding "-RELEASE" to the end of our version numbers in our releases?

I've read through the documentation, but I'm not sure I'm seeing a simple way to do this. Is there still a supported way to achieve the same effect?

**Comment by adamdubiel** [comment]
Let me try to investigate why it disappeared.

**Comment by jawitthuhn** [comment]
Were you able to find out why? I was able to locate the commit, but it was some time ago and I'm less familiar with the discussion around it.

Newer versions have a different bug fix that we will need to continue using the plug-in, but we are trying to determine if there is a safe way that we can upgrade this.

**Comment by jawitthuhn** [comment]
We made the decision that we could drop this custom "-RELEASE" suffix to allow us to upgrade, so I am closing this issue.
