### ISSUE TITLE
forceSnapshot results in wrong version number for initial version

### ISSUE THREAD

**Issue by cliffred** [allegro/axion-release-plugin#273]
Given a project that has never been released yet (no release tags), using the Axion defaults, the following happens:

```
> gradlew currentVersion
Project version: 0.1.0-SNAPSHOT
```

```
> gradlew currentVersion -Prelease.forceSnapshot
Project version: 0.1.1-SNAPSHOT
```

After the first release everything is fine.

**Comment by adamdubiel** [comment]
Force snapshot strikes again :) So many corner cases. I will take a look.
