### ISSUE TITLE
Cannot run simple shell script on Windows

### ISSUE THREAD

**Issue by RezPhantom** [allegro/axion-release-plugin#275]
I ran into this problem when running shell commands in my Jenkins on windows. I thought it might just be me writing bad code, so then I tried testing a simple shell command in a new job. Either I forgot to add something to run shell commands in Jenkins or we have a problem. I also tried using cygwin and turning on the windows feature : Windows Subsystem for Linux

[error.txt](https://github.com/allegro/axion-release-plugin/files/2624119/error.txt)

[pipeline.txt](https://github.com/allegro/axion-release-plugin/files/2624120/pipeline.txt)

![image](https://user-images.githubusercontent.com/33414140/49148096-19572280-f30f-11e8-8950-049297679932.png)

**Comment by adamdubiel** [comment]
I think you created this issue in wrong project, this is not Jenkins :) Closing.
