### ISSUE TITLE
Possible to Do Non-Semantic Version?

### ISSUE THREAD

**Issue by EarthCitizen** [allegro/axion-release-plugin#278]
I have a project that cannot use semantic versioning. I am a strong proponent of semantic versioning, but this particular project has some special circumstances for which semantic versioning is simply not a good fit.

Is it possible to configure this plugin in a way that will allow me to use custom versioning format?

**Comment by adamdubiel** [comment]
I'm sorry, but internally version are parsed and handled using SemVer library, so it is not possible to parse anything that can't be described using some kind of SemVer magic. You might play around with custom decorators, to create version in format that you need out of SemVer version maybe? Or if you need non-semver tags, you can create custom serializers and deserializers?
