### ISSUE TITLE
readVersion on HookContext casts DecoratedVersion to String

### ISSUE THREAD

**Issue by ziscloud** [allegro/axion-release-plugin#283]
@adamdubiel In the document, users should get the same output as the currentVersion task, but actually it is not. there is another issue #207 talks about this issue, but it has been closed.

<img width="871" alt="image" src="https://user-images.githubusercontent.com/4755266/53808648-cafc9400-3f8d-11e9-9d41-ee148fa11be6.png">

In my scenario, I need the `currentVersion` output to update my gradle.properties.

please fix this bug.

**Comment by adamdubiel** [comment]
Hi! I closed the other issue since there was no response. I should rething the problem, but wanted to let you know that i noteiced the issue :)
