### ISSUE TITLE
Question about latest release (latest tag)

### ISSUE THREAD

**Issue by stewartbryson** [allegro/axion-release-plugin#284]
I have a simple requirement, and already use this plugin for releasing, so was curious if this plugin could handle it.

For smoke testing purposes I have with a Gradle project, I need to easily pull the latest release version number so I can run some integration tests and compare with the last release. I am guessing there is a method in here somewhere that I can use... but I haven't found it yet. I will keep looking, but if you know the answer, could you provide it?

Thank you.

**Comment by adamdubiel** [comment]
Hi :) I don't think i understand the question, what do you mean by "easiily pill the latest release version"? What is the "last release"? Is all happening inside Gradle script and you want to access some methods from `scmVersion`?

**Comment by stewartbryson** [comment]
> Hi :) I don't think i understand the question, what do you mean by "easiily pill the latest release version"? What is the "last release"? Is all happening inside Gradle script and you want to access some methods from `scmVersion`?

Sorry... I just want to get a String containing the most recent tag. Similar to `git describe` but without all commit distance extras.

**Comment by adamdubiel** [comment]
Currently there is no API that would get you exactly the tag, but `scmVersion.getScmPosition` returns [VersionScmPosition](https://github.com/allegro/axion-release-plugin/blob/master/src/main/groovy/pl/allegro/tech/build/axion/release/domain/VersionScmPosition.groovy).
