### ISSUE TITLE
Use configuration avoidance API when creating tasks

### ISSUE THREAD

**Issue by zman0900** [allegro/axion-release-plugin#289]
Tasks are currently created eagerly with `project.tasks.create(...)`.  They could instead be created using the recommend "configuration avoidance" API with `project.tasks.register(...)`.

https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

**Comment by adamdubiel** [comment]
Hi, I am aware that this plugin does not use all the latest bells and whistles that came with Gradle 4 and 5 :) This is simply a matter of lack of time for me. Thanks for pointing to this mechanism, I will keep it in mind in the future.
