### ISSUE TITLE
markNextVersion doesn't work with incrementPrerelease

### ISSUE THREAD

**Issue by grzegorzwitkowski** [allegro/axion-release-plugin#290]
Hi! I have a simple project with axion set up:
```
scmVersion {
    branchVersionCreator = [
            'rc/.*' : 'simple'
    ]
    branchVersionIncrementer = [
        'rc/.*' : ['incrementPrerelease', [initialPreReleaseIfNotOnPrerelease: 'rc1']]
    ]
}
```

I have a `master` branch with `init` commit which is released as `release-0.1.0`. Then I created a new branch from master called `rc/feature`, added a new commit `feature 1` and run:
```
./gradlew markNextVersion -Prelease.incrementer=incrementMajor
```

I expected that running `./gradlew currentVersion` will produce `release-1.0.0-rc1-SNAPSHOT` but it gives `1.0.0-SNAPSHOT`.

**Comment by tzieleniewski** [comment]
@grzegorzwitkowski I have the same issue, have you managed to resolve it?
