### ISSUE TITLE
Get SNAPSHOT version from release tag

### ISSUE THREAD

**Issue by hatavan83** [allegro/axion-release-plugin#294]
Hi all,
I try to release a tag and then check out this tag by Drone CI to build/deploy the release tag, but the current version is return wirh SNAPSHOT, could you please give me more idea 
```
+ git init
Initialized empty Git repository in /workspace/pipeline/.git/
+ git remote add origin https://github.com/xxx/pipeline.git
+ git fetch --no-tags origin +refs/tags/v0.0.1:
From  https://github.com/xxx/pipeline.git
 * tag               v0.0.1     -> FETCH_HEAD
+ git checkout -qf FETCH_HEAD

./gradlew cV
> Task :currentVersion
Project version: 0.0.1-SNAPSHOT
```

**Comment by agusmba** [comment]
I'm answering from memory (it's been ages since I used the plugin daily) but I seem to recall that it's due to not being on a branch.
It should be easy to test by creating an ad-hoc branch on that commit/tag and checking that out before using `gradlew cV`

(sorry if that's not the cause)

**Comment by hatavan83** [comment]
I just add 1 more step as `git fetch --all` to resolve version in tag
I have another issue with `initialVersion=0.0.1` 
```
scmVersion {
    useHighestVersion = true
    tag {
        initialVersion = {config, position -> '0.0.1'}
        prefix = 'v'
        versionSeparator = ''
    }
    versionIncrementer 'incrementPatch'
    nextVersion {
        suffix = 'SNAPSHOT'
    }
}
```
When I tag release `v0.0.1` on `production` branch success on CI
I checkout master branch and do some commit, but the version is always `0.0.1-SNAPSHOT`
```
> git tag
v0.0.1
> ./gradlew cV

> Task :currentVersion

Project version: 0.0.1-SNAPSHOT
```

**Comment by agusmba** [comment]
> When I tag release v0.0.1 on production branch success on CI I checkout master branch and do some commit

If you tag on master and then commit something else, the `-SNAPSHOT` would be normal.

**Comment by hatavan83** [comment]
@agusmba
the SNAPSHOT should be +1, but it is the same release tag, so that I think it is not valid :(

**Comment by hatavan83** [comment]
@adamdubiel @agusmba 
When I release on CI by command `gradle release -Prelease.disableChecks -Prelease.pushTagsOnly` with `production` branch,  the current version will not correct on `master` branch as above. I think it is a bug? Do you have any workaround for this case?

**Comment by adamdubiel** [comment]
@hatavan83 from what I understand the situation looks like:

* tag `0.1.0` is created on `production` branch 
* you checkout `master` branch and still get initial version (`0.0.1`)

The thing is that axion-release looks for tags in accordance to Git history. `0.1.0` tag exists in history only on `production` branch and probably not on `master` ([also see docs](https://axion-release-plugin.readthedocs.io/en/latest/configuration/version/#first-tag-encountered)). If you want other branches to be aware of tags, you need to merge them.
