### ISSUE TITLE
Current version not detecting a release

### ISSUE THREAD

**Issue by jpt1971** [allegro/axion-release-plugin#295]
When trying to use axion-release in very basic manner we are not seeing the version number being incremented correctly. The tag is created and saved to git without issue, but the call to currentVersion refuses to budge from 0.1.0-SNAPSHOT when run in Jenkins. Our config in Java for this is:

```
group = theGroup

scmVersion {
    tag {
        prefix = theName
    }
}

project.version = scmVersion.version
```

Our Jenkins job is issuing these commands:

```
git tag
./gradlew currentVersion
./gradlew release -Prelease.disableChecks -Prelease.pushTagsOnly
git tag
euesd-gpp-api-client-0.1.0
```

Sample run:

```
git tag

./gradlew currentVersion
Project version: 0.1.0-SNAPSHOT

./gradlew release -Prelease.disableChecks -Prelease.pushTagsOnly
> Task :verifyRelease
Skipping uncommitted changes check
Skipping ahead of remote check
Skipping snapshot dependencies check

> Task :release
Creating tag: euesd-gpp-api-client-0.1.0
Pushing all to remote: origin

./gradlew currentVersion
Project version: 0.1.0-SNAPSHOT

git tag
euesd-gpp-api-client-0.1.0
```

Not sure if it is due to being on Jenkins, or we are just missing something but just seems like a possible issue, any help would be appreciated.

**Comment by agusmba** [comment]
it seems there are no tags initially. Are you doing a proper clone in jenkins? (shallow clones might not work as expected with axion-release-plugin)

**Comment by jpt1971** [comment]
hi, the jenkins job is not setup to do a shallow clone, i have the 'fetch tags' advanced option enabled at present. The git tag commands i have in the flow shows that tags are present at the start of the process (the original post i made was from a clean start', below is the result of a second run of the Jenkins job.

The second currentVersion should be 0.1.0 shouldn't it? The tags are present locally and in the GIT repo in BitBucket

```
currentVersion
> Task :currentVersion
Project version: 0.1.0-SNAPSHOT

git tag
euesd-gpp-api-client-0.1.0

./gradlew release -Prelease.disableChecks -Prelease.pushTagsOnly --warning-mode all

> Task :verifyRelease
Skipping uncommitted changes check
Skipping ahead of remote check
Skipping snapshot dependencies check
> Task :release
Working on released version 0.1.0, nothing to release
Pushing all to remote: origin
BUILD SUCCESSFUL in 5s
2 actionable tasks: 2 executed
currentVersion
> Task :currentVersion

Project version: 0.1.0-SNAPSHOT

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
git tag
euesd-gpp-api-client-0.1.0
```

**Comment by agusmba** [comment]
I assume "theName" in your config is actually "euesd-gpp-api-client", isn't it?

**Comment by jpt1971** [comment]
yes thats correct, its a constant set in the gradle.properties file

**Comment by adamdubiel** [comment]
Just to clarify - when running on local machine, everything works as expected? Or you observe the same issues?

Current version right after release should display `0.1.0`, and I see `-SNAPSHOT` there.

**Comment by jpt1971** [comment]
i could not get release to work at all locally (windows 10), due to issues with 'org.eclipse.jgit.api.errors.TransportException:' which on jenkins we don't get as we have a ssh host running so i did not pursue hte local issue much. But if i pull the latest and run currentVersion i get:

```
> git pull
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.
From https://xyz/scm/myre/euesd-gpp-api-client
 * [new tag]         euesd-gpp-api-client-0.1.0 -> euesd-gpp-api-client-0.1.0
 * [new tag]         euesd-gpp-api-client-0.1.1 -> euesd-gpp-api-client-0.1.1
 * [new tag]         euesd-gpp-api-client-0.1.2 -> euesd-gpp-api-client-0.1.2
Already up to date.
> ./gradlew currentVersion

> Task :currentVersion

Project version: 0.1.0-SNAPSHOT

BUILD SUCCESSFUL in 11s
1 actionable task: 1 executed
> git tag
euesd-gpp-api-client-0.1.0
euesd-gpp-api-client-0.1.1
euesd-gpp-api-client-0.1.2
> ./gradlew currentVersion

> Task :currentVersion

Project version: 0.1.0-SNAPSHOT

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
>
```

i will see if a colleague is able to run release locally just to see.

**Comment by adamdubiel** [comment]
I don't need the release job to run :) Just tags and current version. From what I see, tags are not detected on localhost as well. This simplifies things a lot, as debugging on localhost is way easier :)

Just to start investigating, can you hardcode the prefix in your `build.gradle`?

Expected outcome on localhost is:

```
./gradlew cV
> Project version: 0.1.2{-SNAPSHOT if more commits are there}
```

**Comment by jpt1971** [comment]
sure thing, i swapped my build.gradle to contain:

```
scmVersion {
    tag {
        prefix = 'euesd-gpp-api-client'
    }
}
```

and the result is the same:

```
> git status
On branch feature/EUPUX-1213
Your branch is up to date with 'origin/feature/EUPUX-1213'.

nothing to commit, working tree clean


> ./gradlew cV

> Task :currentVersion

Project version: 0.1.0-SNAPSHOT

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
```

**Comment by jpt1971** [comment]
oh hey!

on a whim i moved the scmVersion block in the build.gradle file to the top (well just after the plugin section) instead of being near the bottom and now it all seems to work.
```

currentVersion
> Task :currentVersion

Project version: 0.1.3-SNAPSHOT

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
git tag
euesd-gpp-api-client-0.1.0
euesd-gpp-api-client-0.1.1
euesd-gpp-api-client-0.1.2
./gradlew release -Prelease.disableChecks -Prelease.pushTagsOnly --warning-mode all

> Task :verifyRelease
Skipping uncommitted changes check
Skipping ahead of remote check
Skipping snapshot dependencies check
> Task :release
Creating tag: euesd-gpp-api-client-0.1.3
Pushing all to remote: origin
BUILD SUCCESSFUL in 9s
2 actionable tasks: 2 executed
currentVersion
> Task :currentVersion

Project version: 0.1.3

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
git tag
euesd-gpp-api-client-0.1.0
euesd-gpp-api-client-0.1.1
euesd-gpp-api-client-0.1.2
euesd-gpp-api-client-0.1.3
```

**Comment by jpt1971** [comment]
not sure why this would have fixed it, maybe i am using some dependency which is conflicting, am happy to send you my full build.gradle file if its of interest. But atm it all seems happy, thanks so much for you help, is much appreciated.

**Comment by adamdubiel** [comment]
Great! I wanted to suggest it, but in your first comment you published:

```
scmVersion {
    tag {
        prefix = theName
    }
}

project.version = scmVersion.version
```

and so I though everything was in place. This is a known caveat, actually it is also described in the docs, but it does not mention the place in `build.gradle`, only the order of `scmVersion` and `project.version` :) If something accesses version before `scmVersion` block, defaults are used. I know that in newer versions of Gradle there are workarounds for this, but at the time of core plugin creation it had to be this way.

Anyway I'm grand that you found your solution :)
