### ISSUE TITLE
Support getting credentials from .netrc (or _netrc for Windows)

### ISSUE THREAD

**Issue by hugares** [allegro/axion-release-plugin#296]
For SSH, if no authorization option is specified, the plugin will try to fetch authorization options from SSH agent.

Could the plugin do the same for HTTP and try to fetch the authorization if no options are specified, i.e. from netrc file.

**Comment by adamdubiel** [comment]
Released as 1.10.2 :)

**Comment by hugares** [comment]
Thank you for the release!
