### ISSUE TITLE
Enable PDF or downloadable docs on RTD

### ISSUE THREAD

**Issue by bickerx2** [allegro/axion-release-plugin#300]
When travelling and working in areas with limited connectivity. It would be useful if there was a downloadable version of the docs from readthedocs.

**Comment by adamdubiel** [comment]
Unfortunately it's impossible, as `axion-release` docs are built using MkDocs and PDF outputs [are not supported](https://docs.readthedocs.io/en/stable/builds.html?highlight=pdf%20mkdocs#mkdocs).

**Comment by bickerx2** [comment]
Given the seccond comment in https://github.com/readthedocs/readthedocs.org/issues/1939

Would making a zip format be possible?
