### ISSUE TITLE
Custom prefix doesn't work

### ISSUE THREAD

**Issue by nikitsenka** [allegro/axion-release-plugin#303]
Hello
When using custom prefix scmVersion.version always return      
``` 
  tag {
            prefix = 'v'
            versionSeparator = ''
        }
```
```
git tag
v0.1.0
v0.1.1
```
```
 ./gradlew currentVersion -Prelease.useHighestVersion
Project version: 0.1.0-SNAPSHOT
```

**Comment by adamdubiel** [comment]
Can you post relevant portions of `build.gradle`? I wonder if `scmVersion.version` comes **after** `scmVersion` settings.

**Comment by nikitsenka** [comment]
Indeed this is the reason, once i place it above it works:

**Comment by adamdubiel** [comment]
Great :) It has to be configured this way, as all example as docs say.

**Comment by nikitsenka** [comment]
Thanks for quick reply
