### ISSUE TITLE
Remote tags not applied

### ISSUE THREAD

**Issue by nikitsenka** [allegro/axion-release-plugin#306]
Once i created new release and pushed it to remote i want to be able to reuse this tag in other branches as well.
```
➜ git tag
(nothing)
➜ ./gradlew cV
Project version: 0.1.0-SNAPSHOT
➜ git fetch --tags
 * [new tag]         v0.1.0     -> v0.1.0
 * [new tag]         v0.1.1     -> v0.1.1
 * [new tag]         v0.1.2     -> v0.1.2
 * [new tag]         v0.1.3     -> v0.1.3
 * [new tag]         v0.2.0     -> v0.2.0    -   this one was created from other branch
➜ ./gradlew cV    
Project version: 0.1.3
➜  git commit -m "some msg"
➜  ./gradlew createRelease
Creating tag: v0.1.4
```
I'm expecting new tag to be v0.2.1
How can i do it?

**Comment by adamdubiel** [comment]
Just merge contents of this branch with other branches. Since you want to have the same versions, you probably want to have the same code corresponding to those versions :)

**Comment by nikitsenka** [comment]
Gradle build config:

**Comment by adamdubiel** [comment]
axion-release following the structure of git, only knows about tags on given branch. so if you want git tags to be visible in other branches, you need to merge code from master to develop.

This IMO makes sense, because if you have tag for 1.1.0 on master and you would like to work on 1.1.1 on develop you probably want to have code from 1.1.0 on develop as well.

**Comment by nikitsenka** [comment]
I was trying to avoid merge from master to develop. 
As a workaround i'll always increase version from develop branch only and specify incrementer type as parameter

**Comment by adamdubiel** [comment]
Sure, whatever suits your flow :)

However from my point of view having package which has higher version (like 1.1.1) but has no features of previous versions (1.1.0) feels off.
