### ISSUE TITLE
Add parameter to pass current branch name in case repo is in detached state

### ISSUE THREAD

**Issue by maniekq** [allegro/axion-release-plugin#311]
This is feature request. I would like to know if adding this functionality makes sense or I am missing some existing possibilities.
Aim of this functionality would be to have additional parameter like `-Prelease.branchName` which would allow to override/set branch name read from Git (or not set in case repo is in detached state).  

I will try to describe my use case.
I am using Azure DevOps Pipelines to build my application. This CI system check out Git repo in detached head state. Because of that I am always running axion release with parameters `-Prelease.disableChecks` and  `-Prelease.pushTagsOnly` and it works great for simple cases.
However, when I want to add configuration per branch like the one below, it will not work, because branch is not known.
```
scmVersion {
	useHighestVersion = true
	branchVersionCreator = [
		'hotfix/.*': 'simple',
		'feature/.*': 'versionWithBranch'
	]
	versionIncrementer 'incrementMinor'
	branchVersionIncrementer = [
		'hotfix/.*': 'incrementPatch',
	]
}
```

If I could set branch name with `-Prelease.branchName=$(release.branch.name)`, I would be able to pass it from Azure DevOps and use full functionality of axion-release-plugin.

**Comment by maniekq** [comment]
@adamdubiel I would be interested in implementing this, but I would like to know if this makes sense from your perspective.

**Comment by adamdubiel** [comment]
Yes, please do, i know dealing with CI/CD can be a pain so anything that makes it easier is welcome. It would be ideal if you described your Azure Pipelines setup in [docs](https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/) as well :)
