### ISSUE TITLE
Base versionIncrementer type on commit message content?

### ISSUE THREAD

**Issue by richardlund** [allegro/axion-release-plugin#312]
Hi,

I'm looking to use this plugin for a project and am considering using the content of commit messages to drive logic to decide which `versionIncrementer` to use. e.g. Commit message contains `[BUG FIX]` then use 'incrementPatch' etc. However, I thought that perhaps this might have been considered already by other folk. Are you aware of anything that might meet these requirements? Thanks in advance.

**Comment by richardlund** [comment]
I'm guessing that you don't have any advice regarding my question?

**Comment by adamdubiel** [comment]
Hi, sorry i didn't reply earlier. We did consider similar behavior based on merged branches names. 

This is not currently possible, but I think adding this kind of logic would not be too hard by extending `ScmPosition` object to contain all commit messages. Commit traversal to the latest tag is done anyway, so this should not be a major change. Would you be willing to code this feature with any necessary help from me?

**Comment by gabrieljones** [comment]
I am looking to get just the HEAD commit message. I plan to put commit trailers in there to indicate if the version in a file should be treated as a tag of the HEAD commit for version calculation purposes.
