### ISSUE TITLE
Follow the dependencies between the submodules during the release

### ISSUE THREAD

**Issue by kboom** [allegro/axion-release-plugin#314]
Maintaining separate versions for sub-projects is very useful but then releasing must be done with care - projects with internal dependencies need to be released manually one after the other - dependencies first. It would be great to:

1. Make the release task understand this and release the dependencies (if necessary) before attempting to release a selected module
2. Make the release task release all modules of a gradle project according to a safe order.

Currently typing `-Prelease.useHighestVersion -Prelease.disableChecks -Prelease.pushTagsOnly` on the top level project won't work:

> The project uses snapshot versions - can't release. Snapshots found: ...

Doing that from a scope of a project with dependencies won't work either. Of course this happens only when we use `dependency(project(":submodule"))` notation rather than `dependency("my project:mymodule:x.y.z)` which would be difficult to maintain

**Comment by adamdubiel** [comment]
Looks like task dependencies problem, can't it be achieved using custom task in Gradle with specified dependencies?

**Comment by john-tipper** [comment]
I have addressed this issue in PR #326.
