### ISSUE TITLE
Warning about deprecated behaviour in Gradle 6.0.1

### ISSUE THREAD

**Issue by BrassyPanache** [allegro/axion-release-plugin#319]
I've just added the release plugin to my project.  Upon the initial run of the currentVersion task I receive this message:

```
./gradlew currentVersion

> Task :currentVersion
Property 'versionConfig' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.

Project version: 0.1.0-SNAPSHOT
```

**Comment by adamdubiel** [comment]
Hi, I would like to cover all this with: https://github.com/allegro/axion-release-plugin/issues/315

**Comment by bgalek** [comment]
@BrassyPanache I've added @Input and @Output annotations where they where ncesseary, this issue will be fixed in next release :)

**Comment by BrassyPanache** [comment]
Thanks, @bgalek! Much appreciated.
