### ISSUE TITLE
versionWithBranch not working

### ISSUE THREAD

**Issue by krzykrucz** [allegro/axion-release-plugin#320]
Hello, I use the default configuration of plugin and `versionWithBranch` strategy for versionCreator doesn't seem to add a branch name to the release name. I even tried it with a cl option `-Prelease.versionCreator=versionWithBranch`

My build.gradle.kt is as follows:
```kotlin
import org.gradle.jvm.tasks.Jar
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import pl.allegro.tech.build.axion.release.domain.PredefinedVersionCreator.versionCreatorFor

plugins {
    val kotlinVersion = "1.3.50"
    base
    maven
    kotlin("jvm") version kotlinVersion
    id("pl.allegro.tech.build.axion-release") version "1.10.3"
}

val gitVersion = scmVersion.version as String

scmVersion {
    useHighestVersion = true
    versionCreator = versionCreatorFor("versionWithBranch")
}

allprojects {
    group = "com.krzykrucz"
    version = gitVersion

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            url = uri("...")
        }
    }
}


subprojects {
    apply {
        plugin("kotlin")
        plugin("org.jetbrains.kotlin.jvm")
        plugin("maven-publish")
    }


    tasks {
        withType<JavaCompile> {
            sourceCompatibility = "11"
            targetCompatibility = "11"
        }

        withType<KotlinCompile> {
            kotlinOptions.jvmTarget = "11"
        }
    }

    configure<PublishingExtension> {

        val sourcesJar by tasks.creating(Jar::class) {
            classifier = "sources"
            from(sourceSets.main.get().allSource)
        }

        publications {
            create<MavenPublication>("complete") {
                from(components["java"])
                version = gitVersion
                artifact(sourcesJar)
            }
        }
        repositories {
            maven {
                url = uri("...")
            }
        }
    }
}
```

Am I doing anything incorrectly?

**Comment by adamdubiel** [comment]
What do you mean by `release version`? Can you post the command along with expected and actual result?

**Comment by krzykrucz** [comment]
Sure. First I do from a test->origin/test branch: 
```
./gradlew release -Prelease.versionCreator=versionWithBranch -Prelease.local
``` 
and then 
```
./gradlew currentVersion
```
, which outputs
```
> Task :currentVersion

Project version: 1.1.1-SNAPSHOT
```
According to docs, the version should be sth like `1.1.1-test-SNAPSHOT` imo.

Btw, this is a multimodule Kotlin project, where all modules are versioned together.

**Comment by adamdubiel** [comment]
Ah, i see the problem.

```
val gitVersion = scmVersion.version as String

scmVersion {
    useHighestVersion = true
    versionCreator = versionCreatorFor("versionWithBranch")
}

```

You configure the plugin after it is used. Just change the order of those two lines:

```
scmVersion {
    useHighestVersion = true
    versionCreator = versionCreatorFor("versionWithBranch")
}

val gitVersion = scmVersion.version as String
```

And it should be fine. Once I move to lazy properties, this kind of problems shouldn't occur. TIll then, there is a big warning sign in docs ;)

> Order of definition does matter! First, you need to apply the plugin, then configure it using scmVersion extension and only then current version can be set for whole project via scmVersion.version.

**Comment by krzykrucz** [comment]
Thanks! I must've missed that in the docs. It works now, I'm closing the issue.

**Comment by kboom** [comment]
> Ah, i see the problem.
> 
> ```
> val gitVersion = scmVersion.version as String
> 
> scmVersion {
>     useHighestVersion = true
>     versionCreator = versionCreatorFor("versionWithBranch")
> }
> ```
> 
> You configure the plugin after it is used. Just change the order of those two lines:
> 
> ```
> scmVersion {
>     useHighestVersion = true
>     versionCreator = versionCreatorFor("versionWithBranch")
> }
> 
> val gitVersion = scmVersion.version as String
> ```
> 
> And it should be fine. Once I move to lazy properties, this kind of problems shouldn't occur. TIll then, there is a big warning sign in docs ;)
> 
> > Order of definition does matter! First, you need to apply the plugin, then configure it using scmVersion extension and only then current version can be set for whole project via scmVersion.version.

Perhaps a clear example like the one above would help? Red one to the left and green one to the right? Not sure how we missed that but we spent on it several hours :-)
