### ISSUE TITLE
1.12.1 missing in the public maven repository

### ISSUE THREAD

**Issue by Farix1337** [allegro/axion-release-plugin#352]
I want to use the newest version 1.12.1 because 1.12.0 ist currently not usable for our projects because of lightweight tags which cause NullPointerExceptions.
When is planned to publish the newest version 1.12.1 to global maven repository?

**Comment by bric3** [comment]
Even on gradle plugin repository : https://plugins.gradle.org/m2/pl/allegro/tech/build/axion-release/pl.allegro.tech.build.axion-release.gradle.plugin/maven-metadata.xml, at this date (20200530171456) the latest is 1.12.0.

**Comment by adamdubiel** [comment]
I just published 1.12.1.

**Comment by bric3** [comment]
@adamdubiel Thanks !
