### ISSUE TITLE
Update documentation to latest version 1.9.3 -> 1.12.0

### ISSUE THREAD

**Issue by DaveBender** [allegro/axion-release-plugin#354]
The documentation, referenced in the README.md at [readthedocs.io](https://axion-release-plugin.readthedocs.io/en/latest/), appears to be out of date.  It shows documentation for version 1.9.3 but the latest version is [1.12.0](https://github.com/allegro/axion-release-plugin/releases/tag/axion-release-1.12.0)

Some examples in the documentation appear to refer to classes that are no longer in the code.

**Comment by bgalek** [comment]
@DaveBender how do you feel about contribution? :)

**Comment by bgalek** [comment]
thx, fixed ;)
