### ISSUE TITLE
Configuring custom initial version 

### ISSUE THREAD

**Issue by anurag-srivastava-by** [allegro/axion-release-plugin#362]
Is there any limitation on version format? I see 2020.1.0.0 as the initial version is not working while 2020.1.0 is working.

**Comment by adamdubiel** [comment]
Yes, only SemVer is supported: https://semver.org

**Comment by anurag-srivastava-by** [comment]
Thanks for your quick reply. I got it working with below config.

 tag { 
        prefix = 'release-2020' 
        versionSeparator = '.'
		initialVersion = { tag, position -> "1.0.0" }
    }
