### ISSUE TITLE
Lazy initialization of repository credentials

### ISSUE THREAD

**Issue by adamdubiel** [allegro/axion-release-plugin#37]
As a user i want to be able to specify `customKeyFile` and `customKeyPassword` programaticaly just before `release` task is run, not in command line options.

**Comment by philbeiler** [comment]
Unfortunately, I can't give you the full stacktrace without jumping thru a ton of hoops -- working on an air-gapped network.. but... I will try to summarize the stack trace...

The exception is pretty straight forward -- it basically seems like those properties are not sent to jgit

jgit.api.errors.TransportExcption:  ssh://xxxxxxxxxx.git  : USERAUTH fail
TaskExceptionException: Execution failed for task ':release'
Unchecked Exception   jgit.api.errors.TransportException

Ultimately, at:
jgit.api.PushCommand.call  160 
jgit.transport.JschConfigSessionFactory.getSession    142

Let me know if I can help any more. Thanks for being so responsive!

**Comment by adamdubiel** [comment]
I know exactly where the problem lies, no need for stacktraces :) I will try to spend some time on this through the weekend, will post updates.

**Comment by adamdubiel** [comment]
I spent some time refactoring code to achieve this (not yet ready), but there is one important thing to note. First interaction with repository takes place on `project.version=scmVersion.version`, as axion needs to establish current version for whole buildscript to use.

Adding ability to change key file and its credentials in runtime will lead to situation in which reading might use different credentials than pushing. This will occur only when `attachRemote` option is used. If repository is open for reading without credentials, it's fine. In other case, you need to specify proper credentials (i.e. run bash script for it) before version assignment.

This is not a blocker of course, it just needs to be noted to fully understand how adding this option will affect axion-release flow.

**Comment by philbeiler** [comment]
Not to be an annoyance... have you made any progress on this issue? Thanks.

**Comment by adamdubiel** [comment]
Actually i think i have it done already, now it needs some testing, which i plan on doing today. Just a little bit more patience :)

**Comment by adamdubiel** [comment]
Tested, released in 1.0.1, see updated README for details :)

**Comment by philbeiler** [comment]
Thanks. I tested and it worked fine, now moving on to the next problem -- I will get a automated release yet!!  **Thanks so much for your help!**

**Comment by philbeiler** [comment]
Not exactly sure how to reopen this... but I will put the relevant stuff here.... and maybe you can reopen. Not a lot happening in the build script...  Using your plugin, in combination with the credentials plugin -- I will hard-code the password to remove that variable from the problem -- but I have printed out the value in the script - so I'm 99% sure that part is working!

I have hacked the script to it bare-essentials...  I just in-lined the two values 'customKey' properties...

1. apply the axion-release plugin (I can not use the "new" plugin style -- I'm still using the buildscript block to load/find your plugin)  **Could this be an issue / difference?**

Next I have the scmVersion block

Then I hard code these values
 -- release.ext.customKeyFile = "$$System.env.HOME" + "/.ssh/id_rsa"
 -- release.ext.customKeyPassword = 'password"

Gradle release -P (attach remotes) -P (disable Checks)  release

Still failing with with authentication issues... on the push..

It is basically like those properties are not really being picked up....  if I specify them on the command line - it works perfectly..

Can you give this one more look?  If I need to, I can try to reproduce it, on an internet connected machine.  

Thanks. Phil

**Comment by adamdubiel** [comment]
Ah, now everything is clear. I probably should have posted example of usage here after solving problem.
What you should do in your script/task is modify `scmVersion` extension, not project flags, i.e.:

```
scmVersion.repository.customKey = // either content of key in String or File to read key from
scmVersion.repository.customKeyPassword = "my password"
```

Project flags are read only when applying plugin, but variables from `scmVersion` are lazily read before each authentication attempt.

**Comment by philbeiler** [comment]
DOH!!!  Thanks.. I will try this first thing tomorrow!

**Comment by adamdubiel** [comment]
Any luck? :)

**Comment by philbeiler** [comment]
Sorry for the delay. I got so busy making all of my CI jobs work after I validated it, I forgot to update you. It now works exactly like I needed it to, nice and clean... Thanks for your help.

**Comment by adamdubiel** [comment]
Great news, closing this once and for all :) I will create wiki pages for each CI we got covered (Jenkins + Bamboo).
