### ISSUE TITLE
allow changing the default branch name

### ISSUE THREAD

**Issue by gabrieljones** [allegro/axion-release-plugin#373]
I see the branch name `master` hard coded in some places. Is it possible to make this configurable so I can change what axion considers to be the "default" branch?

Reference:
https://github.com/allegro/axion-release-plugin/search?q=master+-Test

**Comment by bgalek** [comment]
Hi! @gabrieljones that's a good point! Maybe you would like to contribute? :)

**Comment by bgalek** [comment]
I see one significant place so far: https://github.com/allegro/axion-release-plugin/blob/03f951c313325fb5a93d0e4e809b6803710c8a42/src/main/groovy/pl/allegro/tech/build/axion/release/domain/PredefinedVersionCreator.groovy

**Comment by gabrieljones** [comment]
I just came up with this work around:

```build.gradle.kts
scmVersion {
  versionCreator("versionWithBranch")
  branchVersionCreator = mapOf(
    "main" to KotlinClosure2<String, pl.allegro.tech.build.axion.release.domain.scm.ScmPosition, String>({ versionFromTag, position ->
      "$versionFromTag"
    })
  )
}
```

this is build.gradle.kts syntax by the way

**Comment by gabrieljones** [comment]
Maybe it would be cleaner for me to create a new [custom version creator](https://github.com/allegro/axion-release-plugin/blob/03f951c313325fb5a93d0e4e809b6803710c8a42/docs/configuration/version.md#custom-version-creator)

I might look into that tomorrow

**Comment by bgalek** [comment]
I was thinking exactly about custom version creator :)

**Comment by gabrieljones** [comment]
how do I specify a custom version creator in Kotlin DSL?

**Comment by gabrieljones** [comment]
Here is what I came up with:
```build.gradle.kts
import pl.allegro.tech.build.axion.release.domain.scm.ScmPosition

//...

scmVersion {
  versionCreator = KotlinClosure2<String, ScmPosition, String>({ versionFromTag, position ->
    when (val branch = position.branch) {
      "master" -> versionFromTag
      "main" -> versionFromTag
      else -> "$versionFromTag-$branch"
    }
  })
}
```
