### ISSUE TITLE
org.eclipse.jgit.api.errors.TransportException not authorized

### ISSUE THREAD

**Issue by surjitsinghbhachu** [allegro/axion-release-plugin#374]
I would like to start using this plugin with a SpringBoot gradle project but I am getting an exception when I try to run the gradle `release` command with GitHub. I can pull/push to Github with no issues using the repo over https, it's only when I use the release command.

Gradle version: 6.8.2

Here is my Gradle config:

```
plugins {
	id 'org.springframework.boot' version '2.4.2'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
	id 'pl.allegro.tech.build.axion-release' version '1.12.1'
}
project.version = scmVersion.version
```
Here is the exception:

```
./gradlew release

> Task :verifyRelease
Looking for uncommitted changes.. 
Checking if branch is ahead of remote.. 
Checking for snapshot versions.. 

> Task :release FAILED
Creating tag: release-0.1.1
Pushing all to remote: origin
Exception occurred during push: org.eclipse.jgit.api.errors.TransportException: https://XXXXX: not authorized

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':release'.
> org.eclipse.jgit.api.errors.TransportException: https://XXXXX: not authorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 569ms
2 actionable tasks: 2 executed

```

What am I doing wrong?

**Comment by bgalek** [comment]
Hi, have you tried running the same task with `--debug`?  If we want to debug "not authorized" message, we would need more output. Also, are you willing to tryout current "master" build (you'll need to build the project locally)

**Comment by surjitsinghbhachu** [comment]
With --debug, here is the output:

```
2021-02-17T22:03:40.055+0000 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@664348098 pairs: {GET /XXXXX/info/refs?service=git-receive-pack HTTP/1.1: null}{Accept-Encoding: gzip}{Pragma: no-cache}{User-Agent: JGit/5.7.0.202003110725-r}{Accept: application/x-git-receive-pack-advertisement, */*}{Cache-Control: no-cache}{Host: github.com}{Connection: keep-alive}
2021-02-17T22:03:40.137+0000 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@664348098 pairs: {GET XXXXX/info/refs?service=git-receive-pack HTTP/1.1: null}{Accept-Encoding: gzip}{Pragma: no-cache}{User-Agent: JGit/5.7.0.202003110725-r}{Accept: application/x-git-receive-pack-advertisement, */*}{Cache-Control: no-cache}{Host: github.com}{Connection: keep-alive}
2021-02-17T22:03:40.534+0000 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@112b91728 pairs: {null: HTTP/1.1 401 Authorization Required}{Server: GitHub Babel 2.0}{Content-Type: text/plain}{Content-Security-Policy: default-src 'none'; sandbox}{Content-Length: 26}{www-authenticate: Basic realm="GitHub"}{X-Frame-Options: DENY}{X-GitHub-Request-Id: XXXXX}
2021-02-17T22:03:40.536+0000 [QUIET] [pl.allegro.tech.build.axion.release.domain.scm.ScmService] Exception occurred during push: org.eclipse.jgit.api.errors.TransportException: https://XXXXX.git: not authorized
```
Happy to try the master build. Can you point me to the instructions on how to build and reference in my gradle file?

**Comment by bgalek** [comment]
Thx for sharing debug output, It looks like we're not sending any credentials at all... strange...
Current master has some changes that may address the issue, so thank You for your involvement!

How to test this plugin locally:

1. clone the repo
2. run `./gradlew clean build`
3. run `./gradlew publishToMavenLocal`
4. test local build on your application like:

apply plugin: 'axion-release'
 ```
buildscript{
  repositories {
      mavenLocal()

      dependencies{
        classpath 'pl.allegro.tech.build:axion-release-plugin:axion-release-plugin-1.12.2-SNAPSHOT.jar'
      }
  }
}
```

I was typing from memory, so if I missed something let me now, I'll update the instruction and commit it into CONTRIBUTING.md

:)

**Comment by surjitsinghbhachu** [comment]
Thanks for the instructions. I was able to build the plugin locally but I got the same error. I may have overlooked something though, can I just double check my process:

1. Created my repo in GitHub
2. Cloned my repo using the https URL (not SSH). It did not ask me for my GIT username and password at this point.
3. Made some change locally, committed and pushed to origin (this is where I was asked for my git username and password)
4. Tried to run `./gradlew release` (and got the transport error)

I tried added the following  into the gradle file:

```
scmVersion {
    repository {
        scmVersion.repository.customUsername = "XXXXX"
        scmVersion.repository.customPassword = "XXXXX"
    }
}

```
and then the `-release` worked! 

My assumption was that it would use the existing git credentials. Do I have specify the credentials separately? If so, how can I do this without putting them in the build.gradle file?

**Comment by bgalek** [comment]
gr8! 
Yes, when git push command prompts You for password, that's the place where it's problematic for our plugin.
Also this plugin covers an use case, when you run a automated task (CI/github action) for relese - there won't be any way to prompt for password!
I recommend using environment variables or gradle parameters to pass username and password without hardcoding them in build.gradl file.

i.e.:
`./gradlew release -Pusername=myUsername -Ppassword=myPassword`
and then use those arguments in `scmVersion.repository.customUsername` and `scmVersion.repository.customPassword`. All Ci that I know of have some kind of secret management. 

Hope it helps ;)

**Comment by f4lco** [comment]
>i.e.:./gradlew release -Pusername=myUsername -Ppassword=myPassword
and then use those arguments in scmVersion.repository.customUsername and scmVersion.repository.customPassword

@bgalek a shortcut already exists in the plugin for this exact usecase. This is what I'm currently using:

```
./gradlew :mything:release -Prelease.customUsername="${USER}" -Prelease.customPassword="${PW}"
```

No need for modifications in `build.gradle`. In this case `${USER}` and `${PW}` are environment variables, but they can  easily be replaced by the actual credentials for firing one-off releases from the command line.

**Comment by bgalek** [comment]
@surjitsinghbhachu do You need any more assistance? :)

**Comment by surjitsinghbhachu** [comment]
No thanks for your support @bgalek. Issue can be closed.
