### ISSUE TITLE
Support common v1.2.3 prefix

### ISSUE THREAD

**Issue by mockitoguy** [allegro/axion-release-plugin#378]
It appears that `scmVersion.tag.prefix` only supports prefixes with hyphen. In Mockito project we're using a convention without hyphen: `v1.0.0`, `v1.1.0`. Is there a way to configure axion plugin to support tags with single letter `v` prefix? Thanks for this nice plugin!

**Comment by bgalek** [comment]
We are changing this behavior here https://github.com/allegro/axion-release-plugin/pull/377.
