### ISSUE TITLE
There is an incompatible JNA native library installed on this system.

### ISSUE THREAD

**Issue by Jolter** [allegro/axion-release-plugin#38]
Testing this plugin for the first time, so bare with me if I'm making some stupid newbie mistake.

I get this error when running the Release task for the first time. I have no preexisting tags in the repo, locally or remotely. The remote repo is in Gerrit. This is a multi-project build.

My dev machine is a Windows host, and I run gradlew from a "git bash" console (minGW).

I read the below like there is an incompatibility between the Java environment that runs my Gradle, and some library which is called by axion-release-plugin. How can I get around this?

If I manually deleted the tag and tried again, I got an even more cryptic error : 'Bad <init> method call from inside of a branch'.

    user@host /c/workspace/myproject (master)
    $ gradlew --version
    
    ------------------------------------------------------------
    Gradle 2.2-20141002220015+0000
    ------------------------------------------------------------
    
    Build time:   2014-10-02 22:00:15 UTC
    Build number: none
    Revision:     cfcfc3a224acceee6a4ae1f823af15ba56ceab13
    
    Groovy:       2.3.6
    Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
    JVM:          1.7.0_71 (Oracle Corporation 24.71-b01)
    OS:           Windows 7 6.1 amd64

    user@host /c/workspace/myproject (master)
    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    
    nothing to commit, working directory clean
    
    user@host /c/workspace/myproject (master)
    $ git tag
    
    user@host /c/workspace/myproject (master)
    $ gradlew release -Prelease.forceVersion=0.0.1
    :verifyRelease
    Looking for uncommited changes..
    Checking if branch is ahead of remote..
    :release
    Creating tag: release-0.0.1
    Pushing all to remote: origin
    :release FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':release'.
    >
    
      There is an incompatible JNA native library installed on this system.
      To resolve this issue you may do one of the following:
       - remove or uninstall the offending library
       - set the system property jna.nosys=true
       - set jna.boot.library.path to include the path to the version of the
         jnidispatch library included with the JNA jar file you are using
    
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug
    option to get more log output.
    
    BUILD FAILED
    
    Total time: 27.295 secs
    
    user@host /c/workspace/myproject (master)
    $ git tag -d release-0.0.1
    Deleted tag 'release-0.0.1' (was 7797695)
    
    user@host /c/workspace/myproject (master)
    $ gradlew release -Prelease.forceVersion=0.0.1 --stacktrace
    :verifyRelease
    Looking for uncommited changes..
    Checking if branch is ahead of remote..
    :release
    Creating tag: release-0.0.1
    Pushing all to remote: origin
    :release FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':release'.
    > Bad <init> method call from inside of a branch
    Exception Details:
      Location:
        org/ajoberstar/grgit/exception/GrgitException.<init>(Ljava/lang/String;)V @8
    7: invokespecial
      Reason:
        Error exists in the bytecode
      Bytecode:
        0000000: b800 164d 04bd 0029 5903 2b53 5910 ff12
        0000010: 04b8 002f 2a5f ab00 0000 00af 0000 0005
        0000020: 8794 83a0 0000 0032 aad3 b1ff 0000 0047
        0000030: c783 a456 0000 005a f0c1 c756 0000 0087
        0000040: 0000 9b75 0000 00a6 5f5a 5903 3212 31b8
        0000050: 0035 c000 315f 57b7 0037 a700 755f 5a59
        0000060: 0332 b800 3dc0 003f 5f57 b700 42a7 0062
        0000070: 5f5a 5903 32b8 003d c000 3f5f 5904 3212
        0000080: 31b8 0035 c000 315f 5905 32b8 0048 5f59
        0000090: 0632 b800 485f 57b7 0018 a700 355f 5a59
        00000a0: 0332 b800 3dc0 003f 5f59 0432 1231 b800
        00000b0: 35c0 0031 5f57 b700 4ba7 0016 5f5a 57b7
        00000c0: 004e a700 0dbb 0050 5912 52b7 0053 bf57
        00000d0: 2ab6 001c 4e2d 2a5f b500 1e2d 57b1
      Stackmap Table:
        full_frame(@72,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Unin
    itializedThis})
        full_frame(@93,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Unin
    itializedThis})
        full_frame(@112,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Uni
    nitializedThis})
        full_frame(@157,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Uni
    nitializedThis})
        full_frame(@188,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Uni
    nitializedThis})
        full_frame(@197,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Uni
    nitializedThis})
        full_frame(@207,{Object[#2],Object[#63],Object[#85]},{Object[#87]})
    
    
    * Try:
    Run with --info or --debug option to get more log output.
    
    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':release
    '.
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
    ecuteActions(ExecuteActionsTaskExecuter.java:69)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
    ecute(ExecuteActionsTaskExecuter.java:46)
            at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
    uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
            at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
    ute(SkipUpToDateTaskExecuter.java:64)
            at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
    e(ValidatingTaskExecuter.java:58)
            at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
    ter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
            at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
    .execute(SkipTaskWithNoActionsExecuter.java:52)
            at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
    e(SkipOnlyIfTaskExecuter.java:53)
            at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
    .execute(ExecuteAtMostOnceTaskExecuter.java:43)
            at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailur
    e(AbstractTask.java:305)
            at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
    orker.executeTask(AbstractTaskPlanExecutor.java:79)
            at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
    orker.processTask(AbstractTaskPlanExecutor.java:63)
            at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
    orker.run(AbstractTaskPlanExecutor.java:51)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
    tTaskPlanExecutor.java:23)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
    ltTaskGraphExecuter.java:88)
            at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
    ExecutionAction.java:29)
            at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
    r.java:62)
            at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExec
    uter.java:23)
            at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecu
    ter.java:68)
            at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
    ecutionAction.java:32)
            at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
    r.java:62)
            at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
    r.java:55)
            at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
    GradleLauncher.java:149)
            at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
    Launcher.java:106)
            at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
    cher.java:86)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
    troller.run(InProcessBuildActionExecuter.java:80)
            at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
    a:33)
            at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
    a:24)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
    ssBuildActionExecuter.java:36)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
    ssBuildActionExecuter.java:26)
            at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBu
    ild.java:46)
            at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
    CommandOnly.java:34)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(
    WatchForDisconnection.java:35)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute
    (ResetDeprecationLogger.java:24)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execut
    e(StartStopIfBuildAndStop.java:33)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.ReturnResult.execute(ReturnRes
    ult.java:34)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
    ardClientInput.java:71)
            at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
    ardClientInput.java:69)
            at org.gradle.util.Swapper.swap(Swapper.java:38)
            at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(For
    wardClientInput.java:69)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClien
    t.java:60)
            at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
    CommandOnly.java:34)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBu
    ild(EstablishBuildEnvironment.java:70)
            at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
    CommandOnly.java:34)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.
    run(StartBuildOrRespondWithBusy.java:45)
            at org.gradle.launcher.daemon.server.DaemonStateCoordinator.runCommand(D
    aemonStateCoordinator.java:243)
            at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy.do
    Build(StartBuildOrRespondWithBusy.java:49)
            at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
    CommandOnly.java:34)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.HandleCancel.execute(HandleCan
    cel.java:37)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.HandleStop.execute(HandleStop.
    java:30)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(Da
    emonHygieneAction.java:39)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.CatchAndForwardDaemonFailure.e
    xecute(CatchAndForwardDaemonFailure.java:32)
            at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed
    (DaemonCommandExecution.java:125)
            at org.gradle.launcher.daemon.server.exec.DefaultDaemonCommandExecuter.e
    xecuteCommand(DefaultDaemonCommandExecuter.java:52)
            at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$Co
    nnectionWorker.handleCommand(DefaultIncomingConnectionHandler.java:154)
            at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$Co
    nnectionWorker.receiveAndHandleCommand(DefaultIncomingConnectionHandler.java:128
    )
            at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$Co
    nnectionWorker.run(DefaultIncomingConnectionHandler.java:116)
            at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
    orImpl$1.run(DefaultExecutorFactory.java:64)
    Caused by: java.lang.VerifyError: Bad <init> method call from inside of a branch
    
    Exception Details:
      Location:
        org/ajoberstar/grgit/exception/GrgitException.<init>(Ljava/lang/String;)V @8
    7: invokespecial
      Reason:
        Error exists in the bytecode
      Bytecode:
        0000000: b800 164d 04bd 0029 5903 2b53 5910 ff12
        0000010: 04b8 002f 2a5f ab00 0000 00af 0000 0005
        0000020: 8794 83a0 0000 0032 aad3 b1ff 0000 0047
        0000030: c783 a456 0000 005a f0c1 c756 0000 0087
        0000040: 0000 9b75 0000 00a6 5f5a 5903 3212 31b8
        0000050: 0035 c000 315f 57b7 0037 a700 755f 5a59
        0000060: 0332 b800 3dc0 003f 5f57 b700 42a7 0062
        0000070: 5f5a 5903 32b8 003d c000 3f5f 5904 3212
        0000080: 31b8 0035 c000 315f 5905 32b8 0048 5f59
        0000090: 0632 b800 485f 57b7 0018 a700 355f 5a59
        00000a0: 0332 b800 3dc0 003f 5f59 0432 1231 b800
        00000b0: 35c0 0031 5f57 b700 4ba7 0016 5f5a 57b7
        00000c0: 004e a700 0dbb 0050 5912 52b7 0053 bf57
        00000d0: 2ab6 001c 4e2d 2a5f b500 1e2d 57b1
      Stackmap Table:
        full_frame(@72,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Unin
    itializedThis})
        full_frame(@93,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Unin
    itializedThis})
        full_frame(@112,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Uni
    nitializedThis})
        full_frame(@157,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Uni
    nitializedThis})
        full_frame(@188,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Uni
    nitializedThis})
        full_frame(@197,{UninitializedThis,Object[#63],Object[#85]},{Object[#87],Uni
    nitializedThis})
        full_frame(@207,{Object[#2],Object[#63],Object[#85]},{Object[#87]})
    
            at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy:107)
            at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy)
            at java_util_concurrent_Callable$call$0.call(Unknown Source)
            at java_util_concurrent_Callable$call$0.call(Unknown Source)
            at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
            at org.ajoberstar.grgit.Grgit.methodMissing(Grgit.groovy:193)
            at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.
    callPush(GitRepository.groovy:87)
            at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.
    push(GitRepository.groovy:83)
            at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.
    push(GitRepository.groovy:78)
            at pl.allegro.tech.build.axion.release.domain.scm.ScmRepository$push$5.c
    all(Unknown Source)
            at pl.allegro.tech.build.axion.release.domain.Releaser.release(Releaser.
    groovy:42)
            at pl.allegro.tech.build.axion.release.domain.Releaser$release.call(Unkn
    own Source)
            at pl.allegro.tech.build.axion.release.ReleaseTask.release(ReleaseTask.g
    roovy:33)
            at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
            at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
    actory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
            at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
    actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
            at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
    actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
    ctTask.java:579)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
    ctTask.java:562)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
    ecuteAction(ExecuteActionsTaskExecuter.java:80)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
    ecuteActions(ExecuteActionsTaskExecuter.java:61)
            ... 69 more
    
    
    BUILD FAILED
    
    Total time: 9.751 secs
    
    user@host /c/workspace/myproject (master)
    $

**Comment by adamdubiel** [comment]
It's going to be extremely hard to test suggestions i find, as nobody i know works on Windows environment, but i will try my best.

Can you try to experiment with [these](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/auth/AuthConfig.html) system flags? Specificly, disable `org.ajoberstar.grgit.auth.pageant.allow` or `org.ajoberstar.grgit.auth.sshagent.allow`. You could also take a look at (grgit)[https://github.com/ajoberstar/grgit] issues, it provides Git integration which fails here.

**Comment by adamdubiel** [comment]
Any luck with that?

**Comment by Jolter** [comment]
Sorry for the lack of update. I'm going to try this on a native *nix host any day now. Those system flags could be useful, too.

**Comment by Jolter** [comment]
Yes, you're right, it works fine on a Linux host using the same versions of the plugin + gradle, and the same build script.
Let's see if I have time to find a workaround on Windows - my other option is to do the version handling more manually but so far we don't release too often...

**Comment by adamdubiel** [comment]
I think playing around with flags, namely disabling pagent could do the trick on Windows.

**Comment by adamdubiel** [comment]
Can i close this issue? I don't know if i can be of any help or if fault lies at axion-release end.

**Comment by Jolter** [comment]
Sorry, still no luck even when enabling Pageant and ssh-agent. Same output as above when using 
  $ gradlew release -Porg.ajoberstar.grgit.auth.pageant.allow=false -Porg.ajoberstar.grgit.auth.sshagent.allow=false -Prelease.forceVersion=0.0.4

I think I'd be hard pressed to file a good ticket on this towards grgit, since I have no idea how this plugin is using the lib.

**Comment by adamdubiel** [comment]
Okay, and i have no idea how it works on Windows :D Let me create small demo-project to see if you get same behavior using vanilla grgit, okay? Then I will create ticket for grgit, mentioning you as reporter, since i won't be able to do the testing.

**Comment by Jolter** [comment]
Brilliant, that sound like a good plan.

**Comment by dbottstein** [comment]
FYI, I was able to get past this error by setting GRADLE_OPTS environment variable: `export GRADLE_OPTS='-Dorg.ajoberstar.grgit.auth.sshagent.allow=false -Dorg.ajoberstar.grgit.auth.pageant.allow=false'`. Apparently, setting JVM options via the gradle command line [isn't supported](https://gradle.org/docs/current/userguide/installation.html#N10162).

**Comment by adamdubiel** [comment]
So it was all the sshagent/pageant fault after all, like we thought at the beginning. @Jolter - can you test this solution?

**Comment by Jolter** [comment]
Hope I can give this a shot later today or tomorrow.

**Comment by adamdubiel** [comment]
I'm closing this issue as resolved now - feel free to reopen if you still have problems.
