### ISSUE TITLE
META: Maintenance of axion-release-plugin

### ISSUE THREAD

**Issue by realdadfish** [allegro/axion-release-plugin#381]
Dear current maintainer(s),

it seems to me that this software is somewhat unmaintained, still, many people use it today and even send in pull requests that sometimes keep open for weeks, or months, without any notice.

What is the current status of this project? Is it still actively maintained? Is there a wish to expand the active maintainers to more people, so tasks can be distributed amongst them?

Thanks,
A happy user (and contributor).

**Comment by jandersson-svt** [comment]
HI fellow axion user and PR submitter - I think a good idea to help the project would be to code review the PR's and fix a few bugs, to get rid of the backlogs. Of course, before doing that one would like to know that the effort is worth it, - . For example, if you or I would start doing code review or fixing bugs, would it help get them solved/merged quicker?  I *think* @bgalek is the most active maintainer now, at least he is responding to questions recently, correct me if If wrong @bgalek :) . NOTE: I'm not a maintainer or associated ,  but I'm a heavy user of it in our FOSS-projects at my org, and I also submitted a PR recently, and might help out with more if see that the project is active in the future.

**Comment by bgalek** [comment]
@realdadfish Hi! Thx for your side of the story. I'm doing my best to help with the project, I've been closing old issues, done some maintenance and some little fixes last few weeks ;) My goal is to close all old issues, but as You already know, there are a lot things to review and test. 

@jandersson-svt code review will be always welcome! :) BTW. I'm planning to check Your PR today ;)

**Comment by jandersson-svt** [comment]
If I can get the time I'll try to have a look at some of the older issues or prs and see If can contribute with something :)

**Comment by mockitoguy** [comment]
@bgalek, I tested the most recent HEAD with Mockito and it looks good (https://github.com/mockito/mockito/pull/2243)

Ship it ;-)

**Comment by bgalek** [comment]
@mockitoguy on it! Because this is a gradle plugin we don't have any snapshots releases :( I'll create new version today with next "fix" version, test it for the last time and then I'll create new minor release ;)

**Comment by bgalek** [comment]
@mockitoguy new version released :)

**Comment by mockitoguy** [comment]
@bgalek, great!

**Comment by jandersson-svt** [comment]
Congrats!! Will test today!

**Comment by jandersson-svt** [comment]
I browsed through the issues. Many of them are feature requests and such. "Axion would be great if it could.. ".
One suggestion is to plow through the issues list and label the issues, according to the default standard list https://docs.github.com/en/github/managing-your-work-on-github/managing-labels

As I understand it, an "triage" user for a project can do this, without having any other access to the repo itself.

I could offer to do this on a free day, but sadly, I cannot find any way to limit a users access to a

**Comment by bgalek** [comment]
@jandersson-svt sweet! I'll be happy to give you permissions to label issues ;)
