### ISSUE TITLE
[Regression] Axion 1.13.0 doesn't support previous prefixes

### ISSUE THREAD

**Issue by wyhasany** [allegro/axion-release-plugin#386]
After update I see following error
```sh
./gradlew currentVersion
* What went wrong:
Failed to parse version: ACME-2.4.339 that matched configured prefix: ACME. There can be no tags that match the prefix but contain non-SemVer string after the prefix. Detailed message: Unexpected character 'HYPHEN(-)' at position '0', expecting '[DIGIT]'
```
adding hyphen to the prefix fixes the problem (`build.gradle.kts`):
```
scmVersion {
    tag.prefix = "ACME-"
}
```
If it was intended it would be nice to document it inside release docs otherwise it should be fixed as it breaks backward compatibility.

**Comment by bgalek** [comment]
@wyhasany hi! This is indead regression, I'll fix it as soon as possible!

**Comment by bgalek** [comment]
I've updated release notes and I'll update docs/readme this week! @wyhasany thx for pointing out the problem!

**Comment by wyhasany** [comment]
That's awesome, I think I can close this ticket. Thanks for fast answer! :)
