### ISSUE TITLE
[Regression] Shadowing seems not to work as expected

### ISSUE THREAD

**Issue by wyhasany** [allegro/axion-release-plugin#389]
While releasing I've encountered following exception:
```
11:31:34  + ./gradlew bootBuildInfo generateGitProperties release
11:31:34  Watching the file system is not supported on this operating system.
11:31:35  > Task :bootBuildInfo FROM-CACHE
11:31:39  > Task :generateGitProperties
11:31:39  
11:31:39  > Task :verifyRelease
11:31:39  Looking for uncommitted changes.. 
11:31:39  Checking if branch is ahead of remote.. 
11:31:39  Checking for snapshot versions.. 
11:31:41  
11:31:41  > Task :release FAILED
11:31:41  Creating tag: ACME-API-2.4.342
11:31:41  Pushing all to remote: origin
11:31:41  hmacsha1: java.lang.ClassNotFoundException: shadow.com.jcraft.jsch.jce.HMACSHA1
11:31:41  Exception occurred during push: shadow.org.eclipse.jgit.api.errors.TransportException: ssh://git@acme.com/acme-api.git: java.lang.ClassNotFoundException: shadow.com.jcraft.jsch.jce.Random
```

**Comment by bgalek** [comment]
I'll look at it

**Comment by bgalek** [comment]
@wyhasany I think, this is an easy fix - it seems that org.eclipse.jgit is loading classes dynamicly, so i.e. Random.class got removed due tree-shaking - stay tuned for a fix release!

**Comment by bgalek** [comment]
@wyhasany can U share your build.gradle for me? I'm trying to reproduce the problem ;)

**Comment by wyhasany** [comment]
@bgalek pls stop your investigation. It seems that in my company there is some issue between Jenkins <-> Bitbucket which can cause this bug. I can confirm that when our devops resolve it 🤣

**Comment by wyhasany** [comment]
@bgalek It seems not to be related to some issues with my environment, after fixing issue by DevOps the exception with `ClassNotFoundException` still exists

**Comment by wyhasany** [comment]
I've spent some time trying to reproduce it with simple project but I failed. Here you can see example project (no clue why it happens on my environment)

[axion-example.zip](https://github.com/allegro/axion-release-plugin/files/6222156/axion-example.zip)

**Comment by bgalek** [comment]
@wyhasany try 1.13.1 tommorow (maven central sync) and tell me if it helps ;)

**Comment by wyhasany** [comment]
It works as expected ❤️  Thanks for your support @bgalek !

**Comment by Mati20041** [comment]
@bgalek 

Unfortunately it looks like the problem still occurs :( 
I'm using 1.13.1 version and also tried to clear the caches.

`id 'pl.allegro.tech.build.axion-release' version '1.13.1'`


```
> Task :release FAILED
Creating tag: release-0.1.20
Pushing all to remote: origin
hmacsha1: java.lang.ClassNotFoundException: shadow.com.jcraft.jsch.jce.HMACSHA1
Exception occurred during push: shadow.org.eclipse.jgit.api.errors.TransportException: git@gitlab.com:mybusinessproject.git: java.lang.ClassNotFoundException: shadow.com.jcraft.jsch.jce.Random
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':release'.
> shadow.org.eclipse.jgit.api.errors.TransportException: git@gitlab.com:mybusinessproject.git: java.lang.ClassNotFoundException: shadow.com.jcraft.jsch.jce.Random
```
Any idea where the root of this behavior might be? 🤔 

(I removed companys git urls)

**Comment by bgalek** [comment]
@Mati20041 hi! my only suspect is https://github.com/allegro/axion-release-plugin/blob/master/build.gradle#L120
I've just checked, removing minimizing restores missing class.
Be sure to update to next fix version1
