### ISSUE TITLE
Build break with message "There can be no tags that match the prefix but contain non-SemVer string after the prefix." after upgrade to 1.13.0

### ISSUE THREAD

**Issue by michaelruocco** [allegro/axion-release-plugin#394]
Hi, first off thanks for the very useful plugin, I use it in a number of my repos and it works perfectly.

Recently I have attempted to update from version 1.12.1 to 1.13.0 and I have found a good number of my builds have broken. The builds all use the ```'versionWithBranch'``` version creator with a tag prefix. And example config from one of the broken repos is:

```
scmVersion {
    versionCreator "versionWithBranch"
    tag {
        prefix = "idv-context"
    }
}
project.version = scmVersion.version
```

I have performed a number of releases on the project in the past, and have a number of existing tags.

```
michaelruocco@Michaels-MacBook-Pro-2 idv-context % git tag
idv-context-0.1.0
idv-context-0.1.1-alpha
idv-context-0.1.10
idv-context-0.1.11
idv-context-0.1.2
idv-context-0.1.2-alpha
idv-context-0.1.3
idv-context-0.1.4
idv-context-0.1.5
idv-context-0.1.6
idv-context-0.1.7
idv-context-0.1.8
idv-context-0.1.9
```

After upgrading from 1.12.1 to 1.13.0, when I try to run a build, for example ```./gradlew currentVersion``` (but it happens on pretty much any build) I get the following error:

```
michaelruocco@Michaels-MacBook-Pro-2 idv-context % ./gradlew currentVersion

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/michaelruocco/git/github/idv-context/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating root project 'idv-context'.
> Failed to parse version: idv-context-0.1.11 that matched configured prefix: idv-context. There can be no tags that match the prefix but contain non-SemVer string after the prefix. Detailed message: Unexpected character 'HYPHEN(-)' at position '0', expecting '[DIGIT]'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

From reading the error, it suggests that the existing tags are incorrect and should not be followed by a hyphen. To that end I was able to fix the issue by checking the prefix definition from above to be ```prefix = "idv-context"``` instead of ```prefix = "idv-context-"``` and now it appears to be working fine again.

If this is the intended solution then I am fine for this to be closed again, I just wanted to flag it up incase it was an unintentional change.

Thanks.

**Comment by bgalek** [comment]
hi @michaelruocco!
Thx for kind words!
Yes, this is intended solution as described in release notes: https://github.com/allegro/axion-release-plugin/releases/tag/axion-release-1.13.0

I didn't had time to fix changelog/docs yet, sorry!

**Comment by michaelruocco** [comment]
Ah okay, I should have checked the release notes before raising, in that case this can be closed. Thanks for confirming.
