### ISSUE TITLE
Doesn't work with OpenSSH version 8+

### ISSUE THREAD

**Issue by milesje** [allegro/axion-release-plugin#398]
We recently updated all of our servers and laptops to use OpenSSH 8.2p1 and now axion-release fails with a "Auth Fail" error. I spun up a snapshot of one of our Linux Servers that was running version 7.6p1 and it works fine on there.... Both machine are using the exact same RSA 2048 key so it must be the version of OpenSSH installed on the machine.

**Comment by milesje** [comment]
I'm using version 1.13.2!

**Comment by bgalek** [comment]
@milesje Are you willing to help with reproducing the issue on github action? 
Maybe we could test `axion-release-plugin` with latest openssh?
how about that? :)

**Comment by milesje** [comment]
@bgalek I will help in any way I can. I've never used github actions, but I will learn it if I need to.

**Comment by bgalek** [comment]
@milesje That's the spirit! 

Here are the docs:
https://docs.github.com/en/actions
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

You'll need something like
```
- name: Install xmllint
  run: sudo apt-get install openssh
```

You can fork this repo and make changes in .github folder :)
