### ISSUE TITLE
Invalid private key

### ISSUE THREAD

**Issue by peterfigure** [allegro/axion-release-plugin#401]
```
* What went wrong:
Execution failed for task ':release'.
> org.eclipse.jgit.api.errors.TransportException: git@github.xx/xx.git: invalid privatekey: [B@52771620
```

looks like the issue might be related to: https://bugs.eclipse.org/bugs/show_bug.cgi?id=520927 - I'm using ed25519 private keys. looks like it was resolved a while ago but have to use the MINA ssh dependency: https://wiki.eclipse.org/JGit/New_and_Noteworthy/5.2 (org.eclipse.jgit:org.eclipse.jgit.ssh.apache).

any chance of switching? elliptic curve keys are very much recommended over RSA these days...

**Comment by bgalek** [comment]
hi! @peterfigure sure thing!

**Comment by bgalek** [comment]
@peterfigure wanna try to make PR with this update? ;)

**Comment by peterfigure** [comment]
I'll try to find some time over the weekend but can't promise anything, also, I don't know Groovy 😳

**Comment by bgalek** [comment]
fingers crossed! :)

**Comment by jdomag** [comment]
@bgalek
 I'm affected by this as well. 
Any chance you can fix that?

**Comment by bgalek** [comment]
I'll check it this weekend!

**Comment by jdomag** [comment]
@bgalek 
Any progress on this one?

**Comment by bgalek** [comment]
sorry to keep you wait!
@peterfigure @jdomag as I understand https://github.com/allegro/axion-release-plugin/pull/414 this could resolve the issue? could you test it out with your ed25519 key?

**Comment by big-andy-coates** [comment]
Hey @bgalek, I'm encountering this "invalid private key" issue, probably due to my ed25519 key. I'm running plugin version 1.13.6, which includes #414, so looks like its not fixed yet.

**Comment by bgalek** [comment]
Hi, I'm aware :( I've started a complex fix for all ssh related problems, but I've didn't find any time to finish it up :( You can check progress here https://github.com/allegro/axion-release-plugin/pull/416

**Comment by big-andy-coates** [comment]
Great stuff.

And… great plug-in by the way!

**Comment by jamesdehart** [comment]
@bgalek I'm running into this issue. It seems to be an issue with the SSH key type. I use `ed25519`. Is there a way to use your build from #416  or are you still working on it?

**Comment by sssshong** [comment]
@jamesdehart i have same issue. Did you solve this problem?

**Comment by bgalek** [comment]
unfortunately not yet - if anyone wants to jump into https://github.com/allegro/axion-release-plugin/pull/416 feel free
I'm waiting for some vacation days to sit on this problem and I finally finish it!

**Comment by ramesh-vangala** [comment]
Any update on this?

**Comment by anekrasov-dr** [comment]
hello,
I'm running into this issue:
```
16:51:29  + ./gradlew markNextVersion -Prelease.incrementer=incrementMinor -Prelease.customKeyFile=****
16:51:30  
16:51:30  > Task :markNextVersion FAILED
16:51:30  Creating next version marker tag: client/-0.2.0-alpha
16:51:30  Pushing all to remote: origin
16:51:30  Exception occurred during push: org.eclipse.jgit.api.errors.TransportException: git@github.com:myrepo.git: invalid privatekey: [B@5d0fd7ec
16:51:30  
16:51:30  FAILURE: Build failed with an exception.
16:51:30  
16:51:30  * What went wrong:
16:51:30  Execution failed for task ':markNextVersion'.
16:51:30  > org.eclipse.jgit.api.errors.TransportException: git@github.com:myrepo.git: invalid privatekey: [B@5d0fd7ec
```
this happens on my jenkins node. I'm using `withCredentials([sshUserPrivateKey(credentialsId: 'credsId', keyFileVariable: 'SSH_FILE')])` after finding out that ssh-agent is not working.

**Comment by lukasz20p** [comment]
@bgalek is there any workaround for this. With changes on [github](https://github.blog/2021-09-01-improving-git-protocol-security-github/) using axion-release-plugin is impossible

**Comment by bgalek** [comment]
@onyxraven exactly, this PR will need more work then I anticipated, maybe you would like to contribute? This draft is valid, but there are so migrations needed.

**Comment by bgalek** [comment]
Should work now :)
