### ISSUE TITLE
ServiceUnavailableException when executing task release

### ISSUE THREAD

**Issue by dmutterSF** [allegro/axion-release-plugin#409]
When I try to release I get this error message:
`shadow.org.eclipse.jgit.api.errors.ServiceUnavailableException: Signing service is not available`

```groovy
scmVersion {
  repository {
    // custom ssh-key
    if (project.hasProperty('ssh_key')) {
      customKey = project.file(ssh_key) // ssh_key contains the absolute path to the private key
    }
  }
  tag {
    prefix = 'v'
    versionSeparator = '-'
  }
  checks {
    aheadOfRemote = true
    uncommittedChanges = true
    snapshotDependencies = true
  }
  hooks {
    pre 'fileUpdate', [file       : "${projectDir}/README.md", pattern: { v, p -> /(\*\*Release\*\*:) $v/ },
                       replacement: { v, p -> "\$1 $v" }]
    pre 'commit', { v, p -> "release ${v}" }
  }
}
 ```
I am using version 1.13.2 of axion-release

This may be related to #364 as the author got the same error later on

**Comment by dmutterSF** [comment]
Still have the same issue with the latest release 1.13.6

**Comment by bgalek** [comment]
hi! We're gonna drop shadow plugin to fix it, check out next release when it's published! :)

**Comment by cloudshiftchris** [comment]
Possibly related to shadowing challenges in #459

**Comment by bgalek** [comment]
1.13.7 without shadow plugin released
