### ISSUE TITLE
Version after release is always snapshot! (with monorepo)

### ISSUE THREAD

**Issue by shashken** [allegro/axion-release-plugin#421]
Duplicate of https://github.com/allegro/axion-release-plugin/issues/332 to get some attention, sorry maintainers :( 
Check out the latest comment I posted in that thread, there is a problem with this plugin with monorepos that does not allow to use this awesome plugin with them 😢 
I think we are close to figuring out why this happends but we need a maintainer/some1 who knows this well to help us here.

**Comment by bgalek** [comment]
Hi, I've commend in the original task ;)
