### ISSUE TITLE
Unable to release from CI Server (JENKNIS)

### ISSUE THREAD

**Issue by philbeiler** [allegro/axion-release-plugin#43]
I'm using the standard git plugin from jenkins  and when I run - I provided the additional parameter to attach to the remote..
./gradlew release -Prelease.attachRemote="ssh://git@hello.com/repo.git"

However, it still fails --  with **HEAD is not set to track another branch**.  I also configured the GIT plugin to check out to a specific branch - but get the same error.

To debug a little, I logged onto the CI server and tried to do a push of the project. The remote (push) repo was updated appropriately...  but the push failed with 

To push the current branch and set the remote as upstream, use
  git push --set-upstream origin master

And then the git push worked from the shell -- **BUT** the Jenkins job still fails with the same error.

Any thoughts?  Thanks

**Comment by adamdubiel** [comment]
Can you configure your build to print `git remote show origin`, or if that fails `git remote show origin -n` (offline version)? I dont know about Jenkins, but Bamboo uses shallow fetch by default, is there any way you could enable fetch with tags? I dont mean full clone, but something in between.

**Comment by toddcscar** [comment]
We are experiencing the exact same error  with Jenkins on our build servers and are troubleshooting.  Don't have a solution yet.

**Comment by adamdubiel** [comment]
I will load Jenkins docker image and try to solve the problem as well,
although i never used Jenkins much.

**Comment by adamdubiel** [comment]
Okay, so solution seems to be pretty straightforward, at least the basic one. Simply disable checks:

```
./gradlew release -Prelease.disableChecks
```

Jenkins pulls repository with attached remotes, but current position is in detached state, so it's not possible to track changes from remote. Can you test it please?

I think disabling checks on Jenkins CI is not a big deal, since it is already a "safe" environment, meaning code is pulled fro repository and there should be no way to bypass these anyway.

**Comment by philbeiler** [comment]
Sure. I can test...  Thanks. Phil

**Comment by philbeiler** [comment]
So that does work --- that is progress!!! 

But now I'm back to issue #37.. If I hard code the -P properties for customKeyfile and customPass, the release process works like a charm. But if I set the properties inside the gradle script --- it fails with the same USERAUTH fail problem as before -- jgit.errors.TransportException.

I cloned your repo, built the dependency,  I assume it should work, but does not. Is there any way to prove that I have the lazy caching of credentials code - and that it is working?

Thanks. Phil

(As a side question -- do you plan on pushing your releases to maven central  any more - you have not done so for the last two.  Thanks)

**Comment by adamdubiel** [comment]
I thought the former problem has been solved already in 1.0.1 - please reopen that issue if it's still broken. You can post relevant parts of build.gradle, i'm only curious in tasks execution order etc.

As to the sidenote - i don't think there is much sense in pushing it to Maven Central if gradle hosts own plugin repository. This also saves us the effort of writing `buildscript { }` clause.

**Comment by philbeiler** [comment]
I will re-open #37. Thanks for the pointer on this problem..

Unfortunately, using the gradle plugin repository is is not very helpful at this point -- or I will have to come up with a new process to download and move dependencies to our air-gapped network. I currently have a nice maven process to pull dependencies, and move them to our internal repository. I will have to figure out an equivalent process for gradle! (Since new "plug-in" repository (access) does not support the ability to provide credentials to secured-repositories -- we are required to use the old style) dependency access.

Thanks again.

**Comment by adamdubiel** [comment]
Ah, i guess i can set up sync between bintray and Maven Central, but this might be a recurring problem for you. Anyway going with dual-deployment is not a problem, i just need to find some time to set it up.

**Comment by tfnico** [comment]
To those who follow in our footsteps; it's actually documented here: http://axion-release-plugin.readthedocs.org/en/latest/configuration/ci_servers.html
