### ISSUE TITLE
Github Actions support

### ISSUE THREAD

**Issue by big-andy-coates** [allegro/axion-release-plugin#431]
I've been setting up a new project using Github's own build Actions and it took a little bit of digging to get the release plugin to work.  Thought I'd share the magic incantation needed...

Obviously, the plugin needs the tags to be available so it knows what the next tag should be.  By default, the `actions/checkout@v2` action doesn't include tags and is only a shallow checkout.

I found adding `git fetch --tags --unshallow` prior to doing a `release` was all that was needed to get everything working, e.g. https://github.com/creek-service/creek-core/blob/main/.github/workflows/gradle.yml#L33

Not sure if you want to add this to your docs?

**Comment by gabrieljones** [comment]
`git fetch --tags --unshallow` should be added to the documentation here:
https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions

**Comment by bgalek** [comment]
@gabrieljones just use
```
scmVersion {
    unshallowRepoOnCI.set(true)
}
```

it will be turned on in upcoming releases ;)

**Comment by bgalek** [comment]
@gabrieljones I thnk not, since we don't have a generic way of introducing those flags, should be easy to add this, I'm ok with that - maybe you would like to create a PR? If not, create an feature request for that and I'll be happy to add this.
