### ISSUE TITLE
Simplify usage on Gitlab CI with versionWithBranch

### ISSUE THREAD

**Issue by david0** [allegro/axion-release-plugin#443]
Gitlab CI seems to do a detached HEAD checkout (no branch name set). I did not find a way to tell not to do so.

We are using the `versionWithBranch` versionCreator and on feature branches it will generate the same version as on the main/master branch.

I was able to work around that by using `-Prelease.overriddenBranchName=$CI_COMMIT_BRANCH`. Maybe the plugin could be improved to take CI_COMMIT_BRANCH into account? Or, at least this workaround should be noted in the Gitlab CI section of the documentation.

**Comment by mklueh** [comment]
I was wondering why I could not get snapshots using Gitlab CI when on my dev branch. When will this be rolled out?

**Comment by bgalek** [comment]
https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#gitlab-ci
