### ISSUE TITLE
Two step configuration - Fail to parse tag

### ISSUE THREAD

**Issue by farget93** [allegro/axion-release-plugin#452]
Hello,
during creating new project using Axion I've faced and issue with achieving support for non standard tags, [name]-[version]-[state].
State is just some String suffix differing in some releases.

Also very important information for this issue is that I am using "com.fizzpod.pater-build" as parent to other projects as well. In that I defined standard behaviour, how tags should be serialize and deserialize as well. And in the new project after applying the pater-build plugin I am just changing the configuration for axion, like scm{...}

So what is the issue?
Well, axion tries to parse the version once it is applied so it uses the first one, from pater-build not from the project it self. And in that case it fails due to bad tag.

See line 52:
[Version Factory](https://github.com/allegro/axion-release-plugin/blob/main/src/main/java/pl/allegro/tech/build/axion/release/domain/VersionFactory.java)

What do I suggest as fix or feature?
A way to delay this evaluation just only and only during the axion task execution. Or just don't be so strict to the version value.

**Comment by bgalek** [comment]
Hi, would you like to create a PR with failing test?

**Comment by farget93** [comment]
Hello,
I've done more investigation into the problem which we were facing and I found it was caused by not "smart" approach from our side. 
So, what was the issue?
Axion plugin was configured in such way, that the prefix was taken from project properties. This is not the best practice since it can fail during the project imports, maybe you are asking why. Well, unfortunately we are also forcing the plugin to evaluate those settings by accessing the version shortly after as follows:

`def actualVersion = scmVersion.version`

So any further changes in configuration by build.gradle and not the pater-build file are not evaluated since forcing the axion to evaluate the current settings fails and stop the task - import/release. I will have to revisit the strategy why are we doing it in such way.

If you are still interested in I can create the test for it, but there is not much you can do it since it is not problem with your application.
I will not close it, so you can let me know if you want the test for it - otherwise just close it. And thanks for quick reaction.

**Comment by bgalek** [comment]
Sure, thanks for your insight!
