### ISSUE TITLE
Confusion in documentation regarding GitHub tokens

### ISSUE THREAD

**Issue by mklueh** [allegro/axion-release-plugin#456]
Hello,

I'm trying to locally run the release command for testing purposes, as I'm facing trouble in my CI.

The documentation states [here ](https://axion-release-plugin.readthedocs.io/en/latest/configuration/authorization/#dynamic_1)

```
task loadGitHubToken << {
    scmVersion.repository.customUsername = loadGitHubTokenFromSomewhere()
}
```

**Saying "Load the token from somewhere and set it as the user name!" - is this correct?**

Besides that, it gives me

```
A problem occurred evaluating root project 'my-root-project'.
> Could not find method leftShift() for arguments [build_bsu9smldjlahp1p79jirwcuya$_run_closure3@381e2620] on task ':loadGitHubToken' of type org.gradle.api.DefaultTask.
```

**The << operator might be legacy Gradle Syntax and can't be used with 7.4.2 anymore**

I was trying to use the CLI arguments as following:

> ./gradlew :applications:my-application:release -Drelease.customPassword=my-github-token -Drelease.customUserName=some-random-custom-bot-name

But this gives me 

```
Looking for uncommitted changes.. 
Checking if branch is ahead of remote..
Checking for snapshot versions..

> Task :applications:my-application:release FAILED
Working on released version 0.1.0, nothing to release
Pushing all to remote: origin
Exception occurred during push: axion.org.eclipse.jgit.api.errors.TransportException: https://github.com/some-user/my-project.git: not authorized

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applications:my-application:release'.
> axion.org.eclipse.jgit.api.errors.TransportException: https://github.com/some-user/my-project.git: not authorized

```

**Comment by bgalek** [comment]
Hi, docs sould be updated then.
if this works:
```
-Prelease.customUsername=${{github.actor}} -Prelease.customPassword=${{github.token}}
```
you're passing wrong credentials or your bot isn't allowed to push
