### ISSUE TITLE
Failed to parse version: v--0.1.0 that matched configured prefix: v

### ISSUE THREAD

**Issue by mklueh** [allegro/axion-release-plugin#457]
Hello,

I'm trying to use this plugin in a monorepo with GitHub Actions, but I'm running into this issue while attempting to build one of my applications

```
A problem occurred evaluating root project 'my-root-project'.
> Failed to parse version: v--0.1.0 that matched configured prefix: v. There can be no tags that match the prefix but contain non-SemVer string after the prefix. Detailed message: Unexpected character 'HYPHEN(-)' at position '0', expecting '[DIGIT]'
```

This is my root build.gradle setup:

```
scmVersion {
    dryRun = true
    localOnly = false
    useHighestVersion = true
    versionCreator 'versionWithBranch'
    repository {
        pushTagsOnly = true
    }
    monorepos {
        projectDirs = project.subprojects.stream()
                .filter(p -> "applications" != p.getParent().name)
                .map(p -> p.name)
                .collect(Collectors.toList())
    }
    nextVersion {
        suffix = 'alpha' // tag suffix
        separator = '-'
    }
    checks {
        aheadOfRemote = true
        uncommittedChanges = true
        snapshotDependencies = true
    }
}

//I configure projects that sit in the applications module only
subprojects.stream()
        .filter(p -> "applications" == p.getParent().name)
        .forEach(p -> {
            p.configure(p) {
                apply plugin: 'pl.allegro.tech.build.axion-release'
                p.version = scmVersion.version
            }
        })
```

The task I'n running in CI is 

> ./gradlew --continue :applications:my-application:release

And I've removed all previous tags from the commit history

What am I doing wrong here?

**Comment by bgalek** [comment]
it seams you have `v--0.1.0` prefix that is not being parsed, it's advised to use semver tags (v0.1.0), just add another valid tag on your last version commit, and axion will continue your version history

**Comment by mklueh** [comment]
@bgalek ok thanks, just to be clear if I understand it correctly:

Axion is assumes a false prefix by default and the default initialization routine does not set the initial version to 0.1.0 as stated [here](https://axion-release-plugin.readthedocs.io/en/latest/configuration/version/#initial-version) - and this behavior is caused by the monorepo?

**Comment by mklueh** [comment]
This issue was likely cause by the missing scmVersion config in the submodules build.gradle

See https://github.com/allegro/axion-release-plugin/issues/461
