### ISSUE TITLE
Support for gradle 7.x?

### ISSUE THREAD

**Issue by benfortuna** [allegro/axion-release-plugin#458]
Hi, many thanks for a very useful release plugin.

I've just upgraded to Gradle 7.4.2 and it seems the currentVersion task is no longer detecting git tags (I haven't tried a release yet). 

I noticed a commit where you reverted to Gradle 6 for compatibility reasons, is it a known issue that Gradle 7 is not yet supported? Any plans to support Gradle 7 in future? Thanks.

**Comment by bgalek** [comment]
please do, and get back with feedback! That would be a bummer if standard functionality would not work on gradle7!

**Comment by benfortuna** [comment]
So I removed all old marker tags on my git branch, but it didn't make a difference. 

I can workaround this issue for now by using `markNextVersion` task, as it will correctly pick up the marker tag, but for some reason it doesn't seem to be recognizing the latest version (3.2.2) to increment.

These are my current latest release tags (not including marker tag):

```
% git tag | grep 3.2           
ical4j-3.2.0
ical4j-3.2.1
ical4j-3.2.2
```

**Comment by benfortuna** [comment]
Ok, not sure how but it's all working again without the marker tag. Perhaps it was an issue with remote tags, but I will close this ticket as it does seem to work with gradle 7.
