### ISSUE TITLE
Error running Gradle unit tests with axion 1.13.4+: java.util.ServiceConfigurationError: java.nio.file.spi.FileSystemProvider: Provider org.apache.sshd.common.file.root.RootedFileSystemProvider not found

### ISSUE THREAD

**Issue by cloudshiftchris** [allegro/axion-release-plugin#459]
...in some cases the error is "Circular loading of installed providers detected" due to Groovy having a try/finally that attempts to reload filesystems when the previous attempt has failed (due to the fs not found error in the subject).

Perhaps related to the shading adjustments in 1.13.4 (#412), as the axion JAR contains META-INF/services/java.nio.file.spi.FileSystemProvider with an incorrect value of "org.apache.sshd.common.file.root.RootedFileSystemProvider" (the shaded value is "axion.org.apache.sshd.common.file.root.RootedFileSystemProvider"

In build.gradle.kts the 'shadowJar' task is missing "mergeServiceFiles()" to adjust service files accordingly.  This was not there previously for the 'shadow' prefix - possibly this worked due to an elsewhere-shadowed library being grabbed (alternately, other code changes could now be triggering the loading of this FS provider.  edit: confirmed, this FS provider was not present prior to 1.13.4).

#415 is related as well - the presence of dependencies was masking this issue, with their removal it's a gamble as to whether a dependency is present at all (or at the desired version).

cc @kkocel

**Comment by cloudshiftchris** [comment]
There are other service files present that also have incorrect references.

**Comment by cloudshiftchris** [comment]
The interaction here is with JUnit temporary dirs and Gradle ProjectBuilder; here's a Kotlin snippet, it's the use of ProjectBuilder that is the start of the failing stack trace.

```
internal abstract class AbstractTest {

    @BeforeEach
    fun beforeEach(@TempDir tempDir: File) {
        project = ProjectBuilder.builder()
        .withName("Test project")
        .withProjectDir(tempDir)
        .build()
    }
}
```

**Comment by bgalek** [comment]
hi! Next release will drop shadow as it caused more problems than it should!

**Comment by bgalek** [comment]
1.13.7 without shadow plugin released
