### ISSUE TITLE
Please release to maven central

### ISSUE THREAD

**Issue by BryanDollery** [allegro/axion-release-plugin#46]
Hey, this looks great, but we have constraints at work restricting our ability to build our own version of your tool. Do you think you might have some time soon to release the latest version to maven central?

**Comment by adamdubiel** [comment]
Yes, this is the issue i discussed with @philbeiler . I had the code, so it should be quite quick, but i need some time to make it happen. I am mainly occupied with creating hooks at the moment (see #36 ), i see if  i can make Maven Central release happend together with their release.

**Comment by adamdubiel** [comment]
I recreated the configuration, `1.2.0` will be released to Central.

**Comment by adamdubiel** [comment]
Version 1.2.0 has been release, waiting for Central sync (this should be done in few hours at most).
