### ISSUE TITLE
currentVersion on tekton

### ISSUE THREAD

**Issue by JustDoItN** [allegro/axion-release-plugin#479]
Hi to everyone

we're trying to replace jenkins with tekton and ran into the showstopper as described below.

id "pl.allegro.tech.build.axion-release" version "1.13.9"

In jenkins and locally currentVersion works as expected - for simplicity-sake i'll show only local stuff:

local:
![image](https://user-images.githubusercontent.com/26071987/171200384-5f33beb4-d75e-4b1c-8189-8c25cde0ca03.png)

![image](https://user-images.githubusercontent.com/26071987/171200687-dd8be16e-2e71-4045-93c2-2aed84c012c8.png)
(after Gradle-update to 7.4.2 - it still works, as expected)

on tekton (with subsequent fail on createRelease):
![image](https://user-images.githubusercontent.com/26071987/171201689-99e19efb-1bf3-48b4-92b3-09b5933b7402.png)
(the only difference in version on pod and local is java on patch-level of java 11)

root-build.gradle on a small multi-module project
![image](https://user-images.githubusercontent.com/26071987/171202586-836257a3-7231-47db-bbef-fb579236fdcb.png)

any ideas on what it fails?

Thanks tons in advance

**Comment by JustDoItN** [comment]
Hi bgalek

once again thanks for your advice - pulling the full repo brought the breakthru - now it works

Cheers

**Comment by bgalek** [comment]
@JustDoItN great news! Do you think you could add a FAQ into docs with some hints about the issue? I'm looking for anything that would help people with error like you ;)

**Comment by JustDoItN** [comment]
@bgalek for sure! Should I just add another md-file FAQ below example or as a top-level topic?

**Comment by bgalek** [comment]
I would start a new section FAQ or Troubleshooting ;)
