### ISSUE TITLE
release -Prelease.dryRun fails

### ISSUE THREAD

**Issue by davidbanhos** [allegro/axion-release-plugin#488]
Hi,

   I'm running using Gradle 7.4.2  (wrapper). I'm having the below issue:

  _PS XXXXX\TestPluginAxionRelease> .\gradlew.bat release -Prelease.dryRun
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
**Task '.dryRun' not found in root project 'TestPluginAxionRelease'.**

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s_

 Sorry, but am I missing any setup?
 
Plugins setup:
_plugins {
    id 'java'
    id 'maven-publish'
    id "pl.allegro.tech.build.axion-release" version **"1.13.14"**
}_

**Comment by bgalek** [comment]
hi, it looks like a shell problem, never used PowerShell in day-to-day basis - but I'm guessing you need to escape dot (.) character

**Comment by bgalek** [comment]
i would guess: `.\gradlew.bat release -Prelease\.dryRun`

**Comment by davidbanhos** [comment]
Spot on, @bgalek ! Thanks.

I've just executed the cache on "GitBash" using **gradew** and it worked correctly.
But  the back lash (\.dryRun) still does not work on PS. 

Let me investigate on the case.

**Comment by davidbanhos** [comment]
Btw, old "Command prompt" just works without issues. No back-slash required.
