### ISSUE TITLE
Abitlity to create a release branch and to use createReleaseCommit on it

### ISSUE THREAD

**Issue by martinda** [allegro/axion-release-plugin#50]
Some workflows involve the creation of a release branch. Would this be an appropriate feature for this plugin? A branch would be created, then a release commit would be made to that branch. IT would work along with the createReleaseCommit feature, in the sense that the commit would be made to the release branch. The release branch would be named in a similar manner as the tag is named. What do you think?

**Comment by adamdubiel** [comment]
I think it's a nice feature, but we have to think about merging stuff. If release branch won't be merged to master/production, the version won't propagate there - do you have any thoughts on this?

**Comment by martinda** [comment]
I was thinking of the workflow presented here http://blogs.atlassian.com/2013/10/inside-atlassian-feature-branching-on-the-stash-team/ (scroll down to the branching model picture).

Assuming the release number is structured as Major.minor.bugfix, release numbers would have to be based on the release branches, and on their tags. Release branches would need to be initialized (tagged) to start with a new Major release number (1.0.0, 2.0.0, ...). Feature releases would increment the minor number (1.1.0, 1.2.0, ...). Merges from bugfixes would increment the bugfix number (1.1.1, 1.1.2, ...). The plugin would need to have a few new tasks to increment specific elements of the release number depending on what is being done (feature, bugfix or new release stream). I am not sure whether this changes the search that gets the currentVersion value. It may not if the plugin searches from the current commit: the user or the CI system could prepare the local repo with the right checkout. I feel this problem is workflow specific and should not be the concern of the plugin.

For users of this workflow, it is harder to get a snapshot release number: a user would need to get (merge) their feature into a release branch before she could get a snapshot release number (when working locally, she could merge into master then into the feature branch, or directly into the feature branch).

I think the plugin needs to be workflow agnostic, but that it should not preclude any specific workflow. Workflow complications could be handled in the CI system and by the users who choose a more complicated workflow.

I think the plugin only need three more methods: one to increment each element of the version number. And it may have these methods already, I have not looked at the plugin code yet.

**Comment by adamdubiel** [comment]
I will crunch this idea overnight, but quick comment: there is no way to increment custom part of version, but adding this is a really quick fix.

**Comment by martinda** [comment]
I just found a gradle plugin that implements [Semantic Versionning](https://github.com/ajoberstar/gradle-git/wiki/SemVer%20Support) after following a grgit link.

**Comment by adamdubiel** [comment]
axion-release uses semver as well, it just does not expose methods to pick which version part to increment (except from forcing version), adding which is not much of a problem.

**Comment by martinda** [comment]
I am thinking that maybe, if I had a release branch were I recorded the releases, I could apply versioning just on that branch. I would increment the minor number if the release branch was a merge from master, and I would increment the patch number if the release branch was a merge from a bugfix branch. The developers would have to set the Major number in the build.gradle, because so far I cannot detect non-backward compatible changes. Maybe the Major number would warrant a new release branch all together, this way past releases could be bugfixed for long term maintenance.

I would want to take advantage of the other components of semver, like the pre-relase and the build metadata as well. I think nextVersion would work for the pre-release component, but probably not for the build metadata.

Do you think this plugin would work in this scenario? Thanks!

**Comment by adamdubiel** [comment]
If you need to customize pre-release or build metadata, just create `versionCreator` - you have access to current commit id etc. If you come up with something you would like to share, i will add it to predefined creators.

As to the general problem: i'm thinking you could have the release branch and on release, inspect branch history. If commits since last release come from branch bugfix/*, then increment patch. If any of them comes from some feature/*, increment minor. 

```
release    ----o---m----m---o
bugfix/*    -------/------/-------
feature/*  -------------/--------
```

Above graph shows situation in which release branch has been released, then both bugfix and feature branches have been merged. Now when inspecting history we could see the need of updating minor version. Does it look like something you need?

if it does, i need to think if its technically possible to achieve..

**Comment by adamdubiel** [comment]
Is this issue still relevant? Trying to close all long-living issues :)

**Comment by martinda** [comment]
Hello Adam. I agree to close the issue. Thanks.

**Comment by adamdubiel** [comment]
Great, thanks :)

**Comment by vbuell** [comment]
Just curious, what's was the solution for that request? Did you manage to pair `gradle-git` with `axion`?

**Comment by martinda** [comment]
@vbuell In the end, I am using another solution. At this time for my flow this type of automation is not a good fit. I think I will create release branches only when needed, and create them manually. Not all releases need a support branch after all.
