### ISSUE TITLE
currentVersion ignores scmVersion.repository.directory

### ISSUE THREAD

**Issue by hzpz** [allegro/axion-release-plugin#503]
I'm working on a project, were the Gradle project is in a sub-directory of the Git repository, like this:
```
└── root-directory  <-- this is the root of the Git repository
    └── gradle-project  <-- this is the root of the Gradle project
        └── build.gradle
```

My `build.gradle` contains the following:
```groovy
plugins {
    id "pl.allegro.tech.build.axion-release" version "1.13.14"
}

group = "some.group"
version = scmVersion.version

scmVersion {
    repository {
        directory = project.rootProject.file('../')
    }
}
```

Running `gradle currentVersion` gives me the following output:
> \> Configure project :
Failed to open repository, trying to work without it org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /Users/[...]/Dev/root-directory/gradle-project
Couldn't perform is legacy DefTagname Repository command on uninitialized repository
Couldn't perform is legacy DefTagname Repository command on uninitialized repository
Could not resolve current position on uninitialized repository, returning default
Could not resolve current position on uninitialized repository, returning default
Couldn't perform check uncommitted changes command on uninitialized repository
>
> \> Task :currentVersion
> 
> Project version: 0.1.0-SNAPSHOT

Note that the plugin is looking for the Git repository in the directory `gradle-build`, not in `root-directory`. It would seem that the `currentVersion` task somehow ignores `scmVersion.repository.directory`. 

However, the task `verifyRelease` _does_ seem to work as expected:
> \> Configure project :
Failed to open repository, trying to work without it org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /Users/[...]/Dev/root-directory/gradle-project
Couldn't perform is legacy DefTagname Repository command on uninitialized repository
Couldn't perform is legacy DefTagname Repository command on uninitialized repository
Could not resolve current position on uninitialized repository, returning default
Could not resolve current position on uninitialized repository, returning default
Couldn't perform check uncommitted changes command on uninitialized repository
>
> \> Task :verifyRelease FAILED
> Looking for uncommitted changes.. FAILED
>
> Staged changes:
> &nbsp;&nbsp;&nbsp;modified: gradle-project/build.gradle
>
> Unstaged changes:
> &nbsp;&nbsp;&nbsp;added: gradle-project/.gitignore

Is there something wrong with my setup, is this somehow working as designed or is it actually a bug?

I am using Gradle 7.4.2 on macOS with Eclipse Adoptium 11.0.13+8.

**Comment by bgalek** [comment]
Hi, it can actually be a bug, do you want to investigate it further or you can wait for me to check that out? :)

**Comment by gabrieljones** [comment]
I am also experiencing this bug. I am attempting to use a relative path:
```
scmVersion {
  repository {
    directory.set(project.rootProject.file("../../"))
  }
}
```

**Comment by caribbeann** [comment]
Also affected by this :(

**Comment by vinzpk1981** [comment]
Seems I also have similar issue, 
Have a mono repo ( root)  with independent modules (  added to the root settings.gradle.kts via includedBuild)  at the top level as follows
root
     module 1 ( has the plugin applied with repository config path set to root)
     module 2 ( has the plugin applied with repository config path set to root)
     module 3
Module 1 and module 2 are completely independent to each other and I am able to release them separately which is great. I have set the tag prefix specific to each module
My problem is module 3 is a common library used by module 1 and module 2. If I have a commit in module 3 alone, module 1 or module 3 currentVersion is not able to detect that change.

I am using the version 1.16.1. Do you know if  this is  valid use case for this plugin to solve ?

**Comment by kkocel** [comment]
I have experienced it as well.

My project structure:

repo/backend

my `build.gradle.kts`:

```kotlin
scmVersion {
    repository {
        directory.set(project.rootProject.file("../").toString())
    }
}
```

and I get:

```
$ ./backend/gradlew -p backend/ -q currentVersion -Prelease.quiet
Couldn't perform is legacy DefTagname Repository command on uninitialized repository
Could not resolve current position on uninitialized repository, returning default
Could not resolve current position on uninitialized repository, returning default
Couldn't perform check uncommitted changes command on uninitialized repository
0.1.0-SNAPSHOT
```

**Comment by kkocel** [comment]
And I found why it happens :)

In my `build.gradle.kts` I had:

```kotlin
version = scmVersion.version

scmVersion {
    repository {
        directory.set(project.rootProject.file("../").toString())
    }
}
```

I had to configure the repository directory before calling `scmVersion.version`:

```kotlin
scmVersion {
    repository {
        directory.set(project.rootProject.file("../").toString())
    }
}

version = scmVersion.version
```

**Comment by bgalek** [comment]
thx ;)

**Comment by ddeath** [comment]
@bgalek sorry for pinging you on old issue. We got burned by this as well after some dev did refactor in one of our services.

However I noticed weird thing. If we run:
```
./gradlew release \
      -Prelease.disableChecks \
      -Prelease.pushTagsOnly \
      -Prelease.overriddenBranchName="feature/DLV-446" \
      -Prelease.customUsername=*** \
      -Prelease.customPassword=***
```

Then we get same error, however in the end release will detect correct version:
```
> Configure project :
Failed to open repository, trying to work without it org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/runner/work/xxxx/customer-master-service
Couldn't perform is legacy DefTagname Repository command on uninitialized repository
Could not resolve current position on uninitialized repository, returning default
Could not resolve current position on uninitialized repository, returning default
Couldn't perform check uncommitted changes command on uninitialized repository

> Task :verifyRelease
Skipping uncommitted changes check
Skipping ahead of remote check
Skipping snapshot dependencies check

> Task :release
Creating tag: customer-master-service-app-0.0.28
Pushing all to remote: origin
```

However if we run `./gradlew currentVersion -q` right after it,  we will get:
```
Couldn't perform is legacy DefTagname Repository command on uninitialized repository
Could not resolve current position on uninitialized repository, returning default
Could not resolve current position on uninitialized repository, returning default
Couldn't perform check uncommitted changes command on uninitialized repository

Project version: 0.1.0-SNAPSHOT
```

So it seems there could be way to fix this? I mean if release is working, then currectVersion in theory could work as well...

Also if there is no fix for it, wouldnt be better to throw exception instead of fallbacking to "wrong" version?

Let me know what you think. I could try to work on it if it is something you think is worth it...
