### ISSUE TITLE
class "org.eclipse.jgit.transport.JschConfigSessionFactory"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by kicktipp** [allegro/axion-release-plugin#525]
I use this plugin in version '1.14.0'. The axion-release-plugin has a dependency on 

```
project.ext.versions = [
    jgit     : '5.12.0.202106070339-r',
]
...
implementation group: 'org.eclipse.jgit', name: 'org.eclipse.jgit', version: versions.jgit

```
I have another plugin which is using jgit:

```
dependencies {
    implementation 'org.eclipse.jgit:org.eclipse.jgit:6.2.0.202206071550-r'
    //  implementation 'org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r'
}
```

When I update jgit in the other plugin from version 5 to version 6 I get the following error:

```
A problem occurred evaluating root project 'PluginComsumer'.
class "org.eclipse.jgit.transport.JschConfigSessionFactory"'s signer information does not match 
signer information of other classes in the same package

```
I reduced the problem to a really simple no operation plugin. The plugin is really doing nothing just having a dependency on jgit. 

The error does only occur in the main project as soon as I add
```

allprojects {
    project.version = scmVersion.version
}

```
So I have two conditions:
- there must be a dependency to jgit v6 in another gradle plugin (not lib) 
- the main project must be configured with `project.version = scmVersion.version`

I guess this can be fixed by updating jgit. But maybe then the error occurs the other way around.

**Comment by cloudshiftchris** [comment]
This is fugly.  It's due to axion declaring a dependency on several jgit modules (5.13.1.202206130422-r as of v1.14.1) with other plugins (spotless, in my case) pulling in other jgit modules, resulting in a version alignment issue.

This is from axion 1.13.14 w/ spotless 6.11.0 (initial version on the left):
```
org.eclipse.jgit:org.eclipse.jgit.gpg.bc:5.12.0.202106070339-r -> 5.13.1.202206130422-r
org.eclipse.jgit:org.eclipse.jgit.ssh.apache:5.12.0.202106070339-r -> 5.13.1.202206130422-r
org.eclipse.jgit:org.eclipse.jgit.ssh.jsch:5.12.0.202106070339-r -> 5.13.1.202206130422-r
org.eclipse.jgit:org.eclipse.jgit.ui:5.12.0.202106070339-r -> 5.13.1.202206130422-r
org.eclipse.jgit:org.eclipse.jgit:5.12.0.202106070339-r -> 5.13.1.202206130422-r
org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r -> 5.13.1.202206130422-r
org.eclipse.jgit:org.eclipse.jgit:5.13.1.202206130422-r
```

Was able to force alignment by adding the below.  The above output shows the versions aligning correctly across all jgit modules (prior to alignment the versions were mixed).

```
buildscript {
    dependencies { 
            components.all<JGitAlignmentRule>()
    }
}

abstract class JGitAlignmentRule : ComponentMetadataRule {
    override fun execute(ctx: ComponentMetadataContext) {
        ctx.details.run {
            if (id.group == "org.eclipse.jgit") {
                belongsTo("org.eclipse.jgit:jgit-virtual-platform:${id.version}")
            }
        }
    }
}
```

Unaware of how this can be addressed by axion (or any other jgio-consuming library) - jgit itself should publish a BOM.

**Comment by bgalek** [comment]
maybe jgit 6 will do better ;)

**Comment by mklueh** [comment]
Any chance to get a hint on how to solve it with Groovy?

Tried to adapt the Kotlin script


```
abstract class JGitAlignmentRule implements ComponentMetadataRule {

    void execute(ComponentMetadataContext ctx) {
        ctx.details.run {
            if (id.group == "org.eclipse.jgit") {
                belongsTo("org.eclipse.jgit:jgit-virtual-platform:${id.version}")
            }
        }
    }
}

buildscript {
    repositories {
    }
    dependencies {
        components.all(JGitAlignmentRule)
    }
}

```

But I'm getting 


> A problem occurred evaluating root project 'my-project'.
> JGitAlignmentRule
