### ISSUE TITLE
Version tag different from scmVersion.version

### ISSUE THREAD

**Issue by danhallin** [allegro/axion-release-plugin#58]
For some reason the version that goes into tag and the version that is returned by scmVersion.version differ. 

I have a version defined like this (YY.M.X where YY is year, M is month, X is incremental restarting from 1 every month). The problem I'm having is that while scmVersion.version creates these correctly as months switch, the version that goes into the tag only increment the last digit.

So if my last tag is PREFIX-15.2.12 then scmVersion.version returns PREFIX-15.3.1 (as month is now 3) while the tag is created as PREFIX-15.2.13.

Am I doing something wrong or is this a bug in how the versionCreator is used?

My version creator:

        versionCreator { version, position ->
            Pattern p = Pattern.compile("([0-9]+)[.]([0-9]+)[.]([0-9]+)")
            Matcher m = p.matcher(version);
            if (m.find()) {
                int year = Integer.parseInt(m.group(1))
                int month = Integer.parseInt(m.group(2))
                int minor = Integer.parseInt(m.group(3))

                Calendar cal = Calendar.getInstance();
                cal.setTime(new Date());
                if ((cal.get(Calendar.YEAR) % 100) != year || cal.get(Calendar.MONTH) != (month - 1)) {
                    minor = 1
                }

                return String.format("%02d.%s.%s",
                        cal.get(Calendar.YEAR) % 100,
                        cal.get(Calendar.MONTH) + 1,
                        minor)
            }

            return version
        }

**Comment by adamdubiel** [comment]
Hm, so versionCreator (or should it be **decorator**) decorates version read from SCM. The functions that are responsible for creating tags are serializers/deserializers. See http://axion-release-plugin.readthedocs.org/en/latest/configuration/version.html . Now i see that it might be inconsistent or unintuitive, but haven't thought on how to fix it.

**Comment by danhallin** [comment]
Adding a serializer which did pretty much the same thing (some added fluff) as the versionCreator solved the problem, many thanks!
