### ISSUE TITLE
Check if tag prefixes for multi-module project are not prefixes of each other

### ISSUE THREAD

**Issue by mkosmul** [allegro/axion-release-plugin#61]
If you accidentally configure two subprojects in a multi-module project to use tag prefixes which are prefixes of each other, e.g.:

```
scmVersion {
    tag {
        prefix = 'something'
    }
} 
```

and

```
scmVersion {
    tag {
        prefix = 'something-client'
    }
} 
```

then releasing the module with longer tag prefix (effectively: creating a git tag such as `something-client-1.2.3`) will cause the project to become unusable. Any Gradle command including gradle clean ends with:

```
FAILURE: Build failed with an exception.
* Where:
Build file '/home/mkosmul/src/flex/build.gradle' line: 130
* What went wrong:
A problem occurred evaluating root project 'something'.
> com.github.zafarkhaja.semver.UnexpectedCharacterException (no error message)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
```

This is because Gradle tries to parse the tag `something-client-1.2.3` but using the prefix `something`, which results in it trying to parse `client-1.2.3` as a version number, which fails. However, the error message is very confusing.

The best thing that can be done here is probably to valdiate all tag prefixes in order to ensure not one of them is a prefix of any other, thus preventing the confusing error message from appearing.

**Comment by adamdubiel** [comment]
I added better explicit error message in #190
