### ISSUE TITLE
Unable to use latest SSH features

### ISSUE THREAD

**Issue by wdroste** [allegro/axion-release-plugin#633]
Summary jsch is abandoned and BitBucket (and GitHub) recommends the latest SSH key type ex: ECDSA

We followed bitbucket's instructions and our builds started to fail because jsch couldn't use the latest ECDSA private key and therefore axion-release-plugin failed to tag our repository using Git over SSH.

For more information:
https://github.com/gradle/gradle/pull/20387

Drop in replacement:
https://github.com/mwiede/jsch

**Comment by bgalek** [comment]
hi @wdroste some people already tried that, https://github.com/allegro/axion-release-plugin/pull/610/files and it seems it won't be so easy as "drop in" :(

**Comment by bgalek** [comment]
Should be fixed

**Comment by wdroste** [comment]
Awesome thanks
