### ISSUE TITLE
CreateVersionInfo task to fix version in build pipeline

### ISSUE THREAD

**Issue by coco1979ka** [allegro/axion-release-plugin#64]
When I use axion release plugin within my jenkins build pipeline, only the first job will be able to fetch the version from git repository. For all downstream jobs I prefer to clone the workspace and so I cannot get the version from the plugin.
So it should be possible to call a task in the first job to generate a VersionInfo file, which can be used in other jobs.

Any other ideas?

**Comment by adamdubiel** [comment]
If i understand correctly (i'm not a Jenkins user): only first job works with .git, others have no access to .git?

I think it's doable, i imagine it would be sth like:

```
./gradlew persistVersion -Prelease.versionFile=version.info
# later on...
./gradlew build -Prelease.readVersion -Prelease.versionFile=version.info
```
