### ISSUE TITLE
TransportException: Not authorized while pushing all tags to remote

### ISSUE THREAD

**Issue by bl4keee** [allegro/axion-release-plugin#658]
Hi! I am struggling with pushing changes with axion-release and keep receiving above mentioned exception. 

The thing is, plugin seems to work fine with **./gradlew currentVersion** that prints out the version correctly as below: 

![current-version](https://github.com/allegro/axion-release-plugin/assets/50672367/e5f652ff-047a-496b-9945-d834b0cb9fe8)

However, running **./gradlew release -Prelease.customUsername="username" -Prelease.customPassword="password"** or **./gradlew release -Prelease.customUsername=username -Prelease.customPassword=password** results in **not authorized** error.

![not-auth](https://github.com/allegro/axion-release-plugin/assets/50672367/a7d09465-1cb6-4cda-8109-552c9cbaeb9b)

Plugin version used: 1.15.4
Gradle version: 7.6.1
The same issue occurs on Windows 10 as well as Ubuntu 22.04.
Build gradle configuration as follows:

![Screenshot from 2023-09-18 20-59-21](https://github.com/allegro/axion-release-plugin/assets/50672367/9153d352-e52b-4fca-9d94-8796e9aef7f6)

Similiar issue: https://github.com/allegro/axion-release-plugin/issues/211

Is there any workaround besides providing credentials in build.gradle like below? 

`scmVersion {
	repository {
		type = 'git'
		remote = 'origin'
		customUsername = ''
		customPassword = ''
	}
}`

**Comment by tim-str** [comment]
Hi there,
you can probably go ahead with the below approach.

tasks.register('loadStashToken') {
    group 'release'
    scmVersion.repository.customUsername.set("$artifactory_user")
    scmVersion.repository.customPassword.set("$artifactory_password")
}

tasks.named('release') {
    dependsOn loadStashToken
}

**Comment by bl4keee** [comment]
@tim-str 
Thanks for posting your solution. I am not really able to get authenticated using any way present in  the documentation. 
So far, I've tried using ssh-agent based approach on Linux that does not seem to work, solely providing username and password via gradle parameters also cannot get me authenticated as well as trying to pass these to variables through custom made gradle tasks. 
I am not quite sure, but seems like the plugin does not work well with my version of gradle (7.6.1).

**Comment by bgalek** [comment]
Should work now
