### ISSUE TITLE
Having GPG signing enabled seems to make pre commits fail

### ISSUE THREAD

**Issue by enquestor** [allegro/axion-release-plugin#674]
I currently have gpg signing via ssh key enabled( `gpg.format=ssh` ). It seems like gpg signing just doesn't work well with this plugin (possibly due to usage of [JGit](https://bugs.eclipse.org/bugs/show_bug.cgi?id=581483)?), as previously release tasks seem to also fail with gpg signing via gpg key also. 

Is it advised to just not sign release commits using this commit? Or would gpg signing be supported in future releases?

**Comment by bgalek** [comment]
it should be supported, would you like to dig into the project and debug this case?
