### ISSUE TITLE
RemoteRefUpdate Status is not populated to exception logger

### ISSUE THREAD

**Issue by VicenteJankowski** [allegro/axion-release-plugin#684]
GitRepository.class has ```verifyPushResults``` method, which looks for ```RemoteRefUpdate``` instance of package ```org.eclipse.jgit.transport``` with status different than ```OK```. As a result of ```verifyPushResults``` there is created new ```ScmPushResult``` instance in which there is only populated value of message of the ```RemoteRefUpdate```, but not status. As documentation of ```RemoteRefUpdate``` states, message is present only if it is "needed/possible". 

As consequence, there are cases in which push results in self-explaining failure status with no message - this happens for example for ```REJECTED_NONFASTFORWARD``` status.

Because of the above, if push will be rejected with status, which does not include message, we then get gradle task failure with exception ```ReleaseFailedException``` with no error message:
```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':release'.
> pl.allegro.tech.build.axion.release.ReleaseFailedException (no error message)
```
This is hard to quickly understand the reason of the problem and to debug.

_Improvement suggestion_:
The code should populate ```RemoteRefUpdate.Status``` to ```ScmPushResult.class``` and then status should be included in exception logger. Example of possible stdout:
```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':release'.
>  pl.allegro.tech.build.axion.release.ReleaseFailedException 
  Status: REJECTED_NONFASTFORWARD
  Message: (empty)
```

**Comment by bgalek** [comment]
hi, nice idea! would you like to make a PR?:)

**Comment by VicenteJankowski** [comment]
Of course, already in progress :)
