### ISSUE TITLE
Axion should skip creating new tag if it already exists AND this existing tag is on head

### ISSUE THREAD

**Issue by vbuell** [allegro/axion-release-plugin#69]
There is a common situation when you got "Tag already exists" exception when rereleasing after failed release. We shouldn't threat such case as fatal if the commit id of existing tag is the same as head id.

**Comment by vbuell** [comment]
Pull Request: https://github.com/allegro/axion-release-plugin/pull/74

**Comment by adamdubiel** [comment]
Released in 1.2.4.
