### ISSUE TITLE
axion should always release if force version

### ISSUE THREAD

**Issue by vbuell** [allegro/axion-release-plugin#70]
It's impossible to release forced version when:
* we are currently on released version but we want to release yet another version (say, we have many releasing branches and I want to release from the same position both 1.0.0 and 0.99.15)
* in case if something went wrong last time and axion already had created tag but later didn't managed to push changes to remote; and we want to re-release it again after we have fixed the issue

For cases like this it make sense to treat forceVersion option more strictly way - it should try to re-release the version if possible, even if we are already on released version.

**Comment by vbuell** [comment]
Pull Request: https://github.com/allegro/axion-release-plugin/pull/73

**Comment by adamdubiel** [comment]
Second case won't work - since we already have a tag with same name, git will complain (i guess it's #69 that fixes that). As to the first option - why would you like to have the same piece of code marked by two different versions? axion-release will return the latter tag always anyway. Can you draft an example, when this will actually work?

**Comment by vbuell** [comment]
The realistic examples that happened in my practice:
- Releasing final version after the release candidate, if no bugs was fixed. Like: 2.0.0-rc5, 2.0.0-GA. Both may point to the same git commit.
- Sometimes you have to release something at the end of the spring (for sprint demoing, for smoke testing, etc). In that case 2.0.0-s47 - where s47 is the # on sprint - may point to the same git commit as 2.0.0.

Regarding the second case - you're absolutely right - #69 should care about that.

**Comment by adamdubiel** [comment]
Okay, i see the point - please take a look at my code review comments and i will merge it afterwards.

**Comment by adamdubiel** [comment]
Released in 1.2.4.
