### ISSUE TITLE
Question - How to serialize / deserialize tag in 1.16.1?

### ISSUE THREAD

**Issue by jerzykrlkroche** [allegro/axion-release-plugin#704]
Hello team.

I've recently upgraded to version 1.16.1 and my project won't build.

I've set up the serialization just like the [documentation](https://axion-release-plugin.readthedocs.io/en/latest/configuration/version/#serialization) says:

```
scmVersion {
    tag {
        serialize({config, version -> "my-version"})
    }
}
```

And I'm getting this Gradle error:

```
> Could not find method serialize() for arguments [build_2wfsgo14h16840owj4rup62bu$_run_closure1$_closure5$_closure6@5e1de291] on object of type pl.allegro.tech.build.axion.release.domain.TagNameSerializationConfig.
```

Is there something wrong with the code?

**Comment by wborn** [comment]
I think the docs are wrong and you need to use `serializer` and `deserializer` instread.

See also:

https://github.com/allegro/axion-release-plugin/blob/3d5aa62d36ef247460bbe85a90c4fc6510df9195/src/test/groovy/pl/allegro/tech/build/axion/release/infrastructure/config/NextVersionPropertiesFactoryTest.groovy#L19-L20
