### ISSUE TITLE
Cannot release pre-release versions like 2.0.0-rc2

### ISSUE THREAD

**Issue by vbuell** [allegro/axion-release-plugin#71]
Axion doesn't allow to release versions with suffixes. `gradle release -Prelease.forceVersion=2.0.0-rc2` releases 2.0.0 instead.

**Comment by vbuell** [comment]
https://github.com/allegro/axion-release-plugin/pull/72

**Comment by adamdubiel** [comment]
Thanks for the PR, i will review it tomorrow :) Same with other issues you created today.

**Comment by adamdubiel** [comment]
Released in 1.2.4.
