### ISSUE TITLE
Default Versioncreator "VERSION_WITH_BRANCH" changes Release-Version name

### ISSUE THREAD

**Issue by sforberger** [allegro/axion-release-plugin#789]
I am not sure if my problem is a bug.

With Version 1.18.0 the default versionCreator changes from simple to VERSION_WITH_BRANCH.

gradle currentVersion on mainbranch is still 1.2.0-SNAPSHOT

Gradle release creates the Tag v1.2.0. 
But the gitlab-ci pipeline running on the tagged version, publishs Version 1.2.0-v1.2.0 to maven repository.

It looks like the decorate step is now also being executed for a release

With
`scmVersion {
    versionCreator("simple")
}`
it works as expected.

**Comment by bgalek** [comment]
hi! 
Can you make sure that on gitlab-ci you checkout on **branch** not tag? it seems like 1.2.0-v1.2.0 is just {version}-{tag}

**Comment by sforberger** [comment]
Hi,
git strategy is set to git fetch.
I am using Axion to create the Release-Tag.

**Comment by bgalek** [comment]
could you add "git status" command before release step and show me your build output?

**Comment by sforberger** [comment]
git status
HEAD detached at cc9f1e8
nothing to commit, working tree clean

**Comment by sforberger** [comment]
$ git status
HEAD detached at 94bcecc
nothing to commit, working tree clean
$ gradle currentVersion
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.9/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 
> Task :buildSrc:checkKotlinGradlePluginConfigurationErrors
> Task :buildSrc:generateExternalPluginSpecBuilders UP-TO-DATE
> Task :buildSrc:extractPrecompiledScriptPluginPlugins UP-TO-DATE
> Task :buildSrc:compilePluginsBlocks UP-TO-DATE
> Task :buildSrc:generatePrecompiledScriptPluginAccessors UP-TO-DATE
> Task :buildSrc:generateScriptPluginAdapters UP-TO-DATE
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :conventions-plugin:currentVersion
Project version: 1.20.0-v1.20.0

**Comment by bgalek** [comment]
I see `HEAD detached at 94bcecc`
So as stated in [docs](https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#gitlab-ci):

> Since Gitlab will do a detached head checkout, the branch name has to be overridden when `versionWithBranch` is used.

So just add `-Prelease.overriddenBranchName=${CI_COMMIT_REF_SLUG}` to your release step

**Comment by sforberger** [comment]
I have the overridden branch name in the local gradle.properties

echo "release.overriddenBranchName=$CI_COMMIT_REF_NAME" >> $GRADLE_USER_HOME/gradle.properties

CI_COMMIT_REF_NAME='v1.20.0'

**Comment by bgalek** [comment]
if `CI_COMMIT_REF_NAME='v1.20.0'` than the version resolved will be `1.2.0-v1.2.0`
if CI_COMMIT_REF_NAME will be `master` or `main` this version won't be suffixed with branchname

**Comment by sforberger** [comment]
I switched to CI_COMMIT_REF_SLUG and it's still the same.

**Comment by sforberger** [comment]
`---
variables:
  C4U_CI_RUNNER: c4u-libs-gradle
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
default:
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
    - conventions-plugin/build
    - ".gradle"
    policy: pull-push
before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle
- mkdir -p $GRADLE_USER_HOME
- cp /exchange/gradle.properties $GRADLE_USER_HOME/gradle.properties
- cp /exchange/init.gradle $GRADLE_USER_HOME/init.gradle
- echo "release.overriddenBranchName=$CI_COMMIT_REF_SLUG" >> $GRADLE_USER_HOME/gradle.properties
- if [[ "$AXION_FORCE_VERSION" != "" ]]; then echo "release.forceVersion=$AXION_FORCE_VERSION"
  >> $GRADLE_USER_HOME/gradle.properties; fi
- export LOCALE="de_DE.utf-8"
- export LANG="de_DE.UTF-8"
- export LANGUAGE="de_DE.UTF-8"
- export LC_ALL="de_DE.UTF-8"
- export
build:
  stage: build
  script:
  - gradle --build-cache --refresh-dependencies assemble
  - git status
  - gradle currentVersion
  tags:
  - "${C4U_CI_RUNNER}"
  except:
  - fromsvn
test:
  stage: test
  script: gradle --refresh-dependencies check
  tags:
  - "${C4U_CI_RUNNER}"
  except:
  - fromsvn
publishSnapshotToArtifactoryInternal:
  stage: publish
  script:
  - gradle publishAllPublicationsToArtifactorySnapshotsInternalRepository
  tags:
  - "${C4U_CI_RUNNER}"
  only:
    variables:
    - $EXECUTION_TYPE == "nightly"
publishToArtifactoryInternal:
  stage: publish
  script:
  - gradle publishAllPublicationsToArtifactoryInternalRepository
  tags:
  - "${C4U_CI_RUNNER}"
  only:
  - "/^v([0-9]{1,2}\\.[0-9]{1,2}\\.[0-9]{1,2})$/"
stages:
- build
- test
- publish
`

**Comment by sforberger** [comment]
[cipipeline.txt](https://github.com/user-attachments/files/16500192/cipipeline.txt)
Ci-Pipeline Definition as File

**Comment by bgalek** [comment]
I've tested gitlab-ci integration, and it works fine, I recommend using the release command just like in the docs or this repo:
https://gitlab.com/bgalek/axion-test/-/blob/master/.gitlab-ci.yml?ref_type=heads
https://gitlab.com/bgalek/axion-test/-/jobs/7512709274
(ofc you need to adjust it for your needs)
