### ISSUE TITLE
Custom incrementing rules

### ISSUE THREAD

**Issue by vbuell** [allegro/axion-release-plugin#79]
Axion should support custom semantic version incrementing strategies like:

- Increment patch version if on release branch. Increment minor version otherwise
- Increment pre-release version (rc2 -> rc3) if current version has pre-release part and it ends with digit. Increment patch version otherwise
- etc

**Comment by adamdubiel** [comment]
I have a feeling solving this https://github.com/allegro/axion-release-plugin/issues/52 would cover also this usecase. In general the solution would be adding configurable version incrementer, that could decide how to change the version based on X (where X could be git history or current version).

btw sorry i haven't checked the DI code yet :(

**Comment by vbuell** [comment]
Oh. I didn't see that. You're right, these two tightly coupled...  Will publish a PR soon.
Regarding DI - np. It's not a functional change, you know )

**Comment by vbuell** [comment]
PR was accepted. Closing...

**Comment by adamdubiel** [comment]
It took me long enough, but `1.3.0` is finally here! I changed the naming of configuration option to `versionIncrementer` and added additional rule `branchSpecific`, which delegates execution to other rule depending on branch. Everything is described in [docs](http://axion-release-plugin.readthedocs.org/en/latest/configuration/version.html#incrementing). Once again thanks for coding this feature :)
