### ISSUE TITLE
Add feature to tweet about new version

### ISSUE THREAD

**Issue by jkubrynski** [allegro/axion-release-plugin#80]
I'll be cool to integrate axion with twitter to notify about new versions

**Comment by adamdubiel** [comment]
I don't know if i want to add any Tweeter library as dependency - will have to checkout simple REST API, but even now you could implement it on your own using post-release hook: http://axion-release-plugin.readthedocs.org/en/latest/configuration/hooks.html . Twitter integration would come as yet another predefined action (similar to *commit* and *fileUpdate*).

**Comment by jkubrynski** [comment]
Of course I can do it now on my own :) Just posted issue because tweeting about new version is pretty common useccase

**Comment by adamdubiel** [comment]
Sure, i will implement it as soon as i have some more time :)

**Comment by erichsend** [comment]
As someone who has used this plugin for quite some time, I think it's scope and purpose are well focused and well executed. Perhaps posting to twitter should be left to another generic twitter plugin?
 
(i.e. http://gradle.org/docs/current/userguide/announce_plugin.html)

**Comment by vbuell** [comment]
Totally agreed with @erichsend.

**Comment by jkubrynski** [comment]
There is no problem with using separate plugin as long as people know how should they integrate it. Like pass proper version for example.

**Comment by bgalek** [comment]
i recommend using https://github.com/marketplace/actions/send-tweet-action :)
