### ISSUE TITLE
PushRelease does not push if remote is not called "origin"

### ISSUE THREAD

**Issue by pijpijpij** [allegro/axion-release-plugin#83]
The local repository was referring to its remote under the name of "Chuck_Norris". (In config: [remote "Chuck_Norris"]). when running task pushRelease, it did not push to remote, instead it showed the text: "Changes made to local repository only"
Note in passing that it probably should have failed, since it failed its purpose...

I then changed the remote name "origin" in config, and the push succeeded.

That was using version 1.2.3.

I hope this helps.
PJ

**Comment by adamdubiel** [comment]
I thought i fixed this bug in earlier version, but i guess it persisted somehow.. i will take a look at this.

**Comment by adamdubiel** [comment]
I looked through the code and i see no hardcoded 'origin' - can you post relevant parts of configuration? It should look sth like:

```
scmVersion {
  repository {
    remote = 'Chuck_Norris'
  }
}
```

**Comment by adamdubiel** [comment]
Any more news on that? If so, reopen the issue, i'm closing it for now.
