### ISSUE TITLE
alpha tag and release tag at the same commit yields the wrong version

### ISSUE THREAD

**Issue by philbeiler** [allegro/axion-release-plugin#85]
I did a markNextVersion to do a big version number bump, say 2.0.0. The plugin reported the correct currentVersion 2.0.0-SNAPSHOT --  All is well!!!

We then did the release    currentVersion reported 2.0.0 -- in only ONE cloned work space, all other work spaces still report 2.0.0-SNAPSHOT

Unfortunately, we did not do any comments between the two tags -- so both tags  release-2.0.0-alpha and release-2.0.0 are on the same commit.

It appears that the plugin is preferring the -alpha tag over the release tag.

Is this a possibility?  I know it is a non-normal situation -- but unfortunately it bit me in the behind today - trying to do a production release!

Thanks for any help.

**Comment by adamdubiel** [comment]
Yes, it is possible - i think order in which tags from same commit will be fetch can not be determined - thus you get alpha first. I think the only solution would be to double check alpha commits - if there is one, check if there is some other tag without alpha on same commit.

**Comment by jkrizanic** [comment]
@adamdubiel How should this check be performed?

**Comment by adamdubiel** [comment]
I don't know how to implement it out of my head or what APIs are available. But it does not work out of the box now.

**Comment by adamdubiel** [comment]
Took some time to get here :) But the issue has been fixed. The fix was enabled by change in architecture in 1.5.0 version.
