### ISSUE TITLE
How to autoincrement build number?

### ISSUE THREAD

**Issue by matyasatfp** [allegro/axion-release-plugin#88]
I am trying to use your plugin in our CI system. I have a Github repo with version tags that look like [majorVersion].[buildNumber]. 
If I push something to this repo, I want to run a task, that increments buildNumber by one, and pushes this tag with an empty commit to GIT. Is this possible? When I called release it tried to push the same tag that was already on git (1.0.0)

**Comment by adamdubiel** [comment]
Hm, you basically described how axion-release works, now we need to know why it does not work in your case. Can you show `git tag` and your configuration?

**Comment by matyasatfp** [comment]
So I run gradlew release. When run for the first time, it works correctly, it makes an empty commit with the 1.0.0 tag. But when run for the second time (no commits inbetween) I get the following error:  


    :verifyRelease
    Skipping uncommitted changes check
    Checking if branch is ahead of remote..
    :release
    Creating release commit
    Creating tag: 1.0.0
    :release FAILED

FAILURE: Build failed with an exception.

    * What went wrong:   
    Execution failed for task ':release'.
    > Problem creating tag.

git tag output is:

    C:\CODE\rinoa-art>git tag
    1.0.0
    C:\CODE\rinoa-art>

and the relevant part if the build script:


    scmVersion {
        repository {
            type = 'git'
            directory = project.rootProject.file('./'); // repository location
            remote = 'origin';
            customUsername = gitUsername
            customPassword = gitPassword
        }

        localOnly = false;

        tag {
            prefix = '';
            versionSeparator = '';
            deserialize = { tag, position, tagName -> tagName }
            initialVersion = { tag, position -> "1.0.0" }
        }

        nextVersion {
            suffix = ''
            separator = '' // separator between version and suffix
        }

        createReleaseCommit true; // should create empty commit to annotate release in commit history, false by default
        releaseCommitMessage { version, position -> "commit by panda robot" };

        checks {
            uncommittedChanges = false;
            aheadOfRemote = true;
        }
    }

**Comment by adamdubiel** [comment]
Did you configure `nextVersion` like this on purpose? I think this is source of the problem - `nextVersion` needs a suffix, otherwise there is no saying which tag is version tag, and which belongs to next version. Can you change this and see if it works?

**Comment by adamdubiel** [comment]
Any news here? Did my answer help? :)

**Comment by matyasatfp** [comment]
thanks for the help, adding a suffix would have worked. But I needed something more custom - I wanted in the end our version numbers look like [branch name]-[build number in this branch].   

Also I wanted to use Github access tokens for authorization.. So in the end I rolled my own a wrote a class (that uses jGit) that does all the work. 

But thanks for help! 

PS: For future users more documentation about what format the verision numbers can be and how it can authenticate would be helpful.

**Comment by adamdubiel** [comment]
Versioning schema - i shall add some documentation more to highlight it should be semver compatbile. However in general semver is not a must and it could be replaced by some more "freestyle" versioning as long as some bump-version strategy exists.

As to the documentation - did you read this: http://axion-release-plugin.readthedocs.org/en/latest/configuration/authorization.html ? Github tokens are already supported (since 1.2.3).
