### ISSUE TITLE
Issue with Gradle daemon and cached version numbers between projects...

### ISSUE THREAD

**Issue by philbeiler** [allegro/axion-release-plugin#91]
I seem to have some weird behavior when using the plugin using the Gradle daemon. I typically run with the daemon set to **false** to avoid any issues.  I was wondering if this was possible?

It seems pretty simple to duplicate.  

1. Ensure the daemon has been started
2. In project #1, do currentVersion  (works as expected, and returns the proper value
3. Change to project #2 and do currentVersion  (I get the version number for project #1)
4. export GRADLE_OPTS=..... daemon=false
5. Execute currentVersion  again, and I get the proper version reported for the project.

This is kind a a bummer, as it is possible to publish the wrong version of my artifacts - if I happen to have the daemon enabled.

Thoughts? Possible?  Thanks! Phil

**Comment by adamdubiel** [comment]
Can you give me gradle version as well? I don't remember encountering any problems, and i always used daemon builds.

**Comment by philbeiler** [comment]
Gradle Version 2.5. I also believe that I experienced this issue in previous versions of Gradle. I always use gradlew as well, but I assume that does not really matter. Thanks for looking.

**Comment by adamdubiel** [comment]
I was wondering how is it possible and now i *think* i got something that could cause this kind of behavior. Few versions back there was some static state in plugin, which held version context along with version. This was a very bad idea when people wanted to have multiple versions in single multi-project build, so i refactored it. Maybe this static stuff is being remembered by java spawned by daemon? Which version of axion are you using?

**Comment by philbeiler** [comment]
I was using version 1.2.0.  I upgraded to 1.2.3 (latest version in maven central) and I think the issue is gone... but will need to so some further testing.

**Comment by adamdubiel** [comment]
I just checked out 1.2.0 version and it has this static state. 1.2.3 is no longer affected - that must be it.

**Comment by philbeiler** [comment]
That is great news. I will roll with 1.2.3 for a while. Thanks again.
