### ISSUE TITLE
minor release tag supersedes major alpha tag

### ISSUE THREAD

**Issue by Jarodiv** [allegro/axion-release-plugin#95]
The scenario: 
Using Git Flow you create a release 1.0.0 and set the nextVersion marker on development to 2.0.0-alpha. `gradle currentVersion` reports correctly:

```
release> gradle currentVersion
Project version: 1.0.0

development> gradle currentVersion
Project version: 2.0.0-SNAPSHOT
```

Now we have a hotfix-release on release branch (we are using 'incrementMinorIfNotOnRelease' versionIncrementer):

```
release> gradle currentVersion
Project version: 1.0.1
```

After merging the hotfix back into development, the development version is broken:

```
development> gradle currentVersion
Project version: 1.1.0-SNAPSHOT
```

What happens is, that the merged release tag is 'newer' than the nextVersion marker and thus supersedes it even though it has a smaller version number. This makes it hard to maintain bugfix releases while developing the next major release.

**Comment by adamdubiel** [comment]
Hm, i guess you merged back the bugfix into the development branch? Just looking at the flow, your reasoning is correct. There is no version number comparison there. Workaround would be to recreate nextVersionTag after merge. I will think about some more permanent solution.

**Comment by petarov** [comment]
Hi @adamdubiel, I got a somewhat similar _gitflow_ problem. 
Is it possible to plug a custom rule, so that the latest tag would be fetched regardless of the current [commit tree's history](http://axion-release-plugin.readthedocs.org/en/latest/configuration/version.html#reading). _Latest_ would mean exactly version number comparison in my case.

E.g.,

```groovy
scmVersion {
	branchVersionIncrementer = [
        'develop' : { 
        	c -> c.scmPosition.getLatestTag() // TODO: Get the latest tag without tracing the current commit's history
        }
    ]   
}
```

**Comment by adamdubiel** [comment]
I would rather not do it, the whole point is to trace back the current branch and see the version in local setup. Don't you merge back master to develop once released? This way tag is back in commit history.

**Comment by petarov** [comment]
> Don't you merge back master to develop once released?

Nope, which explains why I can't get a correct SNAPSHOT version number. Thanks for pointing me to that! Axion is great :beer:

To elaborate. All our work goes directly in **develop** and there's a reviewer that merges stable stuff into **master** to build releases. Tags are created from **master**, hence that kind of leaves develop out of the tagging history, unless master is merged back.

**Comment by adamdubiel** [comment]
We use the same flow, but there are usually some additional commits in `release-*` branch or even master (i.e. release commit, version bumps in docs etc), thus we always merge back to develop. Hope this solves the problem :)

**Comment by adamdubiel** [comment]
This issue can be solved by using [highest version](http://axion-release-plugin.readthedocs.io/en/latest/configuration/version.html#tag-with-highest-version) matching, introduced in 1.6.0.
